[window]
ambient = [0.3, 0.3, 0.3]
width = 1600
height = 900
# fullscreen = true
wireframe = true

[scene]
sun.position.cartesian = [1, 0, 0]
camera.position.cartesian = [40, 0, 0]
camera.projection.perspective = 3

[[bodies]]
name = "A"
color = "diffuse"
material.albedo = 0.1

faces_selected = [114, 124, 115, 123, 116, 499, 509, 508, 375, 369, 368, 252, 246, 245]

[bodies.mesh]
shape.path = "/Users/gregoireh/data/meshes/sphere4.obj"
