[restart]
path = "C:/data/kalast-runs/didymos init"
duration_more = 429120
# time_step_factor = 0.1

[window]
colormap = { name = "inferno", vmin = 140, vmax = 360, scalar = "temperature" }

[scene]
camera.position.cartesian = [-19.9, -19.8, -3.7]

[simulation]
pause_first_it = true
elapsed = 66441600
export = { cooldown_start = 0 }
mutual_shadowing = true