[window]
ambient = [0.3, 0.3, 0.3]
width = 1512
height = 982
fullscreen = true
# wireframe = true
colormap = { name = "viridis", scalar = "view_factor" }

[simulation]
routines = "thermal"

[scene]
sun.position.cartesian = [1e8, 0, 0]
camera.position.cartesian = [-30, 0, 0]
camera.projection.perspective = 3

[[bodies]]
name = "Didymos"
color = "data"
material = { albedo = 0.1, emissivity = 0.9, thermal_inertia = 500, density = 2100, heat_capacity = 600 }
interior.grid1d.linear = { size = 40, a = 2e-2 }

# [25533, 17341, 9917, 34621, 25489, 17159, 9867, 34579, 5910, 2214, 3299, 7123, 4411]
# mesh.shape.path = "/Users/gregoireh/data/DART/meshes/didymos-model-v002/9740mm/g_09740mm_spc_obj_didy_0000n00000_v002.obj"
mesh = { shape.shape = "sphere_m1", factor = [0.4095, 0.4005, 0.3035] }
# faces_selected = [25533]

[[bodies]]
name = "Dimorphos"
color = "diffuse"
material = { albedo = 0.1, emissivity = 0.9, thermal_inertia = 500, density = 2100, heat_capacity = 600 }
state.cartesian = { position = [1, 0, 0], reference = "Didymos" }
interior.grid1d.linear = { size = 40, a = 2e-2 }

# mesh.shape.path = "/Users/gregoireh/data/spice/hera/kernels/dsk/g_00243mm_spc_obj_dimo_0000n00000_v004.obj"
# mesh.shape.path = "/Users/gregoireh/data/DART/meshes/dimorphos-model-v003/1960mm/g_01960mm_spc_obj_dimo_0000n00000_v003.obj"
mesh = { shape.shape = "sphere_m1", factor = [0.0895165, 0.0825, 0.0575] }
faces_selected = []