[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
# include = [{ path = "/opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib", format = "wheel" }]