[window]
ambient = [0.3, 0.3, 0.3]
high_dpi = true
width = 1512
height = 982
wireframe = true

[scene]
sun.position.cartesian = [1, 0, 0]
camera.position.cartesian = [10, 0, 0]
camera.projection.perspective = 3

[[bodies]]
name = "Apophis"
color = "diffuse"
mesh = { shape.path = "/Users/gregoireh/data/kalast/runs/Apophis flyby Hakan/apophis_new.obj", factor = [1e-3, 1e-3, 1e-3] }
material.albedo = 0.3
faces_selected = [2288, 1556, 333, 907, 1188, 1169, 1235]
