[window]
colormap = { name = "inferno", vmax = 400.0, scalar = "temperature" }
export_frames = true
high_dpi = true
width = 1512
height = 982

[simulation]
routines = "thermal"
step = 600
duration = 90720000
file = { path = "/Users/gregoireh/data/kalast/runs/Apophis flyby Hakan/tumbling/apophis_tumbling2.csv", behavior = "loop" }

[simulation.export]
step = 600
duration = 3024000
period = 3024000
cooldown_start = 87696000

# Duration file: 840h = 3024000s
# *29 = 87696000s
# *30 = 90720000s
#
# 109800 = 30.5h
# 439200 = 30.5h * 4
# 549000 = 30.5h * 5
# 1098000 = 30.5h * 10
# 13399200 = 30.5h * 4 + 3600h * 1
# 117079200 = 30.5h * 4 + 3600h * 9

[scene]
sun.position = "file"
camera.position.cartesian = [-10, 0, 0]
camera.projection.perspective = 3

[[bodies]]
name = "Apophis"
color = "data"
mesh = { shape.path = "/Users/gregoireh/data/kalast/runs/Apophis flyby Hakan/apophis_new.obj", factor = [1e-3, 1e-3, 1e-3] }
interior.grid1d.linear = { size = 40, a = 2e-2 }
state = "file"
record = { rows = [0], columns = [2288, 1556, 333, 907, 1188, 1169, 1235], mesh = true, depth = true }
temperature.scalar = 150

[bodies.material]
albedo = 0.3
emissivity = 0.9
thermal_inertia = 500.0
density = 2100.0
heat_capacity = 600.0
