# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.tpm.properties import Properties

class Column:
    def __init__(self, object: object, object: Properties, object: float) -> None:
        ...
    z: numpy.object
    t: numpy.object
    d: numpy.object
    def clone(self) -> object:
        ...

