# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Column:
    def __init__(self, z: object, prop: Properties, t_init: float) -> None:
        ...
    z: numpy.ndarray
    t: numpy.ndarray
    d: numpy.ndarray
    def clone(self) -> Self:
        ...

