# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.tpm.properties import Properties

def stability(d: float, dt: float, dx2: float) -> float:
    ...
def stability_maxdt(d: float, dx2: float, s: float = ...) -> float:
    ...
def conduction(t: float, f: float, k: float, dx: float) -> float:
    ...
def effective_temperature(dau: float, r: float, a: float, e: float) -> float:
    ...
def radiation_sun(dau: float, cosi: float, a: float) -> float:
    """Absorbed solar flux on a surface element.

    `cosi` is clamped at zero: a facet tilted away from the Sun receives
    nothing, it does not radiate *into* the Sun. Without the clamp a negative
    cosine yields negative insolation, which in a thermophysical model does
    not merely lose a term but actively drives night-side facets below their
    radiative balance.

    `math::cosine_incidence` already clamps, so callers going through it were
    safe; anything computing a dot product directly -- a vectorised inner loop,
    for instance -- was not. The invariant belongs here rather than in each
    caller.
    """
    ...
def radiation_sun_reflected(viewf: float, a: float, cosi: float, dau: float) -> float:
    """Sunlight reflected off one surface element toward another.

    `cosi` is clamped for the same reason as `radiation_sun`: an element
    facing away from the Sun reflects nothing, and an unclamped negative would
    have a shadowed facet *removing* energy from whatever it illuminates.
    """
    ...
def radiation_sun_reflected_reuse(viewf: float, f: float, a: float) -> float:
    """care with albedos"""
    ...
def radiation_emitted(viewf: float, t: float, e: float) -> float:
    ...
def newton_method_fn(t: float, f: float, set3: float, k: float, subt1: float, subt2: float, twodx: float) -> float:
    ...
def newton_method_dfn(set3: float, k: float, twodx: float) -> float:
    ...
def newton_method(t: float, f: float, se: float, k: float, subt1: float, subt2: float, twodx: float) -> float:
    ...
def conduction_1d(t: object, d: object, dtpdx2: object) -> numpy.ndarray:
    ...
def conduction_1d_nonuniform(t: object, d: object, coef_lo: object, coef_hi: object) -> numpy.ndarray:
    ...
def columns(layers: int, facets: int, t: float) -> numpy.ndarray:
    """Temperatures for a whole body: a column of `layers` under each of
    `facets`, all at `t` (K), for `solar_bc`, `bottom_adiabatic` and
    `heat_conduction` to step in place.

    `(layers, facets)`: `t[0]` is the surface, one temperature per facet,
    ready for `mesh.values`; `t[-1]` the bottom; `t[:, i]` the ground under
    facet `i`. Made here rather than with `numpy.full` so that it has the
    float type kalast was built with.
    """
    ...
def solar_bc(t: object, dau: float, cosi: object, prop: Properties, dz: float) -> None:
    """The solar boundary condition, every facet at once: each surface
    temperature, `t[0]`, solved for the balance of the sunlight it
    absorbs, what it radiates, and what it conducts into the layers under
    it,

    ```text
    S (1 - A) max(cos i, 0) / r^2  -  e sigma T0^4  +  k (-3 T0 + 4 T1 - T2) / (2 dz)  =  0
    ```

    `t` is what `columns` made, changed in place; `dau` the distance to
    the Sun (AU); `cosi` a cosine of incidence per facet, as
    `sim.facet_incidence` gives them; `prop` the surface's `Properties`;
    `dz` the thickness of a layer (m).
    """
    ...
def bottom_adiabatic(t: object) -> None:
    """The adiabatic bottom, every facet at once: no heat through the base
    of a column, its last layer, `t[-1]`, at the temperature of the one
    above. `t` is what `columns` made, changed in place.
    """
    ...
def heat_conduction(t: object, prop: Properties, dt: float, dz: float) -> None:
    """Heat conduction, every facet at once: one explicit step of `dt` (s)
    through the interior of each column, its layers `dz` (m) apart,

    ```text
    T_i  +=  D dt / dz^2  (T_{i-1} - 2 T_i + T_{i+1})
    ```

    `t` is what `columns` made, changed in place, and `prop` gives the
    diffusivity `D`. Refused past the stability of the scheme, `D dt /
    dz^2 > 1/2`: `stability_maxdt` gives the largest `dt`.
    """
    ...

