# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Properties:
    def __init__(self, albedo: float, emissivity: float, density: float, heat_capacity: float, thermal_inertia: float, conductivity: float, diffusivity: float) -> None:
        ...
    albedo: float
    emissivity: float
    density: float
    heat_capacity: float
    thermal_inertia: float
    conductivity: float
    diffusivity: float
    def compute_thermal_inertia(self) -> None:
        ...
    def compute_conductivity(self) -> None:
        ...
    def compute_diffusivity(self) -> None:
        ...
    def compute_conductivity_diffusivity(self) -> None:
        ...

