# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class ProgressDebug:
    def __init__(self, frequency: str, digits_full: int, digits_decimal: int) -> None:
        ...
    frequency: str
    digits_full: int
    digits_decimal: int

class Time:
    def __init__(self, dt: float, duration_total: float, duration_record: float) -> None:
        ...
    dt: float
    duration_total: float
    duration_record: float

class Body:
    def new(self, // mesh: Mesh | None, // state: list[list[float]], // spin_period: float, // spin_axis: list[float], // orbit_period: float, // orbit_axis: list[float]) -> Self:
        ...
    mesh: Mesh
    state: numpy.ndarray
    spin_period: float
    spin_axis: numpy.ndarray
    orbit_period: float
    orbit_axis: numpy.ndarray

class BodyDataMap:
    def __init__(self, temperatures: list[numpy.ndarray], thermal_properties_all: int, thermal_properties_map: object) -> None:
        ...
    temperatures: list[numpy.ndarray]
    thermal_properties_all: int
    thermal_properties_map: list[tuple[int, int]]

class Setup:
    def __init__(self) -> None:
        ...
    sun_position: numpy.ndarray
    progress_debug: ProgressDebug
    time: Time

