# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.mesh import Mesh

class ProgressDebug:
    def __init__(self, frequency: str, digits_full: int, digits_decimal: int) -> None:
        ...
    frequency: str
    digits_full: int
    digits_decimal: int

class Time:
    def __init__(self, dt: float, duration_total: float, duration_record: float) -> None:
        ...
    dt: float
    duration_total: float
    duration_record: float

class Body:
    def __init__(self) -> None:
        ...
    mesh: Mesh
    state: numpy.object
    spin_period: float
    spin_axis: numpy.object
    orbit_period: float
    orbit_axis: numpy.object

class BodyDataMap:
    def __init__(self, temperatures: list[numpy.object], thermal_properties_all: int, thermal_properties_map: object) -> None:
        ...
    temperatures: list[numpy.object]
    thermal_properties_all: int
    thermal_properties_map: list[tuple[int, int]]

class Setup:
    def __init__(self) -> None:
        ...
    sun_position: numpy.object
    progress_debug: ProgressDebug
    time: Time

