[window]
colormap = { name = "inferno", vmax = 400.0, scalar = "temperature" }
# export_frames = true
width = 1024
height = 768

[simulation]
routines = "thermal"
step = 600
duration = 41071560

# Annual period: 474.7286379896793 days = 41016554.322308294 s
#   rounded up to 60: 41016600 s
# Spin period: 7.63262 h = 27477.432 s
#   2 periods: 54954.86 s
#   rounded up to 60: 54960 s
# (474.7286379896793 * 24 + 2 * 7.63262) * 3600 = 41071509.186308295 s
#   rounded up to 60: 41071560 s

[simulation.export]
step = 60
duration = 54960
period = 41071560
cooldown_start = 41016600

[scene]
sun.position = "origin"
camera.position.cartesian = [0, -15, 0]
camera.projection.perspective = 5.0

[[bodies]]
name = "RYUGU"
mesh.shape.path = "/Users/gregoireh/data/meshes/ryugu/SHAPE_SFM_49k_v20180804.obj"
interior.grid1d.linear = { size = 40, a = 2e-2 }
spin = { period = 27477.432, obliquity = 171 }
temperature.scalar = 150
color = "data"
record = { rows = [0], columns = [0], mesh = true, depth = true }

[bodies.material]
albedo = 0.1
emissivity = 0.9
thermal_inertia = 500.0
density = 2100.0
heat_capacity = 600.0

[bodies.state.orbit]
a = 1.190962269512474
e = 0.1910200912732423
