# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Orbit:
    """An orbit about the Sun from two of its elements: `a`, the semi-major axis
    (AU), and `e`, the eccentricity -- which is all its shape and period
    take. Placed in its own plane: x toward perihelion, z along the orbit's
    angular momentum, so a body goes round counter-clockwise seen from +z.
    Tilt a body's spin axis in that frame for its obliquity.
    """
    a: float
    """Semi-major axis (AU)."""
    e: float
    """Eccentricity, `0 <= e < 1`."""
    def __init__(self, a: float, e: float) -> None:
        """An orbit about the Sun: `a` its semi-major axis (AU), `e` its
        eccentricity. In its own plane, x toward perihelion and z along its
        angular momentum: tilt a body's spin axis in that frame for its
        obliquity. Didymos's:

        ```python
        didymos = kalast.astro.Orbit(a=1.6426, e=0.3832)
        year = didymos.period                    # s, 770 days
        pos = didymos.position(t)                # AU, t s after perihelion
        sim.sun.pos = -pos * kalast.util.AU      # the body at the origin
        ```
        """
        ...
    period: float
    """Its period (s), by Kepler's third law: `a^1.5` years."""
    def position(self, t: float) -> numpy.ndarray:
        """Where the body is `t` seconds after perihelion, in AU, in the orbit's
        plane -- the Sun at the origin -- as `(x, y, 0)`.
        """
        ...

