# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Entity:
    def __init__(self, id: int, name: str, frame: str, label: str) -> None:
        ...
    id: int
    name: str
    frame: str

class Body:
    def __init__(self, id: int, name: str, frame: str, label: str, radii: list[float], orbit_period: float, spin_period: float) -> None:
        ...
    id: int
    name: str
    frame: str
    radii: numpy.ndarray
    orbit_period: float
    spin_period: float
    def radius(self) -> float:
        ...
    def diameter(self) -> float:
        ...
    def flattening_radius(self) -> float:
        ...

class Camera:
    def __init__(self, id: int, name: str, frame: str, label: str, px: list[int], fovy: float, filters: list[str]) -> None:
        ...
    id: int
    name: str
    frame: str
    label: str
    px: numpy.ndarray
    fovy: float
    def npx(self) -> int:
        ...

class Spacecraft:
    def __init__(self, id: int, name: str, frame: str, label: str, id_cameras: list[str]) -> None:
        ...
    id: int
    name: str
    frame: str

