# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Entity:
    def __init__(self, object: int, object: str, object: str, object: str) -> None:
        ...
    id: int
    name: str
    frame: str

class Body:
    def __init__(self, object: int, object: str, object: str, object: str, object: list[float], object: float, object: float) -> None:
        ...
    id: int
    name: str
    frame: str
    radii: numpy.object
    orbit_period: float
    spin_period: float
    def radius(self) -> float:
        ...
    def diameter(self) -> float:
        ...
    def flattening_radius(self) -> float:
        ...

class Camera:
    def __init__(self, object: int, object: str, object: str, object: str, object: list[int], object: float, object: list[str]) -> None:
        ...
    id: int
    name: str
    frame: str
    label: str
    px: numpy.object
    fovy: float
    def npx(self) -> int:
        ...

class Spacecraft:
    def __init__(self, object: int, object: str, object: str, object: str, object: list[str]) -> None:
        ...
    id: int
    name: str
    frame: str

