# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from typing import Sequence

class Spin:
    """The spin state: where the pole points and where the body has got to.

    The convention is convex inversion's (Kaasalainen & Torppa 2001): the
    ecliptic-frame pole is `(cos b cos l, cos b sin l, sin b)`, the mesh is
    body-fixed with its rotation axis along `+z`, and the transformation from
    one to the other is

    ```text
    M(t) = Rz(-phase(t)) Ry(pole_lat - pi/2) Rz(-pole_lon)
    ```

    so `M(t) * pole = +z` for every `t`. Everything here is **radians**, which
    is the unit the rest of the engine uses, while the literature quotes poles
    in degrees -- `numpy.radians(...)` at the call site is deliberate rather
    than an oversight.

    `period` and the epochs share whatever time unit the caller likes; only
    their ratio is used.
    """
    pole_lon: float
    """Pole ecliptic longitude, radians."""
    pole_lat: float
    """Pole ecliptic latitude, radians."""
    period: float
    """Sidereal rotation period, in the same unit as the epochs."""
    phase0: float
    """Rotation phase at `epoch0`, radians."""
    epoch0: float
    """The epoch `phase0` refers to."""
    def __init__(self, pole_lon: float = ..., pole_lat: float = ..., period: float = ..., phase0: float = ..., epoch0: float = ...) -> None:
        """Defaults to a pole at the ecliptic north and a unit period, which is
        the spin that makes the algebra checkable rather than a typical one.
        """
        ...
    def phase_at(self, epoch: float) -> float:
        """Rotation phase at `epoch`, radians, unwrapped."""
        ...
    def pole(self) -> list[float]:
        """The spin axis as a unit vector in the ecliptic frame."""
        ...

class Point:
    """One epoch of a light curve."""
    flux: float
    """The disc integral. See the module docs for its units."""
    alpha: float
    """Solar phase angle, radians."""
    lit_fraction: float
    """Fraction of the illuminated cross-section that is not shadowed,
    area-weighted: `sum A mu0 lit / sum A mu0` over facets facing the Sun.

    A diagnostic, not part of the flux. It is the quantity the shadowing
    notes tabulate as "% shadowed" (one minus this), so a real target can
    be placed on those tables rather than guessed at. Exactly 1 with
    `Options::shadowing` off, which is what makes it worth reporting.
    """
    overflowed: bool
    """True if any facet hit [`shadowing::MAX_PIECES`], so its lit area is an
    upper bound rather than the answer.
    """

class Curve:
    """A computed light curve: one entry per epoch, as arrays.

    Arrays rather than a list of [`Point`]s because everything downstream
    -- a plot, a chi-squared, a fit -- wants columns, and unpacking a list
    of objects into them is boilerplate the caller should not write.
    """
    flux: numpy.ndarray
    """The disc integral per epoch. Units in the module docs."""
    alpha: numpy.ndarray
    """Solar phase angle per epoch, radians."""
    phase: numpy.ndarray
    """Rotation phase per epoch, radians, unwrapped."""
    epoch: numpy.ndarray
    """The epochs, echoed back so a plot needs one object."""
    lit_fraction: numpy.ndarray
    """Unshadowed fraction of the illuminated cross-section, per epoch."""
    overflowed: bool
    """True if any facet at any epoch hit the clipper's piece cap."""
    def magnitude(self, reference: float | None = ...) -> numpy.ndarray:
        """Magnitudes relative to `reference`, or to the median flux.

        The median is the out-of-event level of a curve with an eclipse in
        it, which a mean is not.
        """
        ...
    def __len__(self) -> int:
        ...

def flux(vertices: numpy.ndarray, indices: object, sun: object, observer: object, law: object, shadowing: bool = ..., visibility: bool = ...) -> Point:
    """The disc-integrated flux at one epoch.

    `vertices` is `(n, 3)` in any float dtype, `indices` is `(m, 3)` or
    flat `(3m,)` uint32 -- `kalast.mesh.Mesh` hands back the flat form, and
    `mesh.positions * axes` is float64 -- and
    `sun` and `observer` point from the body toward each, in the mesh's own
    frame. `law` is a `Hapke` or a `LommelSeeligerLambert`.

    Use this when the geometry is placed already -- a binary, or a body
    whose vertices you move yourself. `lightcurve` is the rotating
    single-body case.

    Set `shadowing` and `visibility` to False for a convex shape: no facet
    occludes another there, so both passes return 1 and cost the run.
    """
    ...
def lightcurve(vertices: numpy.ndarray, indices: object, spin: Spin, sun: object, observer: object, epochs: Sequence[float] | numpy.ndarray, law: object, shadowing: bool = ..., visibility: bool = ...) -> Curve:
    """A light curve: one rotating body over a series of epochs.

    `vertices` is `(n, 3)` in any float dtype and `indices` `(m, 3)` or
    flat `(3m,)` uint32, in the
    body-fixed frame with the rotation axis along `+z`. `sun` and
    `observer` are **ecliptic-frame** directions from the body, either one
    each or one per epoch. `epochs` shares its unit with `spin.period`.

    The mesh is not rotated -- the two directions are carried into the body
    frame instead, which is exactly equivalent and two vectors per epoch
    rather than every vertex.
    """
    ...

