# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Vertex:
    def __init__(self, pos: list[float] | None, tex: list[float] | None, normal: list[float] | None, tangent: list[float] | None, bitangent: list[float] | None, color: list[float] | None, color_mode: int | None) -> None:
        ...
    pos: numpy.ndarray
    tex: numpy.ndarray
    normal: numpy.ndarray
    tangent: numpy.ndarray
    bitangent: numpy.ndarray
    color: numpy.ndarray
    color_mode: int

class Facet:
    def __init__(self, pos: list[float] | None, normal: list[float] | None, area: float | None) -> None:
        ...
    pos: numpy.ndarray
    normal: numpy.ndarray
    area: float

class Material:
    def diffuse_bytes(self) -> list[int]:
        ...
    def diffuse_dimensions(self) -> tuple[int, int]:
        ...
    def normal_bytes(self) -> list[int]:
        ...
    def normal_dimensions(self) -> tuple[int, int]:
        ...

class Mesh:
    def inward_facing_facets(self) -> numpy.ndarray:
        """Indices of facets whose normal points into the body."""
        ...
    def flip_facets(self, facets: numpy.ndarray) -> int:
        """Reverse the winding of the given facets. Returns how many were flipped."""
        ...
    def __init__(self, path: str | None, update_pos: object, vertices: list[Vertex] | None, facets: list[Facet] | None, indices: list[int] | None, material_id: int | None) -> None:
        ...
    def load(self, _cls: object, pyo3: object, path: str, update_pos: object) -> Self:
        ...
    vertices: VerticesView
    indices: numpy.ndarray
    facets: FacetsView
    material_id: int | None
    _vertices_before_flatten: VerticesBeforeFlattenView
    positions: numpy.ndarray
    textures: numpy.ndarray
    normals: numpy.ndarray
    tangents: numpy.ndarray
    bitangents: numpy.ndarray
    colors: numpy.ndarray
    color_modes: numpy.ndarray
    def flatten(self) -> None:
        ...
    def smoothen(self) -> None:
        ...
    def recompute_facets(self) -> None:
        ...
    def mark_colors_dirty(self) -> None:
        """Call after mutating vertex color/color_mode/extra in place (e.g. a"""
        ...
    def is_flat(self) -> bool:
        ...
    def get_facet_vertices(self, facet: int) -> FacetVerticesView:
        ...
    def get_facet_indices(self, facet: int) -> list[int]:
        ...
    def get_facet_positions(self, facet: int) -> list[numpy.ndarray]:
        ...
    def get_facet_normals(self, facet: int) -> list[numpy.ndarray]:
        ...
    def get_facet_colors(self, facet: int) -> list[numpy.ndarray]:
        ...
    def update_all_vertices_colors(self, mode: int, color: list[float]) -> None:
        ...
    def intersect(self, p: list[float], u: list[float], exit_first: bool) -> tuple[int, list[float]] | None:
        ...

class FacetVerticesView:
    ...

