# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Vertex:
    def __init__(self, pos: list[float] | None, tex: list[float] | None, normal: list[float] | None, tangent: list[float] | None, bitangent: list[float] | None, color: list[float] | None, color_mode: int | None) -> None:
        ...
    pos: numpy.object
    tex: numpy.object
    normal: numpy.object
    tangent: numpy.object
    bitangent: numpy.object
    color: numpy.object
    color_mode: int

class Facet:
    def __init__(self, pos: list[float] | None, normal: list[float] | None, area: float | None) -> None:
        ...
    pos: numpy.object
    normal: numpy.object
    area: float

class Material:
    def diffuse_bytes(self) -> list[int]:
        ...
    def diffuse_dimensions(self) -> tuple[int, int]:
        ...
    def normal_bytes(self) -> list[int]:
        ...
    def normal_dimensions(self) -> tuple[int, int]:
        ...

class Mesh:
    def inward_facing_facets(self) -> numpy.object:
        """Indices of facets whose normal points into the body.

        A quick shape-model sanity check. Reversed winding on a few triangles
        is common in decimated models and is quietly destructive: such a facet
        is permanently dark in the thermophysical model, and a hemicube placed
        on it reports a self view factor near 1. Assumes a roughly star-shaped
        body, so inspect the result rather than trusting it blindly.
        """
        ...
    def flip_facets(self, facets: numpy.object) -> int:
        """Reverse the winding of the given facets. Returns how many were flipped.

        Call before `app.start()`: the GPU buffers are built once when the
        window opens, so a later flip would fix the physics and leave the
        shadow map and hemicube drawing the old winding.
        """
        ...
    def __init__(self, path: str | None, update_pos: object, vertices: list[Vertex] | None, facets: list[Facet] | None, indices: list[int] | None, material_id: int | None) -> None:
        ...
    def load(self, _cls: object, pyo3: object, path: str, update_pos: object) -> object:
        ...
    vertices: object
    indices: numpy.object
    facets: object
    material_id: int | None
    _vertices_before_flatten: object
    positions: numpy.object
    textures: numpy.object
    normals: numpy.object
    tangents: numpy.object
    bitangents: numpy.object
    colors: numpy.object
    color_modes: numpy.object
    def flatten(self) -> None:
        ...
    def smoothen(self) -> None:
        ...
    def recompute_facets(self) -> None:
        ...
    def mark_colors_dirty(self) -> None:
        """Call after mutating vertex color/color_mode/extra in place (e.g. a
        per-facet colormap) to request a GPU re-upload on the next frame.
        The renderer only re-uploads a mesh's color data when this has been
        set, so a static-colored mesh never pays that cost after its
        initial upload -- a script that recolors every frame needs to call
        this every frame too, the same way sim.export_once() works.
        """
        ...
    def is_flat(self) -> bool:
        ...
    def get_facet_vertices(self, facet: int) -> FacetVerticesView:
        ...
    def get_facet_indices(self, facet: int) -> list[int]:
        ...
    def get_facet_positions(self, facet: int) -> list[numpy.object]:
        ...
    def get_facet_normals(self, facet: int) -> list[numpy.object]:
        ...
    def get_facet_colors(self, facet: int) -> list[numpy.object]:
        ...
    def update_all_vertices_colors(self, mode: int, color: list[float]) -> None:
        ...
    def intersect(self, p: list[float], u: list[float], exit_first: bool) -> tuple[int, list[float]] | None:
        ...

class FacetVerticesView:
    ...

