# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class LommelSeeligerLambert:
    """The same mix as a *parameter set*, so a light curve can be handed "a law".

    [`lommel_seeliger_lambert`] is the formula; this is the pair of numbers it
    is fitted with. Convex inversion quotes exactly these two, and the
    endpoints are the other two laws exactly -- `c = 1` is pure
    Lommel-Seeliger, `c = 0` is pure Lambert -- so this one struct covers three
    of the four laws in this module and [`Hapke`] covers the fourth. That is
    why [`crate::lightcurve::Law`] has two variants rather than four.

    **It has no phase dependence of its own.** `r` here is a function of `mu0`
    and `mu` only, so the phase curve it produces comes entirely from the
    changing geometry: no opposition surge, no phase reddening. That is the
    known shape of the model rather than an omission -- inversion work
    multiplies it by a separate empirical phase function -- but it does mean a
    fit to data spanning a range of `alpha` wants [`Hapke`], or a phase
    function applied outside this module.
    """
    w: float
    """Single-scattering albedo, `0..1`. Not the geometric albedo."""
    c: float
    """Lommel-Seeliger fraction: `1` is pure LS, `0` pure Lambert."""
    def __init__(self, w: float = ..., c: float = ...) -> None:
        ...
    def reflectance(self, mu0: float, mu: float) -> float:
        ...

class Hapke:
    """Hapke's bidirectional reflectance, IMSA form, for a smooth surface."""
    w: float
    """Single-scattering albedo, `0..1`."""
    b: float
    """Henyey-Greenstein lobe width, `0..1`."""
    c: float
    """Henyey-Greenstein backward fraction, `0..1`."""
    b0: float
    """Opposition surge amplitude."""
    h: float
    """Opposition surge angular width, radians."""
    theta_bar: float
    """Macroscopic roughness: the mean slope angle of sub-facet relief, in
    radians. `0` is a smooth surface; the literature quotes 20-30 deg for
    most asteroids. Must be in `[0, pi/2)`.
    """
    k: float
    """Hapke's (2008) porosity factor, `1` for none, the IMSA as it was: the
    reflectance is `K` times larger and the `H` functions are taken at
    `mu / K`. From the filling factor `phi`, one minus the porosity,
    `K = -ln(1 - 1.209 phi^(2/3)) / (1.209 phi^(2/3))`. The Hapke 2012 fits
    of the Martian moons carry it: 1.19 for Phobos (87 % porosity,
    Fornasier et al. 2024) and 1.21 for Deimos (86 %, Wargnier et al.
    2025). `[1, inf)`.
    """
    def __init__(self, w: float = ..., b: float = ..., c: float = ..., b0: float = ..., h: float = ..., theta_bar: float = ..., k: float = ...) -> None:
        ...
    def reflectance(self, mu0: float, mu: float, alpha: float) -> float:
        ...
    def bond_albedo(self) -> float:
        ...
    def roughness_terms(self, mu0: float, mu: float, alpha: float) -> tuple[float, float, float]:
        """The roughness terms `(mu0e, mue, S)` at this geometry.

        `(mu0, mu, 1)` when `theta_bar` is zero. `S = 1` at zero azimuth when
        `i <= e`, which is the identity that pins which branch is which.
        """
        ...

class Atmosphere:
    """A dusty atmosphere over a body, per `body.atmosphere`."""
    tau: float
    """Vertical optical depth at the surface."""
    scale_height: float
    """Scale height of the dust, in the scene's units."""
    radius: float
    """The planet's radius, in the scene's units: with the scale height, how
    long a slanted path through the air is, and with `polar_radius` the
    level the optical depth `tau` is given at -- the equatorial radius of
    that ellipsoid.
    """
    polar_radius: float | None
    """The ellipsoid's polar radius, about the body's own z axis; `None`, a
    sphere of `radius`. Above the ellipsoid the air is thinner, below it
    thicker: the dust's optical depth goes as the surface pressure,
    `tau exp(-height / scale_height)` -- on Mars twice as much over
    Hellas as over the uplands round it. A sphere would put the poles
    20 km under it.
    """
    omega: float
    """The dust's single-scattering albedo, `0..1`."""
    g1: float
    """The phase function's first forward lobe's asymmetry, `0..1`."""
    g2: float
    """The second's."""
    q: float
    """The first lobe's weight, `0..1`."""
    albedo: float | None
    """The surface's mean albedo round about, for the light the surface and
    the atmosphere send each other. `None`: each facet's own.
    """
    def __init__(self, tau: float = ..., scale_height: float = ..., radius: float = ..., polar_radius: float | None = ..., omega: float = ..., g1: float = ..., g2: float = ..., q: float = ..., albedo: float | None = ...) -> None:
        ...
    def iof(self, mu0_facet: float, mu0: float, mu: float, alpha: float, albedo: float, lit: float = ..., height: float = ...) -> float:
        """The I/F at a point of a Lambert surface of albedo `albedo` under this
        atmosphere: `mu0_facet` the Sun's cosine from the facet's normal,
        `mu0` and `mu` the Sun's and the camera's from the local vertical,
        `alpha` the phase angle, `lit` how much of the direct beam reaches the
        facet, `height` above the ellipsoid.
        """
        ...
    def level(self, lat: float) -> float:
        """The ellipsoid's radius at geocentric latitude `lat`, radians."""
        ...
    def airmass(self, mu: float) -> float:
        """Chapman's airmass at `mu`, over a sphere."""
        ...

def lambert(albedo: float) -> float:
    """Isotropic scattering: brightness independent of viewing geometry.

    `r = A / pi`. The `mu0` that makes this Lambert's cosine law lives in the
    `I = r J mu0` convention above, not in `r` itself.
    """
    ...
def lommel_seeliger(w: float, mu0: float, mu: float) -> float:
    """Single scattering from a dark particulate half-space.

    `r = (w / 4pi) / (mu0 + mu)`, so the emergent radiance carries
    `mu0 / (mu0 + mu)` -- the limb-darkening signature of a regolith, and
    visibly different from Lambert's `mu0` away from opposition.

    `w` here is the single-scattering albedo, not the geometric albedo.
    """
    ...
def lommel_seeliger_lambert(w: float, c: float, mu0: float, mu: float) -> float:
    """The `c * LS + (1 - c) * Lambert` mix of the convex-inversion literature.

    The Lambert term stands in for multiple scattering, which Lommel-Seeliger
    omits by construction and which matters as the surface brightens. `c = 1`
    is pure Lommel-Seeliger.
    """
    ...
def h_function(w: float, x: float) -> float:
    """Chandrasekhar's `H` function, Hapke's 2002 rational approximation.

    `H` carries the multiple scattering, and it is defined implicitly by

    ```text
    H(x) = 1 + w x H(x) / 2 * integral_0^1 H(u) / (x + u) du
    ```

    which has no closed form. Hapke's 1993 approximation
    `H = (1 + 2x) / (1 + 2x sqrt(1-w))` is good to about 4 %; the 2002 form
    below is good to under 1 %, for the same cost, and `tests/test_scattering.py`
    checks it against the integral equation directly rather than taking that
    on trust.
    """
    ...
def henyey_greenstein(b: float, c: float, alpha: float) -> float:
    """Two-lobe Henyey-Greenstein particle phase function, normalised so that its
    average over the sphere is 1.

    `b` in `[0, 1)` is the lobe width and `c` in `[0, 1]` the backward
    fraction: `c = 0` is purely forward-scattering, `c = 1` purely backward.
    `alpha` is the phase angle in radians, so `alpha = 0` is opposition.

    **Mind the sign convention**, which this got wrong first time round.
    `alpha` is the Sun-target-observer angle, so `alpha = 0` is *back*scatter,
    while Henyey-Greenstein is normally written in the scattering angle
    `theta = pi - alpha`, where `theta = 0` is *forward*. The two lobes below
    are therefore the opposite way round from the textbook expression, and
    writing them the textbook way leaves the normalisation perfectly intact
    while pointing the asymmetry backwards -- a phase curve that brightens
    away from opposition. `tests/test_scattering.py` checks the direction
    separately from the normalisation for exactly that reason, and that is
    what caught it.
    """
    ...
def opposition_surge(b0: float, h: float, alpha: float) -> float:
    """The shadow-hiding opposition surge.

    `B(alpha) = B0 / (1 + tan(alpha/2) / h)`, a sharp brightening within a few
    degrees of opposition as particles stop shadowing one another. `B0` is its
    amplitude at exactly zero phase and `h` its angular width.
    """
    ...

