# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class LommelSeeligerLambert:
    """The same mix as a *parameter set*, so a light curve can be handed "a law".

    [`lommel_seeliger_lambert`] is the formula; this is the pair of numbers it
    is fitted with. Convex inversion quotes exactly these two, and the
    endpoints are the other two laws exactly -- `c = 1` is pure
    Lommel-Seeliger, `c = 0` is pure Lambert -- so this one struct covers three
    of the four laws in this module and [`Hapke`] covers the fourth. That is
    why [`crate::lightcurve::Law`] has two variants rather than four.

    **It has no phase dependence of its own.** `r` here is a function of `mu0`
    and `mu` only, so the phase curve it produces comes entirely from the
    changing geometry: no opposition surge, no phase reddening. That is the
    known shape of the model rather than an omission -- inversion work
    multiplies it by a separate empirical phase function -- but it does mean a
    fit to data spanning a range of `alpha` wants [`Hapke`], or a phase
    function applied outside this module.
    """
    w: float
    """Single-scattering albedo, `0..1`. Not the geometric albedo."""
    c: float
    """Lommel-Seeliger fraction: `1` is pure LS, `0` pure Lambert."""
    def __init__(self, w: float, c: float) -> None:
        ...
    def reflectance(self, mu0: float, mu: float) -> float:
        ...

class Hapke:
    """Hapke's bidirectional reflectance, IMSA form, for a smooth surface."""
    w: float
    """Single-scattering albedo, `0..1`."""
    b: float
    """Henyey-Greenstein lobe width, `0..1`."""
    c: float
    """Henyey-Greenstein backward fraction, `0..1`."""
    b0: float
    """Opposition surge amplitude."""
    h: float
    """Opposition surge angular width, radians."""
    theta_bar: float
    """Macroscopic roughness: the mean slope angle of sub-facet relief, in
    radians. `0` is a smooth surface; the literature quotes 20-30 deg for
    most asteroids. Must be in `[0, pi/2)`.
    """
    def __init__(self, w: float, b: float, c: float, b0: float, h: float, theta_bar: float) -> None:
        ...
    def reflectance(self, mu0: float, mu: float, alpha: float) -> float:
        ...
    def bond_albedo(self) -> float:
        ...
    def roughness_terms(self, mu0: float, mu: float, alpha: float) -> tuple[float, float, float]:
        """The roughness terms `(mu0e, mue, S)` at this geometry.

        `(mu0, mu, 1)` when `theta_bar` is zero. `S = 1` at zero azimuth when
        `i <= e`, which is the identity that pins which branch is which.
        """
        ...

