[window]
# 8
# 14
colormap = { name = "cividis", vmax = 8, scalar = "file" }

export_frames = true
high_dpi = true
# width = 1024
# height = 768

[simulation]
step = 60
duration = 12000

[simulation.export]
step = 60
duration = 12000
period = 120000
cooldown_start = 0

[scene]
camera.position.cartesian = [0, 1, 0]

[[bodies]]
name = "Apophis"
mesh = { shape.path = "/Users/gregoireh/data/kalast/runs/Apophis flyby Hakan/apophis_new.obj", factor = [1e-3, 1e-3, 1e-3] }
color = "data"

# /Users/gregoireh/data/kalast/runs/Apophis Elisa/results_slope_change3-2.csv
# /Users/gregoireh/data/kalast/runs/Apophis Elisa/results_gravity_norm_change_percentage2-2.csv
file_data = { path = "/Users/gregoireh/data/kalast/runs/Apophis Elisa/results_slope_change3-2.csv" }
