//! Building and launching a Rust example from the editor.
//!
//! A `.py` script runs *inside* the editor: the same process, the same
//! window, the scene appearing in the viewport. A `.rs` example cannot --
//! it is a separate program that links kalast as a library, so it has to be
//! compiled and then launched, and it opens a window of its own.
//!
//! So the editor is a different kind of thing for Rust: an editor, a build
//! button and a launcher, rather than a host. What it does keep is the log
//! -- cargo and the example both inherit the redirected stdout, so their
//! output lands in the Log panel beside everything else.

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

/// Where the generated wrapper crate lives.
///
/// Under `target/`, so it is ignored, disposable, and shares the build
/// directory with everything else -- which is what keeps a hosted build to
/// seconds instead of recompiling kalast from scratch.
pub fn wrapper_dir() -> std::path::PathBuf {
    std::path::Path::new("target").join("kalast-hosted")
}

/// Where its cdylib lands.
pub fn dylib_path(release: bool) -> std::path::PathBuf {
    let profile = if release { "release" } else { "debug" };
    // The repo's own build directory, not the wrapper's: the build sets
    // `CARGO_TARGET_DIR` there so kalast is not compiled a second time.
    std::path::Path::new("target")
        .join(profile)
        .join(format!(
            "{}kalast_hosted{}",
            std::env::consts::DLL_PREFIX,
            std::env::consts::DLL_SUFFIX
        ))
}

/// Write a crate that wraps `example` and exports what the host calls.
///
/// The example is included as a module, so its own `fn main` becomes
/// `example::main` and nothing has to be written in the file itself. It is a
/// generated crate rather than a target in this manifest because a declared
/// target whose file is missing breaks every cargo command in the repo,
/// including for someone who never opens the editor.
pub fn write_wrapper(example: &std::path::Path, features: &str) -> Result<(), String> {
    let dir = wrapper_dir();
    let src = dir.join("src");
    std::fs::create_dir_all(&src).map_err(|e| format!("cannot create {}: {e}", src.display()))?;

    let root = std::env::current_dir()
        .map_err(|e| format!("cannot read the working directory: {e}"))?;
    let example_path = root.join(example);
    let example = example_path.to_string_lossy().replace('\\', "/");
    let kalast = root.to_string_lossy().replace('\\', "/");

    std::fs::write(
        dir.join("Cargo.toml"),
        format!(
            "# Generated by kalast's editor. Rewritten for each example hosted;\n\
             # nothing here is meant to be edited or committed.\n\
             [package]\n\
             name = \"kalast-hosted\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n\n\
             [lib]\n\
             crate-type = [\"cdylib\"]\n\n\
             [dependencies]\n\
             kalast = {{ path = \"{kalast}\"{features} }}\n\n\
             [workspace]\n"
        ),
    )
    .map_err(|e| format!("cannot write the wrapper manifest: {e}"))?;

    // The example is *copied* into the wrapper rather than `include!`d or
    // declared as a module, and both of those were tried first:
    //
    // - a module puts `fn main` out of reach, because an example's main is
    //   private and privacy does not reach outwards;
    // - `include!` cannot carry a file whose header is `//!`, since inner
    //   attributes may not come from a macro expansion -- and every example
    //   here starts with one.
    //
    // Copying costs a rewrite of those header lines to `//`, and buys a file
    // where `main` is an ordinary private function of the same module as the
    // exports below.
    let source = std::fs::read_to_string(&example_path)
        .map_err(|e| format!("cannot read {}: {e}", example_path.display()))?;
    let source: String = source
        .lines()
        .map(|l| match l.strip_prefix("//!") {
            Some(rest) => format!("//{rest}\n"),
            None => format!("{l}\n"),
        })
        .collect();

    // Only when it is not already there: a duplicate import is an error, and
    // an example may well have written this one itself.
    let wgpu_import = if source.contains("use kalast::wgpu") || source.contains("use wgpu") {
        ""
    } else {
        "// So that an example naming `wgpu::Color`, as one setting a colour\n\
         // does, compiles without depending on wgpu itself.\n\
         use kalast::wgpu;\n\n"
    };

    std::fs::write(
        src.join("lib.rs"),
        format!(
            "// Generated by kalast's editor from\n\
             // {example}\n\
             //\n\
             // Rewritten every time an example is built for hosting. Nothing\n\
             // here is meant to be edited: change the file above.\n\n\
             {wgpu_import}\
             {source}\n\
             /// What this was built against, checked by the host first.\n\
             #[unsafe(no_mangle)]\n\
             pub extern \"C\" fn kalast_abi() -> u64 {{\n\
             \x20   kalast::app::abi_fingerprint()\n\
             }}\n\n\
             /// Run the example's own `main`, with the host reachable from it.\n\
             ///\n\

             /// # Safety\n\
             ///\n\
             /// `host` must outlive the call.\n\
             #[unsafe(no_mangle)]\n\
             pub unsafe extern \"C\" fn kalast_example(host: *const kalast::app::hosted::HostApi) {{\n\
             \x20   unsafe {{ kalast::app::hosted::set_host(host) }};\n\
             \x20   main();\n\
             \x20   kalast::app::hosted::clear_host();\n\
             }}\n"
        ),
    )
    .map_err(|e| format!("cannot write the wrapper: {e}"))?;

    Ok(())
}

/// Build that cdylib, **with this build's own feature set**.
///
/// Not optional. The `python` feature changes the layout of `Shared` and
/// `Tick`, so a guest built without it and handed an `App` from a host with
/// it reads the wrong bytes. The host is the only thing that knows which it
/// is, so it says so on the command line.
pub fn build_hosted(example: &std::path::Path, release: bool, busy: Arc<AtomicBool>) {
    // Matching the host's features is not optional: `python` changes the
    // layout of `Shared` and `Tick`, and a guest built without it would be
    // handed an `App` whose fields are somewhere else.
    let features = if cfg!(feature = "python") {
        ", features = [\"python\"]"
    } else {
        ""
    };
    if let Err(e) = write_wrapper(example, features) {
        println!("{e}");
        busy.store(false, Ordering::SeqCst);
        return;
    }

    let manifest = wrapper_dir().join("Cargo.toml");
    let target_dir = std::env::current_dir().unwrap_or_default().join("target");
    std::thread::spawn(move || {
        let mut cmd = std::process::Command::new("cargo");
        cmd.args(["build", "--color=never", "--manifest-path"])
            .arg(&manifest)
            // The repo's own build directory, so kalast is not compiled a
            // second time: this is the difference between a hosted build
            // taking seconds and taking a minute.
            .env("CARGO_TARGET_DIR", &target_dir);
        if release {
            cmd.arg("--release");
        }
        println!("$ {}", show(&cmd));
        match cmd.status() {
            Ok(s) if s.success() => println!("built {}", dylib_path(release).display()),
            Ok(s) => println!("build failed: cargo exited with {s}"),
            Err(e) => println!("build failed: could not run cargo: {e}"),
        }
        busy.store(false, Ordering::SeqCst);
    });
}

/// Load a built example into this process and run its `scene`.
///
/// The returned `Library` **must outlive every callback the example
/// installed**: those are function pointers into its code, and unloading it
/// while one is armed unmaps the instructions the next frame will call.
///
/// # Safety
///
/// Calls `dlopen` on a file cargo produced from this crate, and hands it a
/// pointer to the live `App`. The fingerprint check below is what makes that
/// defensible; see `kalast::app::abi_fingerprint`.
pub fn load_example(
    release: bool,
    app: &mut crate::app::App,
) -> Result<libloading::Library, String> {
    let path = dylib_path(release);
    if !path.is_file() {
        return Err(format!(
            "{} is not built yet -- press compile first",
            path.display()
        ));
    }

    unsafe {
        let library = libloading::Library::new(&path)
            .map_err(|e| format!("could not load {}: {e}", path.display()))?;

        let abi: libloading::Symbol<extern "C" fn() -> u64> = library
            .get(b"kalast_abi")
            .map_err(|_| format!("{} exports no kalast_abi", path.display()))?;
        let (theirs, ours) = (abi(), crate::app::abi_fingerprint());
        if theirs != ours {
            return Err(format!(
                "{} was built against a different kalast ({theirs:x} against {ours:x}).\n                   rebuild it with the same features as this program -- press compile.",
                path.display()
            ));
        }

        let run: libloading::Symbol<
            unsafe extern "C" fn(*const crate::app::hosted::HostApi),
        > = library
            .get(b"kalast_example")
            .map_err(|_| format!("{} exports no kalast_example", path.display()))?;
        println!("loaded {}", path.display());

        // On this stack for the whole call, which is what `set_host` needs.
        // The example's `main` runs inside it: it builds an `App` of its own,
        // and every call that would own a loop crosses back through here.
        let api = crate::app::hosted::host::api(app as *mut _);
        run(&api as *const _);

        // Dropped by the caller, not here: the symbols are gone from scope but
        // the callbacks the example just installed are not.
        drop(run);
        drop(abi);
        Ok(library)
    }
}

/// A command as it would be typed.
fn show(cmd: &std::process::Command) -> String {
    let mut out = cmd.get_program().to_string_lossy().into_owned();
    for a in cmd.get_args() {
        out.push(' ');
        out.push_str(&a.to_string_lossy());
    }
    out
}

/// Whether the hosted library is built *and* newer than the example.
///
/// "Built" is not enough on its own: loading a library older than the file
/// shown in the panel would run code the panel is not displaying, which is a
/// worse lie than an empty viewport. The wrapper is generic, so one library
/// stands for whichever example was built last -- hence comparing against
/// the file that is open rather than against a target name.
pub fn is_current(release: bool, source: &str) -> bool {
    let modified = |p: &std::path::Path| std::fs::metadata(p).and_then(|m| m.modified()).ok();
    let Some(built) = modified(&dylib_path(release)) else {
        return false;
    };

    if let Some(edited) = modified(std::path::Path::new(source)) {
        if built < edited {
            return false;
        }
    }

    // And against the engine, which is the half the fingerprint cannot always
    // see: a `bool` added to `Shared` fit in existing padding, changed no size
    // and no offset, and a library built before it loaded anyway -- running
    // the *old* `hosted::step` against the new host. A timestamp does not
    // care whether the change was visible.
    !newest_engine_source().is_some_and(|engine| built < engine)
}

/// When the engine was last edited, over `src/` and the manifest.
///
/// A few hundred `stat`s, and only when the editor is deciding whether to
/// rebuild -- not per frame.
fn newest_engine_source() -> Option<std::time::SystemTime> {
    fn walk(dir: &std::path::Path, newest: &mut Option<std::time::SystemTime>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, newest);
            } else if let Ok(t) = entry.metadata().and_then(|m| m.modified()) {
                if newest.is_none_or(|n| t > n) {
                    *newest = Some(t);
                }
            }
        }
    }

    let mut newest = None;
    walk(std::path::Path::new("src"), &mut newest);
    walk(std::path::Path::new("shaders"), &mut newest);
    if let Ok(t) = std::fs::metadata("Cargo.toml").and_then(|m| m.modified()) {
        if newest.is_none_or(|n| t > n) {
            newest = Some(t);
        }
    }
    newest
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The engine half of the staleness check has to actually see the
    /// engine, or a library built before a change to `Shared` loads against
    /// the host that changed it.
    #[test]
    fn the_engine_s_own_sources_count_as_newer() {
        let newest = newest_engine_source().expect("src/ is walked");
        let manifest = std::fs::metadata("Cargo.toml")
            .and_then(|m| m.modified())
            .expect("the manifest is there");
        assert!(
            newest >= manifest,
            "the walk covers at least the files it is asked about"
        );
    }

    /// The wrapper is what makes an example need nothing written in it, so
    /// what it generates is worth pinning: the example included by path, its
    /// own `main` called, and the host installed around that call.
    #[test]
    fn the_wrapper_calls_the_example_s_own_main() {
        let dir = std::env::temp_dir().join("kalast-wrapper-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let example = dir.join("plain.rs");
        // With the `//!` header every example here has: it must survive the
        // copy as a plain comment, because inner docs are only legal first.
        std::fs::write(&example, "//! A plain example.\nfn main() {}\n").unwrap();

        // `write_wrapper` writes under `target/`, relative to the working
        // directory, which for a test is the crate root.
        write_wrapper(&example, ", features = [\"python\"]").unwrap();

        let lib = std::fs::read_to_string(wrapper_dir().join("src/lib.rs")).unwrap();
        assert!(lib.contains("plain.rs"), "it says where it came from");
        assert!(
            !lib.contains("//! A plain example."),
            "the inner doc header is rewritten; it is only legal first in a file"
        );
        assert!(lib.contains("// A plain example."));
        assert!(lib.contains("fn main() {}"), "the example is copied in whole");
        assert!(lib.contains("main();"), "its own main is called");
        assert!(lib.contains("set_host"), "with the host reachable from it");
        assert!(lib.contains("kalast_abi"), "and the ABI check exported");

        let manifest = std::fs::read_to_string(wrapper_dir().join("Cargo.toml")).unwrap();
        assert!(
            manifest.contains("features = [\"python\"]"),
            "the host's features are passed on, or the layouts disagree"
        );
        assert!(manifest.contains("crate-type = [\"cdylib\"]"));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
