[window]
colormap = { name = "inferno", vmax = 400.0, scalar = "temperature" }
export_frames = true
high_dpi = true
# width = 1024
# height = 768

[simulation]
routines = "thermal"
step = 600
duration = 25920000
file = { path = "/Users/gregoireh/Downloads/hakan/forkalast-2.csv", behavior = "loop" }

[simulation.export]
step = 60
duration = 109800
period = 1296000
cooldown_start = 13399200

# 1296000 = 360h
# 12960000 = 3600h
# 25920000 = 3600h * 2
# 109800 = 30.5h
# 439200 = 30.5h * 4
# 549000 = 30.5h * 5
# 1098000 = 30.5h * 10
# 13399200 = 30.5h * 4 + 3600h * 1
# 117079200 = 30.5h * 4 + 3600h * 9

[scene]
sun.position = "file"
camera.position.cartesian = [-1, 0, 0]

[[bodies]]
name = "Apophis"
color = "data"
mesh = { shape.path = "/Users/gregoireh/Downloads/hakan/apophis_new.obj", factor = [1e-3, 1e-3, 1e-3] }
interior.grid1d.linear = { size = 40, a = 2e-2 }
state = "file"
record = { rows = [0], mesh = true, depth = true }

[bodies.material]
albedo = 0.3
emissivity = 0.9
thermal_inertia = 500.0
density = 2100.0
heat_capacity = 600.0
