// Generated by tools/gen_bindings.py -- do not edit by hand.
//
// Regenerate after changing `Config` or `AppConfig`:  python tools/gen_bindings.py
//
// Hand-written accessors with real logic live in `config.rs`, on fields
// marked `:py_custom:`; everything here is mechanical.

use std::{cell::RefCell, rc::Rc};

use pyo3::prelude::*;

use crate::Float;

/// How the surface is coloured and the image encoded.
///
/// `app.simulation.config.shading`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ShadingConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ShadingConfig {
    /// Colour the frame is cleared to, `(r, g, b, a)`.
    ///
    /// Accepts any 4-element sequence: tuple, list or `numpy.array`.
    #[getter]
    fn background(&self) -> [Float; 4] {
        let c = self.config.borrow().shading.background;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_background(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().shading.background = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Draw triangles facing away from the camera.
    ///
    /// Leave it off for closed shape models -- back faces are invisible there, so
    /// culling them is free performance. Measured on the full-resolution
    /// Didymos/Dimorphos meshes: culled against unculled differs in 5 pixels of
    /// 1,040,400, all on silhouette edges.
    ///
    /// Turn it on for geometry that is *not* closed -- open craters, clipped
    /// sections, single-sided surfaces -- where the inside of the shell must be
    /// visible from outside. Note the shading is single-sided regardless: normals
    /// are not flipped for back faces, so an underside is lit as though it were the
    /// top.
    ///
    /// The shadow pass stays unculled either way, so open geometry still casts
    /// correctly from whichever side faces the light.
    #[getter]
    fn render_back_face(&self) -> bool { self.config.borrow().shading.render_back_face }
    #[setter]
    fn set_render_back_face(&mut self, v: bool) { self.config.borrow_mut().shading.render_back_face = v; }
    /// Multisample anti-aliasing for the main render pass: 1 (off), 2, 4 or 8
    /// samples a pixel.
    ///
    /// Geometry edges are the whole point here. Every silhouette in this
    /// renderer is a science measurement -- a limb, a terminator, a body's
    /// apparent diameter -- and at one sample per pixel each of those is
    /// quantised to whole pixels, which both looks wrong beside other tools
    /// and biases any centroid or radius fitted from an exported frame.
    ///
    /// Only the main pass is multisampled. The shadow map, the facet-id and
    /// hemicube passes stay single-sampled on purpose: they carry ids and
    /// depths, not colour, and averaging those across samples would be
    /// meaningless. Exports are unaffected in shape or size -- the pass
    /// resolves into the same single-sample target that was always exported.
    ///
    /// MSAA takes powers of two, and which of them a GPU has is its own: an
    /// Apple M1 Pro has 1, 2 and 4, no 8. A count the GPU lacks falls back to
    /// the largest it has below, and the console says so, naming the GPU and
    /// its counts. Note that `debug_depth_show` only mirrors the main pass's
    /// depth at 1: above that the pass writes its own multisampled depth
    /// buffer instead.
    #[getter]
    fn msaa(&self) -> u32 { self.config.borrow().shading.msaa }
    #[setter]
    fn set_msaa(&mut self, v: u32) { self.config.borrow_mut().shading.msaa = v; }
    /// Flat colour used when `color_mode` is 2, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().shading.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().shading.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// What the fragment shader outputs.
    ///
    /// | | |
    /// |---|---|
    /// | 0 | vertex/instance colour, lit, with shadows (the default) |
    /// | 1 | raw vertex/instance colour, no lighting |
    /// | 2 | the flat `color` |
    /// | 3 | as 0 but with shadows disabled |
    #[getter]
    fn color_mode(&self) -> u32 { self.config.borrow().shading.color_mode }
    #[setter]
    fn set_color_mode(&mut self, v: u32) { self.config.borrow_mut().shading.color_mode = v; }
    /// Which colours come out exactly in the image: the data's and the flat
    /// one (0), or the lit values (1).
    ///
    /// The image is stored through the sRGB curve, which brightens dark
    /// values, and the shader undoes it on one side. 0: on the colours given
    /// to the unlit modes -- a colormap, `color`, a picked facet -- which are
    /// stored as they are; lit shading is stored through the curve, as a
    /// screen shows it, a lit 0.078 as 0.31. 1: on the lit value, which is
    /// stored as it is, so an exported pixel reads I/F = value / 255; the
    /// unlit modes' colours then come out lighter. With MSAA in 1, a pixel
    /// stores the mean of its samples' values, the mean I/F of what it
    /// covers.
    #[getter]
    fn srgb_mode(&self) -> u32 { self.config.borrow().shading.srgb_mode }
    #[setter]
    fn set_srgb_mode(&mut self, v: u32) { self.config.borrow_mut().shading.srgb_mode = v; }
    /// The power law the conversion uses instead of sRGB's own curve, unset
    /// by default.
    ///
    /// 2.2 is how it was done before 7 October, and parted from the curve in
    /// the dark: with `srgb_mode` 1 a lit 0.078 was stored as 0.047, and a
    /// colormap's darkest colours came out darker than they are. Set it only
    /// to reproduce such an image. In the settings with `srgb_mode` 1 only;
    /// with 0 it applies to the unlit modes' colours, set from a script.
    #[getter]
    fn gamma(&self) -> Option<Float> { self.config.borrow().shading.gamma }
    #[setter]
    fn set_gamma(&mut self, v: Option<Float>) { self.config.borrow_mut().shading.gamma = v; }
    /// Draw a large mesh by the parts the camera can see, each only as fine
    /// as the image can show it.
    ///
    /// A flat mesh of 16,384 facets or more is split, on a thread of its own
    /// once loaded, into a tree of patches, each simplified a level at a
    /// time; every frame draws the patches in view and facing the camera, at
    /// the level whose triangles are about `lod_pixels` across. Each patch
    /// hangs a skirt below its edge, so patches drawn at different levels
    /// leave no gap between them, and every triangle drawn shows the colour,
    /// mode and value of an original facet. The shadow maps hold the camera's
    /// own triangles where the camera looks, coarser ones elsewhere
    /// (`shadows.lod_pixels`), and fit to what the camera sees. The facet-id
    /// pass and the per-facet shadow query always see the full mesh. Off,
    /// or until the tree is built, every mesh is drawn whole, every frame.
    #[getter]
    fn lod(&self) -> bool { self.config.borrow().shading.lod }
    #[setter]
    fn set_lod(&mut self, v: bool) { self.config.borrow_mut().shading.lod = v; }
    /// The size, in pixels, a large mesh's triangles are drawn at when `lod`
    /// is on: smaller is finer and slower.
    ///
    /// A patch is drawn at the coarsest level whose triangles' edges come out
    /// at most this many pixels; its full facets when even those are larger.
    /// At 2, about a triangle per pixel: on Mars at Hera's closest, 0.35 %
    /// from every facet drawn, after a pixel's blur; 0.25 % at 1.5, 0.76 %
    /// at 3.
    #[getter]
    fn lod_pixels(&self) -> f32 { self.config.borrow().shading.lod_pixels }
    #[setter]
    fn set_lod_pixels(&mut self, v: f32) { self.config.borrow_mut().shading.lod_pixels = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().shading)
    }
}

/// The Sun as a light: its colour, the ambient floor, the debug cube.
///
/// `app.simulation.config.light`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct LightConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl LightConfig {
    /// Draw a cube at the light's position, so the Sun is visible.
    ///
    /// Size comes from `light_cube_scale`. `debug_light_cube_fit` is on by
    /// default, which is what makes it *visible* rather than merely drawn:
    /// the camera's far plane is fitted to the bodies, and the Sun is well
    /// outside them.
    #[getter]
    fn cube_show(&self) -> bool { self.config.borrow().light.cube_show }
    #[setter]
    fn set_cube_show(&mut self, v: bool) { self.config.borrow_mut().light.cube_show = v; }
    /// Fit the camera's frustum around the light cube too, not just the
    /// bodies.
    ///
    /// What makes `debug_light_cube_show` show something, so it defaults to
    /// **on**: without it the Sun sits past the fitted far plane and is
    /// clipped away, and asking to see the light and being shown nothing is
    /// not a useful default. Nothing happens either way unless the cube is
    /// being drawn.
    ///
    /// Turn it off to keep the frustum fitted to the geometry being studied
    /// while the cube is on -- for a figure where the cube is out of frame
    /// but the framing must not change.
    ///
    /// The **camera** only. The light's own frustum stays fitted to the
    /// bodies, because it is what the shadow map covers: stretching it to the
    /// Sun would spend the whole map on empty space and leave the bodies a
    /// few texels across.
    ///
    /// Costs the depth range: a far plane at the Sun rather than at the
    /// body's edge is a much longer near-to-far span, so depth precision
    /// drops. For looking at where the light is, not for a figure.
    #[getter]
    fn cube_fit(&self) -> bool { self.config.borrow().light.cube_fit }
    #[setter]
    fn set_cube_fit(&mut self, v: bool) { self.config.borrow_mut().light.cube_fit = v; }
    /// Light added to every fragment regardless of shadowing.
    ///
    /// **Zero by default.** A shadowed facet on an airless body receives
    /// essentially nothing, so any ambient term is light the scene does not
    /// have -- and a shadow that is not black is a shadow whose depth cannot
    /// be read off the image. It was 0.002, small enough to look like nothing
    /// and large enough to be a floor under every dark pixel.
    ///
    /// Raise it to see into shadows while navigating; it is the wrong thing
    /// to have on for anything quantitative.
    #[getter]
    fn ambient(&self) -> f32 { self.config.borrow().light.ambient }
    #[setter]
    fn set_ambient(&mut self, v: f32) { self.config.borrow_mut().light.ambient = v; }
    /// Colour of the Sun, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().light.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().light.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Scales the light by one number, `color`'s red, green and blue alike:
    /// a camera's exposure.
    ///
    /// A lit pixel is `exposure * color * albedo * cos(i)`, the ambient term
    /// scaled with it, and the debug cube is drawn as bright. With
    /// `shading.srgb_mode = 1` an exported pixel reads `exposure * I/F * 255`:
    /// 4.5 shows I/F 0 to 0.22 from black to white, and anything brighter
    /// clips at white. The unlit modes' colours -- a colormap's, the flat
    /// `color` -- are data, and keep theirs.
    #[getter]
    fn exposure(&self) -> f32 { self.config.borrow().light.exposure }
    #[setter]
    fn set_exposure(&mut self, v: f32) { self.config.borrow_mut().light.exposure = v; }
    /// The Sun as a point, every shadow hard; on by default.
    ///
    /// Off, the Sun is a disc of `sun_radius` as each point sees it, and a
    /// shadow has the penumbra that disc gives it: as soft as its occluder
    /// is far from what it falls on, a body's own shadows and another's
    /// alike, and where they overlap, what both leave of the disc. A moon's
    /// shadow on a planet is a soft spot, an eclipse comes on gradually --
    /// from Mars, Phobos's shadow is at most 22 % deep and 50 km across --
    /// and a boulder's shadow blurs toward its tip. The disc is
    /// limb-darkened. A penumbra narrower than a shadow-map texel is drawn
    /// as with a point.
    #[getter]
    fn sun_as_point(&self) -> bool { self.config.borrow().light.sun_as_point }
    #[setter]
    fn set_sun_as_point(&mut self, v: bool) { self.config.borrow_mut().light.sun_as_point = v; }
    /// The Sun's radius in the scene's units, with `sun_as_point` off:
    /// 695,700, the Sun's in km. A scene in metres wants 6.957e8.
    #[getter]
    fn sun_radius(&self) -> f32 { self.config.borrow().light.sun_radius }
    #[setter]
    fn set_sun_radius(&mut self, v: f32) { self.config.borrow_mut().light.sun_radius = v; }
    /// Size of the debug light cube, in world units.
    ///
    /// Only drawn when `debug_light_cube_show` is on.
    #[getter]
    fn cube_scale(&self) -> Float { self.config.borrow().light.cube_scale }
    #[setter]
    fn set_cube_scale(&mut self, v: Float) { self.config.borrow_mut().light.cube_scale = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().light)
    }
}

/// The shadow map and its readback.
///
/// `app.simulation.config.shadows`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ShadowsConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ShadowsConfig {
    /// Side length of each square shadow map, in texels.
    ///
    /// One layer per body (one in all with `per_body` off), each
    /// `resolution^2 x 4 bytes`: 67 MB a layer at the default 4096, 268 MB at
    /// 8192, 17 MB at 2048. The default was 8192 until 22 September; every
    /// layer is stored every frame and the main pass waits for it, and at
    /// 4096 the Didymos pair went from 93 to 106 it/s with the per-facet
    /// shadow query unchanged (texel 21 cm on Didymos, 4 cm on Dimorphos,
    /// with a layer per body). See
    /// `notes/2026-09-22_indexed_main_pass_primitive_index.md`.
    ///
    /// It also feeds the automatic bias, which is expressed relative to one texel,
    /// so changing it changes the shadow bias with it.
    #[getter]
    fn resolution(&self) -> u32 { self.config.borrow().shadows.resolution }
    #[setter]
    fn set_resolution(&mut self, v: u32) { self.config.borrow_mut().shadows.resolution = v; }
    /// Smoothing of the shadows' edges, the percentage-closer-filtering
    /// kernel's *radius* in shadow-map texels: 0 is the hardware's single 2x2
    /// comparison, N a `(2N+1)^2` grid of them averaged.
    ///
    /// The grid lies on the ground around each point, a texel apart along it,
    /// and blurs a shadow's edge as wide whatever the Sun's height, without
    /// moving it. It darkened lit ground as if by ambient occlusion before
    /// 9 October -- on Dimorphos from 68 m, 45 % of the lit pixels by more than
    /// 5 % at 16, 8 % at 4 -- its taps then a square in the map's view, which
    /// at a low Sun reached far along the ground. See
    /// `notes/2026-10-09_pcf_on_the_ground/`.
    ///
    /// It costs where a shadow's edge is in reach -- elsewhere five taps agree
    /// and the rest are skipped -- and grows with the image's pixels: on
    /// Dimorphos at 3234 x 1774, 1.4 ms a frame at 2 and 4.3 at 4, on an M1
    /// Pro. With the map's texels finer than the image's pixels (16384 up
    /// close) there are no stairs to smooth.
    #[getter]
    fn pcf(&self) -> u32 { self.config.borrow().shadows.pcf }
    #[setter]
    fn set_pcf(&mut self, v: u32) { self.config.borrow_mut().shadows.pcf = v; }
    /// Push the sample along the surface normal before the shadow lookup, in
    /// world units. `None` fits it per frame from the layer's own texel size.
    ///
    /// One texel diagonal whatever the PCF radius. The far taps of a kernel
    /// are the shader's per-tap receiver-plane term's business, not this
    /// offset's: lifting the lookup further off the surface moved the shadow
    /// instead of blurring it.
    ///
    /// Pinning it is now worse than leaving it automatic: with per-body shadow
    /// layers a pinned value replaces the fitted one on *every* layer, and
    /// those differ by the ratio of the bodies' sizes -- 403x between Mars and
    /// Deimos in the same scene.
    #[getter]
    fn normal_offset_scale(&self) -> Option<f32> { self.config.borrow().shadows.normal_offset_scale }
    #[setter]
    fn set_normal_offset_scale(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.normal_offset_scale = v; }
    /// Slope-dependent term of the depth-comparison bias. `None` fits it per
    /// frame. Combined in the shader as
    /// `max(shadow_bias_scale * k, shadow_bias_minimum)`.
    ///
    /// See `shadow_normal_offset_scale` for why pinning is discouraged.
    #[getter]
    fn bias_scale(&self) -> Option<f32> { self.config.borrow().shadows.bias_scale }
    #[setter]
    fn set_bias_scale(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.bias_scale = v; }
    /// Floor on the depth-comparison bias, for surfaces facing the light
    /// head-on. `None` fits it per frame.
    ///
    /// Measured to be the *ineffective* knob for the crater-floor PCF leak --
    /// auto, 1e-4 and 1e-3 all gave identical results, while the normal offset
    /// moved it 9x. Reach for that one first.
    #[getter]
    fn bias_minimum(&self) -> Option<f32> { self.config.borrow().shadows.bias_minimum }
    #[setter]
    fn set_bias_minimum(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.bias_minimum = v; }
    /// Read the shadow map back per facet: computes solar occlusion for every
    /// body each frame, readable from `after_render` via
    /// `Simulation::facet_shadow`.
    ///
    /// Off by default because it is not free: the query costs ~1.6 ms per
    /// body at 100k facets and ~7.3 ms at 3.1M, dominated by the blocking
    /// readback. Turn it on for thermophysical or radiance work; leave it off
    /// when you only want images.
    /// Compute per-facet solar occlusion for every body, every frame.
    ///
    /// Read it back with `sim.facet_shadow(body)` from `after_render`. Leave it off
    /// unless something consumes it: it is a compute pass and a readback per frame.
    #[getter]
    fn access_shadow_map(&self) -> bool { self.config.borrow().shadows.access_shadow_map }
    #[setter]
    fn set_access_shadow_map(&mut self, v: bool) { self.config.borrow_mut().shadows.access_shadow_map = v; }
    /// Fit a shadow map per body instead of one fitted to the whole scene.
    ///
    /// On by default, because one shared map is fitted to the scene's extent
    /// and a small body beside a large one then gets almost no texels -- 6 km
    /// Deimos next to 3,396 km Mars is the case that forced this. Each layer
    /// is aimed at its own body and sized to it, while its depth range still
    /// spans the scene, so mutual shadowing is unaffected: anything between
    /// the Sun and a body still casts into that body's layer.
    ///
    /// Costs one shadow pass per body. Turn it off to get the old single
    /// scene-fitted map back, which is only worth doing to reproduce older
    /// output or when every body is a similar size.
    #[getter]
    fn per_body(&self) -> bool { self.config.borrow().shadows.per_body }
    #[setter]
    fn set_per_body(&mut self, v: bool) { self.config.borrow_mut().shadows.per_body = v; }
    /// A finer shadow layer over where the camera looks closest, for a body
    /// seen up close.
    ///
    /// A body's layer is fitted to all the camera sees of it, so a close view
    /// reaching far across the body coarsens its texels: Dimorphos from 37 m
    /// had them at 3 cm, its boulders' penumbrae 4 cm wide -- hard-edged
    /// stairs, and too narrow for the Sun's disc to soften
    /// (`light.sun_as_point`). The near layer covers the patches nearest the
    /// camera, as far out as keeps its texels half the image's pixels there,
    /// and a point inside it is looked up there. Only while the body's own
    /// layer is twice coarser than that, with a perspective camera, layers
    /// per body, the body drawn by its cut (`shading.lod`) and without a
    /// horizon map, and up to eight layers in all; then it costs a layer's
    /// memory and a shadow pass.
    #[getter]
    fn near_layer(&self) -> bool { self.config.borrow().shadows.near_layer }
    #[setter]
    fn set_near_layer(&mut self, v: bool) { self.config.borrow_mut().shadows.near_layer = v; }
    /// With the Sun a disc, a second depth layer under each shadow layer: the
    /// nearest surface behind what the Sun sees first. Nothing with the Sun a
    /// point, whatever it is set to.
    ///
    /// A map holds what the Sun sees first, and a rock in the shadow of a
    /// bigger one is not in it: where a penumbra is walked through such
    /// relief, the disc comes through. Near Dimorphos's terminator, with
    /// texels fine enough to walk its penumbrae (16384), it lit slivers in
    /// the dark, 0.05-0.17 of the disc where rays reach none, which this
    /// takes to 0; on Dimorphos from 68 m, it takes the thin gaps of light
    /// left from 163 pixels to 101. It costs a second shadow pass and a slice
    /// per layer, the pass slower than the first -- 2 to 7 ms a frame on
    /// Dimorphos up close -- for little where penumbrae are narrower than six
    /// texels and drawn hard, as at the default resolution.
    #[getter]
    fn second_depth(&self) -> bool { self.config.borrow().shadows.second_depth }
    #[setter]
    fn set_second_depth(&mut self, v: bool) { self.config.borrow_mut().shadows.second_depth = v; }
    /// Keep each body's shadow layer from frame to frame, drawn again only
    /// when the Sun has moved past `cache_degrees` in the body's own frame,
    /// another body has moved about it, or the scene or the shadows' settings
    /// changed.
    ///
    /// A layer kept turns with its body, so its own shadows stay on it; a
    /// camera that moves, or a simulation paused, then costs no shadow pass at
    /// all. Each layer is fitted to its whole body rather than to what the
    /// camera sees of it, and there is no near layer (`near_layer`), so a view
    /// up close has coarser texels than without. The per-facet shadows the
    /// thermophysical model reads are the kept layers too. Off by default:
    /// the layers are drawn every frame, as fine as the view allows.
    #[getter]
    fn cache(&self) -> bool { self.config.borrow().shadows.cache }
    #[setter]
    fn set_cache(&mut self, v: bool) { self.config.borrow_mut().shadows.cache = v; }
    /// How far, in degrees, the Sun may move in a body's own frame, or another
    /// body about it, before a kept layer is drawn again (`cache`). 0: only
    /// when nothing has moved at all, the shadows as exact as without the
    /// cache. Larger keeps layers through a running simulation -- Didymos
    /// turns 0.044 deg a second of simulated time -- each shadow up to that
    /// far behind the Sun.
    #[getter]
    fn cache_degrees(&self) -> f32 { self.config.borrow().shadows.cache_degrees }
    #[setter]
    fn set_cache_degrees(&mut self, v: f32) { self.config.borrow_mut().shadows.cache_degrees = v; }
    /// Cascaded shadow maps, for a quick look: this many layers over slices
    /// of the camera's view, the nearer finer, and one over the whole scene,
    /// in place of a layer per body. 0, the default: a layer per body.
    ///
    /// As games draw the Sun's shadows: the cost is the cascades' whatever
    /// the bodies, and the shadows are sharp where the camera looks closest.
    /// Less exact than a layer per body: a body's own shadows and another's
    /// share each cascade -- with the Sun a disc a penumbra can come through
    /// where they meet -- there is no near layer, no horizon map and no cache,
    /// and the edges between cascades can show. The per-facet shadows the
    /// thermophysical model reads are each facet's cascade's, so they move
    /// with the camera.
    #[getter]
    fn cascades(&self) -> u32 { self.config.borrow().shadows.cascades }
    #[setter]
    fn set_cascades(&mut self, v: u32) { self.config.borrow_mut().shadows.cascades = v; }
    /// The size, in shadow-map texels, a large mesh's triangles are drawn at
    /// in the shadow maps when `shading.lod` is on, outside the camera's
    /// view.
    ///
    /// A shadow cast into the view needs its occluder's outline, not its
    /// facets: 2 keeps the outline to a texel. With `access_shadow_map`, or a
    /// per-facet shadow query pending, the maps take the full facets and the
    /// whole body.
    #[getter]
    fn lod_texels(&self) -> f32 { self.config.borrow().shadows.lod_texels }
    #[setter]
    fn set_lod_texels(&mut self, v: f32) { self.config.borrow_mut().shadows.lod_texels = v; }
    /// The size, in the camera's pixels, a large mesh's triangles are drawn
    /// at in the shadow maps when `shading.lod` is on, outside the camera's
    /// view.
    ///
    /// Where the camera looks, the maps hold the very triangles it draws: a
    /// coarser caster over a finer receiver shadows it wherever the coarse
    /// surface passes above the fine one, across every crater floor. Outside
    /// it, a caster only casts into the view, and coarser does: whichever of
    /// this and `lod_texels` is coarser is used.
    #[getter]
    fn lod_pixels(&self) -> f32 { self.config.borrow().shadows.lod_pixels }
    #[setter]
    fn set_lod_pixels(&mut self, v: f32) { self.config.borrow_mut().shadows.lod_pixels = v; }
    /// Trace the shadows the thermophysical model reads with rays, on a GPU
    /// that has ray queries: each facet's corners and centre against every
    /// body's full-resolution mesh, the Sun's disc sampled by
    /// `ray_samples` rays. Off by default; without ray queries, the shadow
    /// maps answer as before.
    ///
    /// No texel, filter or bias: a shadow is where the mesh is, a penumbra
    /// what the rays see of the limb-darkened disc. Vulkan on Windows and
    /// Linux, Metal on macOS 15 and later -- on an Apple M1 or M2 the
    /// traversal is the driver's, slower than on hardware that has it.
    #[getter]
    fn rays(&self) -> bool { self.config.borrow().shadows.rays }
    #[setter]
    fn set_rays(&mut self, v: bool) { self.config.borrow_mut().shadows.rays = v; }
    /// The rays each point traces across the Sun's disc, with `rays` on and
    /// `light.sun_as_point` off: each carries the same share of the
    /// limb-darkened disc's light, so a penumbra is resolved to about
    /// 1/`ray_samples`. A point Sun takes one.
    #[getter]
    fn ray_samples(&self) -> u32 { self.config.borrow().shadows.ray_samples }
    #[setter]
    fn set_ray_samples(&mut self, v: u32) { self.config.borrow_mut().shadows.ray_samples = v; }
    /// The rays a point tries first across the disc, with `rays` on: where
    /// they all agree the point is wholly lit or wholly hidden and the rest
    /// of `ray_samples` are not traced. Nearly every point is, so a step
    /// costs about this many rays a point whatever `ray_samples` is.
    ///
    /// A part of the disc smaller than about 1/`ray_probe` of it, hidden or
    /// seen with all of these rays missing it, is missed: the edge of a
    /// penumbra by a sliver. 0 traces all of `ray_samples` everywhere,
    /// exact to them.
    #[getter]
    fn ray_probe(&self) -> u32 { self.config.borrow().shadows.ray_probe }
    #[setter]
    fn set_ray_probe(&mut self, v: u32) { self.config.borrow_mut().shadows.ray_probe = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().shadows)
    }
}

/// Facet edges drawn over or instead of the surface.
///
/// `app.simulation.config.wireframe`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct WireframeConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl WireframeConfig {
    /// the barycentrics are meaningless and the CPU side warns once.
    #[getter]
    fn mode(&self) -> u32 { self.config.borrow().wireframe.mode }
    #[setter]
    fn set_mode(&mut self, v: u32) { self.config.borrow_mut().wireframe.mode = v; }
    /// Wireframe colour, `(r, g, b, a)`; alpha is dropped. Very dark grey
    /// rather than black by default.
    ///
    /// Mode 2 blends by edge coverage and is antialiased; mode 1 thresholds instead,
    /// because the pipeline blend state is REPLACE and a fractional alpha would be
    /// ignored.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().wireframe.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().wireframe.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Wireframe half-width in screen pixels.
    #[getter]
    fn width(&self) -> f32 { self.config.borrow().wireframe.width }
    #[setter]
    fn set_width(&mut self, v: f32) { self.config.borrow_mut().wireframe.width = v; }
    /// Fade the wireframe out as a body recedes far enough that its facets
    /// stop being resolvable. **Off by default.**
    ///
    /// Past about a pixel per facet the three edges cover the whole triangle,
    /// so the mesh reads as a sheet of wireframe colour -- a shadowed body at
    /// distance comes out grey rather than black, which is the wireframe
    /// overwriting the shading rather than drawing the mesh. This fades it out
    /// between 4 px and 1 px facets instead.
    ///
    /// Distance only: the measure is the facet's *largest* screen height, so
    /// tilt does not trigger it and the limb of a sphere keeps its wireframe.
    ///
    /// Only applies to `wireframe_mode = 2`, where there is a shaded surface
    /// underneath to fade into. Mode 1 is wireframe alone and would simply
    /// vanish.
    #[getter]
    fn fade(&self) -> bool { self.config.borrow().wireframe.fade }
    #[setter]
    fn set_fade(&mut self, v: bool) { self.config.borrow_mut().wireframe.fade = v; }
    /// Smooth the wireframe's edges, or draw them hard.
    ///
    /// Its own antialiasing, whatever `shading.msaa` is: the mesh's shader
    /// draws the lines and blends each edge in over a pixel. Off, a pixel is
    /// wire or surface. Mode 1 is always hard, having nothing to blend into.
    #[getter]
    fn antialias(&self) -> bool { self.config.borrow().wireframe.antialias }
    #[setter]
    fn set_antialias(&mut self, v: bool) { self.config.borrow_mut().wireframe.antialias = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().wireframe)
    }
}

/// The picked facet and the facet labels.
///
/// `app.simulation.config.selection`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct SelectionConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl SelectionConfig {
    /// 0 shaded only, 1 wireframe only, 2 wireframe over the shaded mesh.
    ///
    /// Barycentric edge detection in the main fragment shader, so the overlay
    /// cannot z-fight. Needs a flattened mesh -- indexed meshes share vertices, so
    /// Draw each facet's index at its centre.
    ///
    /// For working out *which* facet a number in a data product refers to,
    /// without counting round a mesh by hand. Off by default, and capped by
    /// `facet_labels_max`: a label per facet is a text draw per facet, and a
    /// shape model has millions of them.
    ///
    /// Only facets turned towards the camera are labelled. The text has no
    /// depth test -- it is drawn over the frame -- so labelling the far side
    /// of a body would print numbers on top of the surface hiding them. On a
    /// concave shape, a facet behind another that faces the same way can
    /// still show through.
    #[getter]
    fn labels(&self) -> bool { self.config.borrow().selection.labels }
    #[setter]
    fn set_labels(&mut self, v: bool) { self.config.borrow_mut().selection.labels = v; }
    /// Most facets to label before giving up, per body.
    ///
    /// A guard rather than a preference: turning labels on with a 3.1M-facet
    /// body would queue three million text draws and stop the frame dead.
    #[getter]
    fn labels_max(&self) -> u32 { self.config.borrow().selection.labels_max }
    #[setter]
    fn set_labels_max(&mut self, v: u32) { self.config.borrow_mut().selection.labels_max = v; }
    /// Size of a facet label, in pixels.
    #[getter]
    fn label_size(&self) -> f32 { self.config.borrow().selection.label_size }
    #[setter]
    fn set_label_size(&mut self, v: f32) { self.config.borrow_mut().selection.label_size = v; }
    /// Colour of a facet label, `(r, g, b, a)`.
    #[getter]
    fn label_color(&self) -> [f32; 4] { self.config.borrow().selection.label_color }
    #[setter]
    fn set_label_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().selection.label_color = v; }
    /// Colour a facet takes when it is selected, `(r, g, b, a)`.
    ///
    /// Selecting writes this onto the facet's own vertices and marks them
    /// colour-mode 1, which the shader honours for that facet alone -- so a
    /// picked facet is unlit and this colour while the rest of the body keeps
    /// its shading. Deselecting puts back what was there.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().selection.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().selection.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().selection)
    }
}

/// Colouring facets from per-facet values.
///
/// `app.simulation.config.data`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct DataConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl DataConfig {
    /// Range the colormap spans, or `None` to fit the loaded values each
    /// frame.
    ///
    /// Automatic is the sane default for exploring, but pin it for anything
    /// comparative: an auto range silently rescales between frames, so two
    /// images of the same scene are not on the same colour scale and the
    /// difference between them reads as physics rather than as bookkeeping.
    #[getter]
    fn value_min(&self) -> Option<f32> { self.config.borrow().data.value_min }
    #[setter]
    fn set_value_min(&mut self, v: Option<f32>) { self.config.borrow_mut().data.value_min = v; }
    #[getter]
    fn value_max(&self) -> Option<f32> { self.config.borrow().data.value_max }
    #[setter]
    fn set_value_max(&mut self, v: Option<f32>) { self.config.borrow_mut().data.value_max = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().data)
    }
}

/// The colour scale drawn for `data`.
///
/// `app.simulation.config.colorbar`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ColorbarConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ColorbarConfig {
    #[getter]
    fn enabled(&self) -> bool { self.config.borrow().colorbar.enabled }
    #[setter]
    fn set_enabled(&mut self, v: bool) { self.config.borrow_mut().colorbar.enabled = v; }
    #[getter]
    fn anchor(&self) -> String { self.config.borrow().colorbar.anchor.name().to_string() }
    #[setter]
    fn set_anchor(&mut self, v: &str) -> PyResult<()> {
        let a = crate::app::config::HudAnchor::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown anchor {v:?}: expected one of top-left, top-center, \
                 top-right, middle-left, middle-center, middle-right, \
                 bottom-left, bottom-center, bottom-right"
            ))
        })?;
        self.config.borrow_mut().colorbar.anchor = a;
        Ok(())
    }
    /// Inset from the anchor, pixels.
    #[getter]
    fn x(&self) -> f32 { self.config.borrow().colorbar.x }
    #[setter]
    fn set_x(&mut self, v: f32) { self.config.borrow_mut().colorbar.x = v; }
    #[getter]
    fn y(&self) -> f32 { self.config.borrow().colorbar.y }
    #[setter]
    fn set_y(&mut self, v: f32) { self.config.borrow_mut().colorbar.y = v; }
    /// Long and short axis of the bar, pixels. Its edges drag in the
    /// viewport too.
    #[getter]
    fn length(&self) -> f32 { self.config.borrow().colorbar.length }
    #[setter]
    fn set_length(&mut self, v: f32) { self.config.borrow_mut().colorbar.length = v; }
    #[getter]
    fn thickness(&self) -> f32 { self.config.borrow().colorbar.thickness }
    #[setter]
    fn set_thickness(&mut self, v: f32) { self.config.borrow_mut().colorbar.thickness = v; }
    /// Length of a tick mark, pixels, across the bar's edge -- half inside,
    /// half out -- the numbers standing past it.
    #[getter]
    fn tick_size(&self) -> f32 { self.config.borrow().colorbar.tick_size }
    #[setter]
    fn set_tick_size(&mut self, v: f32) { self.config.borrow_mut().colorbar.tick_size = v; }
    /// `None` infers from the anchor.
    #[getter]
    fn vertical(&self) -> Option<bool> { self.config.borrow().colorbar.vertical }
    #[setter]
    fn set_vertical(&mut self, v: Option<bool>) { self.config.borrow_mut().colorbar.vertical = v; }
    /// Caption, e.g. `"Surface temperature (K)"`.
    #[getter]
    fn label(&self) -> String { self.config.borrow().colorbar.label.clone() }
    #[setter]
    fn set_label(&mut self, v: &str) { self.config.borrow_mut().colorbar.label = v.to_string(); }
    /// Roughly how many numbered ticks; rounded to a readable step as the axes
    /// are.
    #[getter]
    fn ticks(&self) -> usize { self.config.borrow().colorbar.ticks }
    #[setter]
    fn set_ticks(&mut self, v: usize) { self.config.borrow_mut().colorbar.ticks = v; }
    #[getter]
    fn text_size(&self) -> f32 { self.config.borrow().colorbar.text_size }
    #[setter]
    fn set_text_size(&mut self, v: f32) { self.config.borrow_mut().colorbar.text_size = v; }
    #[getter]
    fn text_color(&self) -> [f32; 4] { self.config.borrow().colorbar.text_color }
    #[setter]
    fn set_text_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().colorbar.text_color = v; }
    /// Outline drawn around the strip, in the text's colour, so it reads as a
    /// scale rather than as part of the scene when it sits over a dark body.
    #[getter]
    fn border(&self) -> bool { self.config.borrow().colorbar.border }
    #[setter]
    fn set_border(&mut self, v: bool) { self.config.borrow_mut().colorbar.border = v; }
    /// Mark the lowest and highest value the bodies carry where they fall on
    /// the scale -- at its end, when a pinned range leaves them outside it --
    /// and name them, on the side away from the tick numbers: above a
    /// horizontal bar, left of a vertical one. The data map's only
    /// (`shading.color_mode` 1).
    #[getter]
    fn min_max(&self) -> bool { self.config.borrow().colorbar.min_max }
    #[setter]
    fn set_min_max(&mut self, v: bool) { self.config.borrow_mut().colorbar.min_max = v; }
    /// How `min_max` writes the two values, as a Python format spec: `.0f`
    /// whole numbers, `.3f` three decimals, `.2e` in powers of ten, `d` an
    /// integer. Anything else reads as `.0f`.
    #[getter]
    fn min_max_format(&self) -> String { self.config.borrow().colorbar.min_max_format.clone() }
    #[setter]
    fn set_min_max_format(&mut self, v: &str) { self.config.borrow_mut().colorbar.min_max_format = v.to_string(); }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().colorbar)
    }
}

/// Reference axes, tick labels and the navigation gizmo.
///
/// `app.simulation.config.axes`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct AxesConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl AxesConfig {
    /// Reference axes drawn around the scene.
    ///
    /// `"off"`, `"box"` (MATLAB), `"panes"` (matplotlib), `"gizmo"` (three
    /// labelled arrows at the origin), `"blender"` (ground grid, Z line and
    /// gizmo). A rendered body alone carries no scale or orientation; these
    /// supply both.
    #[getter]
    fn style(&self) -> String { self.config.borrow().axes.style.name().to_string() }
    #[setter]
    fn set_style(&mut self, v: &str) -> PyResult<()> {
        let s = crate::app::axes::AxesStyle::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown axes style {v:?}: expected off, box, panes, gizmo or blender"
            ))
        })?;
        self.config.borrow_mut().axes.style = s;
        Ok(())
    }
    /// Colour of the axis lines and grid.
    #[getter]
    fn color(&self) -> [f32; 3] { self.config.borrow().axes.color }
    #[setter]
    fn set_color(&mut self, v: [f32; 3]) { self.config.borrow_mut().axes.color = v; }
    /// Roughly how many ticks per axis. The step is rounded to 1, 2 or 5
    /// times a power of ten first, so the count lands near this rather than
    /// on it -- a figure with ticks at 0.0347 is unreadable.
    #[getter]
    fn ticks(&self) -> usize { self.config.borrow().axes.ticks }
    #[setter]
    fn set_ticks(&mut self, v: usize) { self.config.borrow_mut().axes.ticks = v; }
    /// Appended to every tick label, e.g. `" km"`.
    ///
    /// The renderer knows the mesh is 0.437 across but not whether that is
    /// metres or kilometres, so the unit has to come from the script.
    #[getter]
    fn unit(&self) -> String { self.config.borrow().axes.unit.clone() }
    #[setter]
    fn set_unit(&mut self, v: &str) { self.config.borrow_mut().axes.unit = v.to_string(); }
    /// Tick label size in pixels, and their colour.
    #[getter]
    fn label_size(&self) -> f32 { self.config.borrow().axes.label_size }
    #[setter]
    fn set_label_size(&mut self, v: f32) { self.config.borrow_mut().axes.label_size = v; }
    #[getter]
    fn label_color(&self) -> [f32; 4] { self.config.borrow().axes.label_color }
    #[setter]
    fn set_label_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().axes.label_color = v; }
    /// Which corner the navigation gizmo sits in. Any of the nine HUD
    /// anchors, so it can be moved out of the way of a colour bar or a HUD.
    ///
    /// Drawn by the `"gizmo"` and `"blender"` axes styles and by no other.
    #[getter]
    fn gizmo_anchor(&self) -> String { self.config.borrow().axes.gizmo_anchor.name().to_string() }
    #[setter]
    fn set_gizmo_anchor(&mut self, v: &str) -> PyResult<()> {
        let a = crate::app::config::HudAnchor::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown anchor {v:?}: expected one of top-left, top-center, \
                 top-right, middle-left, middle-center, middle-right, \
                 bottom-left, bottom-center, bottom-right"
            ))
        })?;
        self.config.borrow_mut().axes.gizmo_anchor = a;
        Ok(())
    }
    /// Half the widget's width, in pixels: a ball centre never sits further
    /// than this from the middle.
    ///
    /// The gizmo's only size knob. Letter height follows it
    /// ([`crate::app::gizmo::label_size`]), the margin to the image edge is
    /// fixed at 20 px, and the letters are black -- each of those was settable
    /// once and none of them was worth setting: a letter is sized and coloured
    /// by the ball it sits on, so the pair could only ever agree or disagree.
    #[getter]
    fn gizmo_size(&self) -> f32 { self.config.borrow().axes.gizmo_size }
    #[setter]
    fn set_gizmo_size(&mut self, v: f32) { self.config.borrow_mut().axes.gizmo_size = v; }
    /// Smooth the axes' lines, or draw them hard.
    ///
    /// Their own antialiasing, whatever `shading.msaa` is: each segment is a
    /// thin strip whose shader blends its edges in over a pixel, or cuts them.
    /// Before, the lines were one pixel wide and smoothed by the mesh's MSAA
    /// alone. The ground grid has its own smoothing, and the gizmo's.
    #[getter]
    fn antialias(&self) -> bool { self.config.borrow().axes.antialias }
    #[setter]
    fn set_antialias(&mut self, v: bool) { self.config.borrow_mut().axes.antialias = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().axes)
    }
}

/// The shaded ground grid of the `blender` axes style.
///
/// `app.simulation.config.grid`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct GridConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl GridConfig {
    /// Shade the `"blender"` style's ground grid instead of drawing it as
    /// line segments. On by default; `False` restores the segments.
    ///
    /// The segments end at the scene bounds, sit at one spacing, and are one
    /// pixel wide because WebGPU has no line width. This computes the grid
    /// per pixel instead: it has no edge, it crossfades between decades as
    /// you zoom -- which is what lets one grid serve a unit cube and a body
    /// 1e4 km away -- and its lines antialias themselves.
    #[getter]
    fn enabled(&self) -> bool { self.config.borrow().grid.enabled }
    #[setter]
    fn set_enabled(&mut self, v: bool) { self.config.borrow_mut().grid.enabled = v; }
    /// Width of a grid line, in pixels.
    #[getter]
    fn width(&self) -> f32 { self.config.borrow().grid.width }
    #[setter]
    fn set_width(&mut self, v: f32) { self.config.borrow_mut().grid.width = v; }
    /// Cells between thick lines, and the factor between the levels the
    /// crossfade steps through -- the same number seen from two sides.
    #[getter]
    fn major(&self) -> u32 { self.config.borrow().grid.major }
    #[setter]
    fn set_major(&mut self, v: u32) { self.config.borrow_mut().grid.major = v; }
    /// Colour of the ordinary lines, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [f32; 4] { self.config.borrow().grid.color }
    #[setter]
    fn set_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.color = v; }
    /// Colour of every `grid_major`-th line.
    #[getter]
    fn major_color(&self) -> [f32; 4] { self.config.borrow().grid.major_color }
    #[setter]
    fn set_major_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.major_color = v; }
    /// The axis lines, drawn over the grid so the origin reads without
    /// hunting for it. Two of the three are in the grid's plane and get
    /// drawn; which two depends on which plane that is.
    #[getter]
    fn axis_x_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_x_color }
    #[setter]
    fn set_axis_x_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_x_color = v; }
    #[getter]
    fn axis_y_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_y_color }
    #[setter]
    fn set_axis_y_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_y_color = v; }
    #[getter]
    fn axis_z_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_z_color }
    #[setter]
    fn set_axis_z_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_z_color = v; }
    /// Fade the grid out between these grazing factors: `0.0` is looking
    /// straight down at the ground plane and `1.0` is looking along it.
    /// Without it the horizon is a hard line of aliasing.
    ///
    /// On the angle rather than the distance because the plane is infinite:
    /// what bounds it on screen is the horizon, not the far plane, so a
    /// distance fade never reaches its ramp.
    #[getter]
    fn fade_near(&self) -> f32 { self.config.borrow().grid.fade_near }
    #[setter]
    fn set_fade_near(&mut self, v: f32) { self.config.borrow_mut().grid.fade_near = v; }
    #[getter]
    fn fade_far(&self) -> f32 { self.config.borrow().grid.fade_far }
    #[setter]
    fn set_fade_far(&mut self, v: f32) { self.config.borrow_mut().grid.fade_far = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().grid)
    }
}

/// The text overlays.
///
/// `app.simulation.config.hud`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct HudConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl HudConfig {
    /// Font for the HUD: a **name** or a **path**, or empty for the built-in
    /// DejaVu Sans.
    ///
    /// `"Arial"`, `"arial"`, `"Times New Roman"` and
    /// `"/Library/Fonts/Arial.ttf"` all work. Anything that exists on disk is
    /// treated as a path; anything else is looked up by name in the
    /// platform's font directories.
    ///
    /// **Matching is on the filename, not the family name inside the font.**
    /// Reading real family names needs a font-database dependency, which an
    /// overlay does not justify; filenames cover the names people type. A
    /// family whose file is named differently -- "Helvetica Neue" living in
    /// `HelveticaNeue.ttc` -- resolves, since punctuation and case are
    /// ignored, but one named nothing like its family will not.
    ///
    /// One font for all HUDs: each additional font needs its own glyph cache
    /// and draw, and per-HUD fonts are not worth that for an overlay. Per-HUD
    /// *size* is free by comparison and lives on `Hud::size`.
    ///
    /// A path that cannot be read or parsed warns once and falls back to the
    /// built-in font, rather than leaving the run with no HUD at all.
    ///
    /// Startup only: the glyph cache is built with the window.
    #[getter]
    fn font(&self) -> String { self.config.borrow().hud.font.clone() }
    #[setter]
    fn set_font(&mut self, v: &str) { self.config.borrow_mut().hud.font = v.to_string(); }
    /// Smooth the text drawn over the image, or draw it hard: the HUDs and
    /// every label -- the axes', the facets', the colour bar's, the gizmo's.
    ///
    /// Text has its own antialiasing, from the font, which `shading.msaa`
    /// never touches. Off, a pixel is text or not: the text is drawn on a
    /// layer of its own and copied over wherever it covers half the pixel,
    /// opaque.
    #[getter]
    fn antialias(&self) -> bool { self.config.borrow().hud.antialias }
    #[setter]
    fn set_antialias(&mut self, v: bool) { self.config.borrow_mut().hud.antialias = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().hud)
    }
}

/// Frame export.
///
/// `app.simulation.config.export`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ExportConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ExportConfig {
    /// Encode and write each exported frame on the render thread instead of a
    /// worker pool.
    ///
    /// Slower, but the file is on disk before the frame returns -- which is what a
    /// script needs if it exports and then reads the file immediately.
    #[getter]
    fn sync(&self) -> bool { self.config.borrow().export.sync }
    #[setter]
    fn set_sync(&mut self, v: bool) { self.config.borrow_mut().export.sync = v; }
    /// How many frames may be waiting to be encoded before the render loop blocks.
    ///
    /// Unbounded, this reached 30 GB RSS growing at ~2 GB/s while only ~5.6 frames
    /// per second actually reached disk, and the loop still claimed 626 it/s --
    /// measuring queue growth rather than work done.
    #[getter]
    fn max_queued(&self) -> u32 { self.config.borrow().export.max_queued }
    #[setter]
    fn set_max_queued(&mut self, v: u32) { self.config.borrow_mut().export.max_queued = v; }
    /// Directory exported frames are written to, as `{export_dir}/{N:06}.png`.
    ///
    /// **Redirect this for any test or benchmark run.** The default is shared, so a
    /// benchmark left at it writes into whatever a real run is using, and two
    /// exporters pointed at one directory race on the startup index scan as well as
    /// on cleanup.
    #[getter]
    fn dir(&self) -> String { self.config.borrow().export.dir.clone() }
    #[setter]
    fn set_dir(&mut self, v: &str) { self.config.borrow_mut().export.dir = v.to_string(); }
    /// Burn the HUD text into exported frames as well as drawing it on screen.
    ///
    /// On by default: an exported frame is what the window shows, the run
    /// state a HUD writes -- a date, an iteration -- included. On, it costs
    /// one extra text pass, on exported frames only. Off for a data product
    /// with a HUD on screen: the HUD is drawn onto the swapchain after the
    /// scene has been copied out, so the export carries the render alone.
    #[getter]
    fn hud(&self) -> bool { self.config.borrow().export.hud }
    #[setter]
    fn set_hud(&mut self, v: bool) { self.config.borrow_mut().export.hud = v; }
    /// Keep the axes -- grid, box or panes, gizmo, and their labels -- in
    /// exported frames as well as on screen.
    ///
    /// On by default, as `hud` is: an exported frame is what the window shows.
    /// Off, frames that are exported draw the axes in a second pass after the
    /// copy, so the window keeps them and the export has the scene alone; other
    /// frames are drawn as before.
    #[getter]
    fn axes(&self) -> bool { self.config.borrow().export.axes }
    #[setter]
    fn set_axes(&mut self, v: bool) { self.config.borrow_mut().export.axes = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().export)
    }
}

/// Mouse and keyboard sensitivities.
///
/// `app.simulation.config.controls`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ControlsConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ControlsConfig {
    /// Multiplier for WASD movement speed.
    #[getter]
    fn sensitivity_move(&self) -> Float { self.config.borrow().controls.sensitivity_move }
    #[setter]
    fn set_sensitivity_move(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_move = v; }
    /// Multiplier for mouse-look speed in WASD mode.
    #[getter]
    fn sensitivity_look(&self) -> Float { self.config.borrow().controls.sensitivity_look }
    #[setter]
    fn set_sensitivity_look(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_look = v; }
    /// Multiplier for arcball orbit speed.
    #[getter]
    fn sensitivity_rotate(&self) -> Float { self.config.borrow().controls.sensitivity_rotate }
    #[setter]
    fn set_sensitivity_rotate(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_rotate = v; }
    /// Multiplier for scroll and pinch zoom speed.
    #[getter]
    fn sensitivity_zoom(&self) -> Float { self.config.borrow().controls.sensitivity_zoom }
    #[setter]
    fn set_sensitivity_zoom(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_zoom = v; }
    /// Treat alt + left-drag as a middle-drag, so the arcball can be orbited
    /// on hardware with no middle button. Blender calls the same setting
    /// "Emulate 3 Button Mouse". Defaults on for macOS, where a trackpad is
    /// the common case, and off elsewhere.
    /// Let `Option`/`Alt` + left-drag stand in for a middle-drag.
    ///
    /// Defaults on for macOS, matching Blender's "Emulate 3 Button Mouse". It exists
    /// because a trackpad has no middle button, which once made the arcball
    /// completely unusable there.
    #[getter]
    fn emulate_middle_button(&self) -> bool { self.config.borrow().controls.emulate_middle_button }
    #[setter]
    fn set_emulate_middle_button(&mut self, v: bool) { self.config.borrow_mut().controls.emulate_middle_button = v; }
    /// Two-finger swipe on a trackpad orbits, `shift` pans and `ctrl` zooms; off, it zooms like a wheel.
    ///
    /// Blender's default trackpad map. A trackpad is told from a wheel by
    /// what it reports -- pixels against notches -- which is how Blender
    /// tells them apart too, so a Magic Mouse counts as a trackpad here as
    /// it does there; this is the switch for it. A pinch zooms either way.
    #[getter]
    fn trackpad_orbit(&self) -> bool { self.config.borrow().controls.trackpad_orbit }
    #[setter]
    fn set_trackpad_orbit(&mut self, v: bool) { self.config.borrow_mut().controls.trackpad_orbit = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().controls)
    }
}

/// The size of the image being rendered, as distinct from the window.
///
/// `app.simulation.config.image`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ImageConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ImageConfig {
    /// Render size in physical pixels -- the *image*, not the window.
    ///
    /// `0` means "follow the window", which is what a terminal run wants and
    /// what every script got when there was only one pair of these. Set it to
    /// pin the render independently: a 4K export from a small window, or a
    /// fixed frame size while the editor's viewport panel is dragged about.
    ///
    /// Everything about the image follows this -- the camera's aspect ratio,
    /// where axis ticks project, where the colour bar sits, and what an
    /// exported frame measures.
    #[getter]
    fn width(&self) -> u32 { self.config.borrow().image.width }
    #[setter]
    fn set_width(&mut self, v: u32) { self.config.borrow_mut().image.width = v; }
    #[getter]
    fn height(&self) -> u32 { self.config.borrow().image.height }
    #[setter]
    fn set_height(&mut self, v: u32) { self.config.borrow_mut().image.height = v; }
    /// Mirror the image left to right: the camera's right drawn on the left.
    ///
    /// For an instrument whose images are stored mirrored, so a frame
    /// compares pixel for pixel: pixel `(0, 0)` of an image is its top-left
    /// corner, which a camera fills with the top left of what it sees, and
    /// these put another corner of the view there -- `flip_y` the bottom
    /// left, both the bottom right. The scene is mirrored, on screen and in
    /// an exported frame; the HUD and the colour bar are not. Picking, the
    /// navigation gizmo and the mouse follow the mirror.
    #[getter]
    fn flip_x(&self) -> bool { self.config.borrow().image.flip_x }
    #[setter]
    fn set_flip_x(&mut self, v: bool) { self.config.borrow_mut().image.flip_x = v; }
    /// Mirror the image top to bottom: the camera's up drawn at the bottom.
    #[getter]
    fn flip_y(&self) -> bool { self.config.borrow().image.flip_y }
    #[setter]
    fn set_flip_y(&mut self, v: bool) { self.config.borrow_mut().image.flip_y = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().image)
    }
}

/// Diagnostics and console output.
///
/// `app.simulation.config.debug`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct DebugConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl DebugConfig {
    /// Print app lifecycle events: pause and camera-mode changes.
    #[getter]
    fn app(&self) -> bool { self.config.borrow().debug.app }
    #[setter]
    fn set_app(&mut self, v: bool) { self.config.borrow_mut().debug.app = v; }
    /// Print window and GPU setup: chosen surface format, adapter and device
    /// features, and **the present modes the surface supports**.
    ///
    /// Worth enabling once on any new machine -- it is how the vsync cap that
    /// invalidated a whole benchmark was identified.
    #[getter]
    fn window(&self) -> bool { self.config.borrow().debug.window }
    #[setter]
    fn set_window(&mut self, v: bool) { self.config.borrow_mut().debug.window = v; }
    /// Print per-mesh detail as meshes are uploaded.
    #[getter]
    fn window_mesh(&self) -> bool { self.config.borrow().debug.window_mesh }
    #[setter]
    fn set_window_mesh(&mut self, v: bool) { self.config.borrow_mut().debug.window_mesh = v; }
    /// **Does nothing.** The field exists and is settable from Python, but no code
    /// reads it. Left as a placeholder.
    #[getter]
    fn simulation(&self) -> bool { self.config.borrow().debug.simulation }
    #[setter]
    fn set_simulation(&mut self, v: bool) { self.config.borrow_mut().debug.simulation = v; }
    /// Time each GPU pass with timestamp queries, into `sim.gpu_timings()`.
    ///
    /// Off by default: the queries themselves are nearly free, but reading them
    /// back costs a buffer map per frame, and nothing needs it unless someone is
    /// asking where a frame goes. Silently inert where the adapter has no
    /// `TIMESTAMP_QUERY` -- `sim.gpu_timings()` returns an empty dict there.
    ///
    /// Draw the shadow/depth map as an overlay instead of leaving it offscreen.
    ///
    /// Only mirrors the main pass's depth at `msaa = 1`; above that the pass writes
    /// its own multisampled depth buffer and the debug view is not it.
    #[getter]
    fn gpu_timing(&self) -> bool { self.config.borrow().debug.gpu_timing }
    #[setter]
    fn set_gpu_timing(&mut self, v: bool) { self.config.borrow_mut().debug.gpu_timing = v; }
    /// Count what each body actually drew, with occlusion queries.
    ///
    /// The Visibility panel otherwise tests bounding boxes against the
    /// frustum, so "visible" means "could be seen", and a body wholly behind
    /// another still counts. This draws each body's box after the scene, with
    /// the depth test on and depth writes off, and asks the GPU how many
    /// samples survived. Zero means it put nothing on screen.
    ///
    /// Off by default: it costs a readback every frame, for a diagnostic.
    /// A box is a conservative stand-in for its body, so this can still call
    /// a body visible when only its box is -- the same direction the frustum
    /// test errs in.
    #[getter]
    fn occlusion_queries(&self) -> bool { self.config.borrow().debug.occlusion_queries }
    #[setter]
    fn set_occlusion_queries(&mut self, v: bool) { self.config.borrow_mut().debug.occlusion_queries = v; }
    #[getter]
    fn depth_show(&self) -> bool { self.config.borrow().debug.depth_show }
    #[setter]
    fn set_depth_show(&mut self, v: bool) { self.config.borrow_mut().debug.depth_show = v; }
    /// Free integer passed through to the shader, for one-off experiments.
    #[getter]
    fn extra(&self) -> u32 { self.config.borrow().debug.extra }
    #[setter]
    fn set_extra(&mut self, v: u32) { self.config.borrow_mut().debug.extra = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().debug)
    }
}

/// The groups, as live views. Generated beside the group classes so a
/// group added to the struct appears here without anyone remembering.
#[pymethods]
impl super::config::Config {
    /// How the surface is coloured and the image encoded.
    #[getter]
    fn shading(&self) -> ShadingConfig { ShadingConfig { config: self.config.clone() } }
    /// The Sun as a light: its colour, the ambient floor, the debug cube.
    #[getter]
    fn light(&self) -> LightConfig { LightConfig { config: self.config.clone() } }
    /// The shadow map and its readback.
    #[getter]
    fn shadows(&self) -> ShadowsConfig { ShadowsConfig { config: self.config.clone() } }
    /// Facet edges drawn over or instead of the surface.
    #[getter]
    fn wireframe(&self) -> WireframeConfig { WireframeConfig { config: self.config.clone() } }
    /// The picked facet and the facet labels.
    #[getter]
    fn selection(&self) -> SelectionConfig { SelectionConfig { config: self.config.clone() } }
    /// Colouring facets from per-facet values.
    #[getter]
    fn data(&self) -> DataConfig { DataConfig { config: self.config.clone() } }
    /// The colour scale drawn for `data`.
    #[getter]
    fn colorbar(&self) -> ColorbarConfig { ColorbarConfig { config: self.config.clone() } }
    /// Reference axes, tick labels and the navigation gizmo.
    #[getter]
    fn axes(&self) -> AxesConfig { AxesConfig { config: self.config.clone() } }
    /// The shaded ground grid of the `blender` axes style.
    #[getter]
    fn grid(&self) -> GridConfig { GridConfig { config: self.config.clone() } }
    /// The text overlays.
    #[getter]
    fn hud(&self) -> HudConfig { HudConfig { config: self.config.clone() } }
    /// Frame export.
    #[getter]
    fn export(&self) -> ExportConfig { ExportConfig { config: self.config.clone() } }
    /// Mouse and keyboard sensitivities.
    #[getter]
    fn controls(&self) -> ControlsConfig { ControlsConfig { config: self.config.clone() } }
    /// The size of the image being rendered, as distinct from the window.
    #[getter]
    fn image(&self) -> ImageConfig { ImageConfig { config: self.config.clone() } }
    /// Diagnostics and console output.
    #[getter]
    fn debug(&self) -> DebugConfig { DebugConfig { config: self.config.clone() } }

    /// Old flat names, for one release: forwarded to the group they
    /// moved into, with a `DeprecationWarning` naming the new path.
    /// Table in `tools/config_renames.py`.
    fn __getattr__(slf: &Bound<'_, Self>, name: &str) -> PyResult<Py<PyAny>> {
        let py = slf.py();
        if let Some((group, new)) = renamed(name) {
            deprecated(py, name, group, new)?;
            return Ok(slf.getattr(group)?.getattr(new)?.unbind());
        }
        if MOVED_TO_APP.contains(&name) {
            return Err(pyo3::exceptions::PyAttributeError::new_err(format!(
                "config.{name} is a window property and moved to app.config.{name}"
            )));
        }
        Err(pyo3::exceptions::PyAttributeError::new_err(format!(
            "'Config' object has no attribute {name:?}"
        )))
    }

    /// The setter half of the shim. Anything not in the table takes the
    /// ordinary path, so the real setters on this class still run.
    fn __setattr__(slf: &Bound<'_, Self>, name: &str, value: Bound<'_, PyAny>) -> PyResult<()> {
        let py = slf.py();
        if let Some((group, new)) = renamed(name) {
            deprecated(py, name, group, new)?;
            return slf.getattr(group)?.setattr(new, value);
        }
        if MOVED_TO_APP.contains(&name) {
            return Err(pyo3::exceptions::PyAttributeError::new_err(format!(
                "config.{name} is a window property and moved to app.config.{name}"
            )));
        }
        // The generic path, by hand: calling `slf.setattr` here would come
        // straight back to this function.
        let key = pyo3::types::PyString::new(py, name);
        let rc = unsafe {
            pyo3::ffi::PyObject_GenericSetAttr(slf.as_ptr(), key.as_ptr(), value.as_ptr())
        };
        if rc == -1 {
            return Err(PyErr::fetch(py));
        }
        Ok(())
    }
}

/// Where a flat name went, if it was one.
fn renamed(name: &str) -> Option<(&'static str, &'static str)> {
    match name {
        "access_shadow_map" => Some(("shadows", "access_shadow_map")),
        "ambient_strength" => Some(("light", "ambient")),
        "axes" => Some(("axes", "style")),
        "axes_color" => Some(("axes", "color")),
        "axes_label_color" => Some(("axes", "label_color")),
        "axes_label_size" => Some(("axes", "label_size")),
        "axes_ticks" => Some(("axes", "ticks")),
        "axes_unit" => Some(("axes", "unit")),
        "background" => Some(("shading", "background")),
        "color" => Some(("shading", "color")),
        "color_mode" => Some(("shading", "color_mode")),
        "colorbar" => Some(("colorbar", "enabled")),
        "colorbar_anchor" => Some(("colorbar", "anchor")),
        "colorbar_border" => Some(("colorbar", "border")),
        "colorbar_label" => Some(("colorbar", "label")),
        "colorbar_length" => Some(("colorbar", "length")),
        "colorbar_text_color" => Some(("colorbar", "text_color")),
        "colorbar_text_size" => Some(("colorbar", "text_size")),
        "colorbar_thickness" => Some(("colorbar", "thickness")),
        "colorbar_ticks" => Some(("colorbar", "ticks")),
        "colorbar_vertical" => Some(("colorbar", "vertical")),
        "colorbar_x" => Some(("colorbar", "x")),
        "colorbar_y" => Some(("colorbar", "y")),
        "colormap" => Some(("data", "colormap")),
        "debug_app" => Some(("debug", "app")),
        "debug_depth_show" => Some(("debug", "depth_show")),
        "debug_light_cube_fit" => Some(("light", "cube_fit")),
        "debug_light_cube_show" => Some(("light", "cube_show")),
        "debug_simulation" => Some(("debug", "simulation")),
        "debug_window" => Some(("debug", "window")),
        "debug_window_mesh" => Some(("debug", "window_mesh")),
        "emulate_middle_button" => Some(("controls", "emulate_middle_button")),
        "export_dir" => Some(("export", "dir")),
        "export_hud" => Some(("export", "hud")),
        "export_max_queued" => Some(("export", "max_queued")),
        "export_sync" => Some(("export", "sync")),
        "extra" => Some(("debug", "extra")),
        "facet_label_color" => Some(("selection", "label_color")),
        "facet_label_size" => Some(("selection", "label_size")),
        "facet_labels" => Some(("selection", "labels")),
        "facet_labels_max" => Some(("selection", "labels_max")),
        "gamma" => Some(("shading", "gamma")),
        "gizmo_anchor" => Some(("axes", "gizmo_anchor")),
        "gizmo_size" => Some(("axes", "gizmo_size")),
        "gpu_timing" => Some(("debug", "gpu_timing")),
        "grid" => Some(("grid", "enabled")),
        "grid_axis_x_color" => Some(("grid", "axis_x_color")),
        "grid_axis_y_color" => Some(("grid", "axis_y_color")),
        "grid_axis_z_color" => Some(("grid", "axis_z_color")),
        "grid_color" => Some(("grid", "color")),
        "grid_fade_far" => Some(("grid", "fade_far")),
        "grid_fade_near" => Some(("grid", "fade_near")),
        "grid_major" => Some(("grid", "major")),
        "grid_major_color" => Some(("grid", "major_color")),
        "grid_width" => Some(("grid", "width")),
        "height" => Some(("image", "height")),
        "hud_font" => Some(("hud", "font")),
        "light_color" => Some(("light", "color")),
        "light_cube_scale" => Some(("light", "cube_scale")),
        "msaa" => Some(("shading", "msaa")),
        "occlusion_queries" => Some(("debug", "occlusion_queries")),
        "render_back_face" => Some(("shading", "render_back_face")),
        "selection_color" => Some(("selection", "color")),
        "sensitivity_look" => Some(("controls", "sensitivity_look")),
        "sensitivity_move" => Some(("controls", "sensitivity_move")),
        "sensitivity_rotate" => Some(("controls", "sensitivity_rotate")),
        "sensitivity_zoom" => Some(("controls", "sensitivity_zoom")),
        "shadow_bias_minimum" => Some(("shadows", "bias_minimum")),
        "shadow_bias_scale" => Some(("shadows", "bias_scale")),
        "shadow_normal_offset_scale" => Some(("shadows", "normal_offset_scale")),
        "shadow_pcf" => Some(("shadows", "pcf")),
        "shadow_per_body" => Some(("shadows", "per_body")),
        "shadow_resolution" => Some(("shadows", "resolution")),
        "srgb_mode" => Some(("shading", "srgb_mode")),
        "value_max" => Some(("data", "value_max")),
        "value_min" => Some(("data", "value_min")),
        "width" => Some(("image", "width")),
        "wireframe_color" => Some(("wireframe", "color")),
        "wireframe_fade" => Some(("wireframe", "fade")),
        "wireframe_mode" => Some(("wireframe", "mode")),
        "wireframe_width" => Some(("wireframe", "width")),
        _ => None,
    }
}

const MOVED_TO_APP: &[&str] = &["fullscreen", "title", "vsync"];

fn deprecated(py: Python<'_>, old: &str, group: &str, new: &str) -> PyResult<()> {
    let msg = std::ffi::CString::new(format!(
        "config.{old} is deprecated; use config.{group}.{new}"
    ))?;
    PyErr::warn(
        py,
        &py.get_type::<pyo3::exceptions::PyDeprecationWarning>(),
        msg.as_c_str(),
        // The script's line: a Rust call has no frame of its own, so 2
        // was the caller's caller -- `<sys>` for a script's top level,
        // which the default filters hide. Nobody saw these.
        1,
    )
}

/// The application's own settings, flat.
#[pymethods]
impl super::config::AppConfig {
    /// Draw in the editor layout: viewport panel, script, config, log.
    ///
    /// A *mode*, not a different loop. `start()` and `step()` behave exactly
    /// as they always did -- the frame simply also draws the UI, and the
    /// scene lands in the viewport panel instead of filling the window. So a
    /// script that drives its own `while app.step():` gets the editor around
    /// it without changing a line, which is the whole reason `step()` was
    /// made non-blocking.
    ///
    /// `start_editor()` is this plus `start()`.
    ///
    /// No widget: a checkbox that switches the UI off from inside the UI
    /// leaves nothing to switch it back on with.
    #[getter]
    fn editor(&self) -> bool { self.config.borrow().editor }
    #[setter]
    fn set_editor(&mut self, v: bool) { self.config.borrow_mut().editor = v; }
    /// Give the whole window to the renderer: panels out of the way, each
    /// coming back when the pointer reaches its edge.
    ///
    /// Focus on the scene, in other words. Not on the window -- that is yours
    /// to size, by double clicking its title bar or dragging a corner -- but
    /// on what is inside it. A focused renderer looks like a plain render
    /// window, with the panels a pointer-flick away: top for the toolbar,
    /// right for the side panel, bottom for the log.
    ///
    /// Independent of `simulation.config.fullscreen`, which is the OS window
    /// and nothing else. Set both to be rid of everything at once; set this
    /// alone and the window stays where it is.
    #[getter]
    fn focus(&self) -> bool { self.config.borrow().focus }
    #[setter]
    fn set_focus(&mut self, v: bool) { self.config.borrow_mut().focus = v; }
    /// Fold the editor's panels to the window edges; `N` toggles it.
    ///
    /// Toolbar, side panel and log fold to their edges and come back
    /// together; each keeps egui's thin handle, so one can be dragged or
    /// double-clicked back out on its own, and an arrow key folds or unfolds
    /// the panel on that edge. Reads `true` only while all three are folded,
    /// so bringing one out clears it. The halfway house between the full
    /// layout and `focus`, which hides everything and reveals on hover. Set
    /// before `start()` to open the editor folded.
    #[getter]
    fn panels_folded(&self) -> bool { self.config.borrow().panels_folded }
    #[setter]
    fn set_panels_folded(&mut self, v: bool) { self.config.borrow_mut().panels_folded = v; }
    /// Fold the toolbar, the top panel, or bring it back; `↑` toggles it.
    ///
    /// Live, and written back: reads `true` while the toolbar is folded,
    /// however it got there -- this field, the key, a drag on its edge, or
    /// `panels_folded`. One per panel; `panels_folded` is all three at once.
    #[getter]
    fn toolbar_folded(&self) -> bool { self.config.borrow().toolbar_folded }
    #[setter]
    fn set_toolbar_folded(&mut self, v: bool) { self.config.borrow_mut().toolbar_folded = v; }
    /// Fold the log, the bottom panel, or bring it back; `↓` toggles it.
    ///
    /// Live and written back, like `toolbar_folded`.
    #[getter]
    fn log_folded(&self) -> bool { self.config.borrow().log_folded }
    #[setter]
    fn set_log_folded(&mut self, v: bool) { self.config.borrow_mut().log_folded = v; }
    /// Does nothing now: the script is the middle's editor tab, and the left
    /// edge has no panel to fold. Kept so a script that sets it still runs.
    ///
    /// No widget: a checkbox that does nothing is worse than none.
    #[getter]
    fn script_folded(&self) -> bool { self.config.borrow().script_folded }
    #[setter]
    fn set_script_folded(&mut self, v: bool) { self.config.borrow_mut().script_folded = v; }
    /// Fold the side panel, on the right -- app, simulation and files -- or
    /// bring it back; `→` toggles it.
    ///
    /// Live and written back, like `toolbar_folded`.
    #[getter]
    fn simulation_folded(&self) -> bool { self.config.borrow().simulation_folded }
    #[setter]
    fn set_simulation_folded(&mut self, v: bool) { self.config.borrow_mut().simulation_folded = v; }
    /// What the editor's toolbar says beside the transport buttons.
    ///
    /// The same template as `huds`, so every placeholder works here too --
    /// `{drawn}` for the iteration on screen, `{it}` for how many have been
    /// begun, `{its}`, `{fps}`, `{ms}`, `{bodies}`, `{paused}`, `{warn}`,
    /// `{gpu}` and its per-pass forms -- and a precision may be attached, as
    /// `{fps:.1}`.
    ///
    /// Empty for a bare toolbar.
    #[getter]
    fn toolbar(&self) -> String { self.config.borrow().toolbar.clone() }
    #[setter]
    fn set_toolbar(&mut self, v: &str) { self.config.borrow_mut().toolbar = v.to_string(); }
    /// The colours of the UI app's panels: `"catppuccin-mocha"`, the default,
    /// or `"dark"`, egui's own.
    ///
    /// The panels only. The scene -- its background included -- is drawn by
    /// the renderer from `app.simulation.config` and shown as an image no
    /// theme tints, so a frame looks the same under either, on screen and
    /// exported.
    #[getter]
    fn theme(&self) -> String { self.config.borrow().theme.name().to_string() }
    #[setter]
    fn set_theme(&mut self, v: &str) -> PyResult<()> {
        let t = crate::app::config::UiTheme::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown theme {v:?}: expected catppuccin-mocha or dark"
            ))
        })?;
        self.config.borrow_mut().theme = t;
        Ok(())
    }
    /// Open the window without taking focus, so a run can go on beside
    /// other work.
    ///
    /// A render window normally comes up *key* and pulls the keyboard away
    /// from whatever was in front of it, which is fine for one run and not
    /// fine for a script that opens a window per case. With this set the
    /// window is ordered in behind the active application instead, and
    /// nothing is typed into it by accident.
    ///
    /// **Startup only** -- it decides how the window is first shown, and how
    /// the application announces itself, neither of which can be taken back
    /// afterwards. Set it before `start()` or the first `step()`.
    ///
    /// The window is still drawn and still interactive; it simply has to be
    /// clicked before it takes the keyboard.
    ///
    /// Named at length because two shorter names were taken and both mean
    /// something else: `focus` here is the panels *inside* the window, and
    /// `simulation.config.background` is the colour the frame is cleared to.
    ///
    /// Unsupported on X11 and Wayland, where winit cannot ask for it, and the
    /// window comes up focused as before.
    ///
    /// No widget: it is read once, while the window is being created. By the
    /// time there is a panel to tick it in, the window it would have governed
    /// is already open, and a checkbox that does nothing is worse than none.
    #[getter]
    fn open_in_background(&self) -> bool { self.config.borrow().open_in_background }
    #[setter]
    fn set_open_in_background(&mut self, v: bool) { self.config.borrow_mut().open_in_background = v; }
    /// Open the UI app's window where it was left: on its screen, at its
    /// place and size, fullscreen if it was.
    ///
    /// Off, it opens where `monitor`, `window_x`, `window_y`, `width`,
    /// `height` and `start_fullscreen` say, every time; the app tab shows
    /// them then, and remembers them as they are set there.
    #[getter]
    fn remember_window(&self) -> bool { self.config.borrow().remember_window }
    #[setter]
    fn set_remember_window(&mut self, v: bool) { self.config.borrow_mut().remember_window = v; }
    /// Window size in physical pixels.
    ///
    /// The *window*, not the render. `simulation.config.width` is the image
    /// inside it, and follows this unless it is set.
    ///
    /// `0`, the default: the size the UI app was left at, or else most of
    /// the screen. Set, it wins over what the app remembers.
    ///
    /// In the app tab while `remember_window` is off, beside the screen and
    /// the place: written by hand there (`gui::window_start`).
    #[getter]
    fn width(&self) -> u32 { self.config.borrow().width }
    #[setter]
    fn set_width(&mut self, v: u32) { self.config.borrow_mut().width = v; }
    #[getter]
    fn height(&self) -> u32 { self.config.borrow().height }
    #[setter]
    fn set_height(&mut self, v: u32) { self.config.borrow_mut().height = v; }
    /// The screen the window opens on: its number in the system's list,
    /// from `"1"`, or part of its name, as `"DELL"` or `"Built-in"`.
    ///
    /// Empty, the default: the screen the UI app was last closed on, where
    /// it was on it -- or else the main screen, the window in its middle.
    /// Set, it wins over what the app remembers, as `width` and `height` do.
    /// Set while the window is open, it moves it there.
    ///
    /// A list of the screens in the app tab while `remember_window` is off,
    /// written by hand: a name typed in would move the window at each letter.
    #[getter]
    fn monitor(&self) -> String { self.config.borrow().monitor.clone() }
    #[setter]
    fn set_monitor(&mut self, v: &str) { self.config.borrow_mut().monitor = v.to_string(); }
    /// Where on its screen the window opens: its top-left corner from the
    /// screen's, in physical pixels. `-1`, the default: in the screen's
    /// middle, or where the UI app left it. Set while the window is open,
    /// it moves it there.
    ///
    /// In the app tab while `remember_window` is off, with `width`.
    #[getter]
    fn window_x(&self) -> i32 { self.config.borrow().window_x }
    #[setter]
    fn set_window_x(&mut self, v: i32) { self.config.borrow_mut().window_x = v; }
    #[getter]
    fn window_y(&self) -> i32 { self.config.borrow().window_y }
    #[setter]
    fn set_window_y(&mut self, v: i32) { self.config.borrow_mut().window_y = v; }
    /// Open the UI app fullscreen, while `remember_window` is off -- `F` and
    /// the green button then change the window, not this.
    ///
    /// In the app tab while `remember_window` is off.
    #[getter]
    fn start_fullscreen(&self) -> bool { self.config.borrow().start_fullscreen }
    #[setter]
    fn set_start_fullscreen(&mut self, v: bool) { self.config.borrow_mut().start_fullscreen = v; }
    /// The OS window title.
    #[getter]
    fn title(&self) -> String { self.config.borrow().title.clone() }
    #[setter]
    fn set_title(&mut self, v: &str) { self.config.borrow_mut().title = v.to_string(); }
    /// Open the window in native fullscreen (borderless, current monitor).
    ///
    /// On macOS this is the same mode the green button gives -- its own
    /// Space -- which is worth knowing because it is not equivalent to a
    /// maximised window: the compositor hands out drawables differently
    /// there, and a stall that only appears fullscreen will not reproduce
    /// maximised.
    ///
    /// Startup only: applied when the window is created.
    #[getter]
    fn fullscreen(&self) -> bool { self.config.borrow().fullscreen }
    #[setter]
    fn set_fullscreen(&mut self, v: bool) { self.config.borrow_mut().fullscreen = v; }
    /// Cap the frame rate to the display refresh.
    ///
    /// **Off by default**, because a capped loop reports the monitor rather
    /// than the scene: on a 239 Hz panel the render loop measured exactly
    /// 239.46 it/s regardless of complexity, which made a 3.1M-facet scene
    /// look identical to a 100k one. That trap cost a wrong conclusion once
    /// and was worked around by hand in nine scripts, so it is the default
    /// that is wrong rather than those scripts.
    ///
    /// The price is that an idle viewer redraws as fast as it can instead of
    /// 60 times a second. Set `True` when you are looking at a scene rather
    /// than timing one.
    #[getter]
    fn vsync(&self) -> bool { self.config.borrow().vsync }
    #[setter]
    fn set_vsync(&mut self, v: bool) { self.config.borrow_mut().vsync = v; }
    /// Neovim in the script editor: your own `nvim`, run the way VS Code's
    /// Neovim extension runs it -- modes, motions, operators, `:` commands,
    /// registers, macros and mappings -- with the config `neovim_config`
    /// names.
    ///
    /// Needs Neovim 0.10 or newer, as `nvim` on the PATH or named by
    /// `neovim_path`. The config is read with `vim.g.kalast` set, so a part
    /// of it that has no place here can be skipped with `if not vim.g.kalast`
    /// -- the way `vim.g.vscode` is used for VS Code. Off, the editor takes
    /// VS Code's keys.
    #[getter]
    fn neovim(&self) -> bool { self.config.borrow().neovim }
    #[setter]
    fn set_neovim(&mut self, v: bool) { self.config.borrow_mut().neovim = v; }
    /// The Neovim to run when `neovim` is on; empty for `nvim` on the PATH.
    #[getter]
    fn neovim_path(&self) -> String { self.config.borrow().neovim_path.clone() }
    #[setter]
    fn set_neovim_path(&mut self, v: &str) { self.config.borrow_mut().neovim_path = v.to_string(); }
    /// The config Neovim reads: `"kalast"`, the one kalast ships; `"user"`,
    /// your own, where Neovim looks for it; or a path, to a config folder
    /// holding `init.lua` or to one file.
    ///
    /// kalast's is its author's: lazy.nvim and its plugins, which it clones
    /// with git the first time it starts, into a folder of its own
    /// (`~/.local/share/kalast-nvim`), apart from your own Neovim's.
    #[getter]
    fn neovim_config(&self) -> String { self.config.borrow().neovim_config.clone() }
    #[setter]
    fn set_neovim_config(&mut self, v: &str) { self.config.borrow_mut().neovim_config = v.to_string(); }
    /// The column the script editor draws a vertical line at, 0 for none:
    /// `editor.rulers` in VS Code, `colorcolumn` in Vim.
    #[getter]
    fn ruler(&self) -> u32 { self.config.borrow().ruler }
    #[setter]
    fn set_ruler(&mut self, v: u32) { self.config.borrow_mut().ruler = v; }
    /// Completion, hover, signatures and errors in the script editor, from a
    /// language server -- pyright for Python, rust-analyzer for Rust -- the
    /// servers VS Code runs for its own.
    ///
    /// Each runs as a process of its own at low priority, so a simulation
    /// never waits on it. One that is not installed is skipped, and the log
    /// says how to install it.
    #[getter]
    fn language_servers(&self) -> bool { self.config.borrow().language_servers }
    #[setter]
    fn set_language_servers(&mut self, v: bool) { self.config.borrow_mut().language_servers = v; }
    /// The command starting the Python language server; empty for the first
    /// of `basedpyright-langserver`, `pyright-langserver`, `pylsp` and
    /// `jedi-language-server` found.
    #[getter]
    fn python_language_server(&self) -> String { self.config.borrow().python_language_server.clone() }
    #[setter]
    fn set_python_language_server(&mut self, v: &str) { self.config.borrow_mut().python_language_server = v.to_string(); }
    /// The command starting the Rust language server; empty for
    /// `rust-analyzer`.
    #[getter]
    fn rust_language_server(&self) -> String { self.config.borrow().rust_language_server.clone() }
    #[setter]
    fn set_rust_language_server(&mut self, v: &str) { self.config.borrow_mut().rust_language_server = v.to_string(); }
    /// Ask GitHub for a newer release when the UI app opens, and offer it in
    /// the toolbar. On a thread, so nothing waits on it; never when a script
    /// runs its own window. Off, kalast touches the network at no point.
    #[getter]
    fn check_updates(&self) -> bool { self.config.borrow().check_updates }
    #[setter]
    fn set_check_updates(&mut self, v: bool) { self.config.borrow_mut().check_updates = v; }
}

