// Generated by tools/gen_bindings.py -- do not edit by hand.
//
// Regenerate after changing `Config` or `AppConfig`:  python tools/gen_bindings.py
//
// Hand-written accessors with real logic live in `config.rs`, on fields
// marked `:py_custom:`; everything here is mechanical.

use std::{cell::RefCell, rc::Rc};

use pyo3::prelude::*;

use crate::Float;

/// How the surface is coloured and the image encoded.
///
/// `app.simulation.config.shading`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ShadingConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ShadingConfig {
    /// Colour the frame is cleared to, `(r, g, b, a)`.
    ///
    /// Accepts any 4-element sequence: tuple, list or `numpy.array`.
    #[getter]
    fn background(&self) -> [Float; 4] {
        let c = self.config.borrow().shading.background;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_background(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().shading.background = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Draw triangles facing away from the camera.
    ///
    /// Leave it off for closed shape models -- back faces are invisible there, so
    /// culling them is free performance. Measured on the full-resolution
    /// Didymos/Dimorphos meshes: culled against unculled differs in 5 pixels of
    /// 1,040,400, all on silhouette edges.
    ///
    /// Turn it on for geometry that is *not* closed -- open craters, clipped
    /// sections, single-sided surfaces -- where the inside of the shell must be
    /// visible from outside. Note the shading is single-sided regardless: normals
    /// are not flipped for back faces, so an underside is lit as though it were the
    /// top.
    ///
    /// The shadow pass stays unculled either way, so open geometry still casts
    /// correctly from whichever side faces the light.
    #[getter]
    fn render_back_face(&self) -> bool { self.config.borrow().shading.render_back_face }
    #[setter]
    fn set_render_back_face(&mut self, v: bool) { self.config.borrow_mut().shading.render_back_face = v; }
    /// Multisample anti-aliasing for the main render pass: 1 (off), 2, 4 or 8.
    ///
    /// Geometry edges are the whole point here. Every silhouette in this
    /// renderer is a science measurement -- a limb, a terminator, a body's
    /// apparent diameter -- and at one sample per pixel each of those is
    /// quantised to whole pixels, which both looks wrong beside other tools
    /// and biases any centroid or radius fitted from an exported frame.
    ///
    /// Only the main pass is multisampled. The shadow map, the facet-id and
    /// hemicube passes stay single-sampled on purpose: they carry ids and
    /// depths, not colour, and averaging those across samples would be
    /// meaningless. Exports are unaffected in shape or size -- the pass
    /// resolves into the same single-sample target that was always exported.
    ///
    /// Counts the adapter does not support fall back to 4, then to 1. Note
    /// that `debug_depth_show` only mirrors the main pass's depth at 1: above
    /// that the pass writes its own multisampled depth buffer instead.
    #[getter]
    fn msaa(&self) -> u32 { self.config.borrow().shading.msaa }
    #[setter]
    fn set_msaa(&mut self, v: u32) { self.config.borrow_mut().shading.msaa = v; }
    /// Flat colour used when `color_mode` is 2, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().shading.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().shading.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// What the fragment shader outputs.
    ///
    /// | | |
    /// |---|---|
    /// | 0 | vertex/instance colour, lit, with shadows (the default) |
    /// | 1 | raw vertex/instance colour, no lighting |
    /// | 2 | the flat `color` |
    /// | 3 | as 0 but with shadows disabled |
    #[getter]
    fn color_mode(&self) -> u32 { self.config.borrow().shading.color_mode }
    #[setter]
    fn set_color_mode(&mut self, v: u32) { self.config.borrow_mut().shading.color_mode = v; }
    /// 0 converts sRGB to linear before shading; 1 treats colours as already
    /// linear.
    #[getter]
    fn srgb_mode(&self) -> u32 { self.config.borrow().shading.srgb_mode }
    #[setter]
    fn set_srgb_mode(&mut self, v: u32) { self.config.borrow_mut().shading.srgb_mode = v; }
    /// Exponent used by the sRGB conversion when `srgb_mode` is 0.
    #[getter]
    fn gamma(&self) -> Float { self.config.borrow().shading.gamma }
    #[setter]
    fn set_gamma(&mut self, v: Float) { self.config.borrow_mut().shading.gamma = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().shading)
    }
}

/// The Sun as a light: its colour, the ambient floor, the debug cube.
///
/// `app.simulation.config.light`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct LightConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl LightConfig {
    /// Draw a cube at the light's position, so the Sun is visible.
    ///
    /// Size comes from `light_cube_scale`. `debug_light_cube_fit` is on by
    /// default, which is what makes it *visible* rather than merely drawn:
    /// the camera's far plane is fitted to the bodies, and the Sun is well
    /// outside them.
    #[getter]
    fn cube_show(&self) -> bool { self.config.borrow().light.cube_show }
    #[setter]
    fn set_cube_show(&mut self, v: bool) { self.config.borrow_mut().light.cube_show = v; }
    /// Fit the camera's frustum around the light cube too, not just the
    /// bodies.
    ///
    /// What makes `debug_light_cube_show` show something, so it defaults to
    /// **on**: without it the Sun sits past the fitted far plane and is
    /// clipped away, and asking to see the light and being shown nothing is
    /// not a useful default. Nothing happens either way unless the cube is
    /// being drawn.
    ///
    /// Turn it off to keep the frustum fitted to the geometry being studied
    /// while the cube is on -- for a figure where the cube is out of frame
    /// but the framing must not change.
    ///
    /// The **camera** only. The light's own frustum stays fitted to the
    /// bodies, because it is what the shadow map covers: stretching it to the
    /// Sun would spend the whole map on empty space and leave the bodies a
    /// few texels across.
    ///
    /// Costs the depth range: a far plane at the Sun rather than at the
    /// body's edge is a much longer near-to-far span, so depth precision
    /// drops. For looking at where the light is, not for a figure.
    #[getter]
    fn cube_fit(&self) -> bool { self.config.borrow().light.cube_fit }
    #[setter]
    fn set_cube_fit(&mut self, v: bool) { self.config.borrow_mut().light.cube_fit = v; }
    /// Light added to every fragment regardless of shadowing.
    ///
    /// **Zero by default.** A shadowed facet on an airless body receives
    /// essentially nothing, so any ambient term is light the scene does not
    /// have -- and a shadow that is not black is a shadow whose depth cannot
    /// be read off the image. It was 0.002, small enough to look like nothing
    /// and large enough to be a floor under every dark pixel.
    ///
    /// Raise it to see into shadows while navigating; it is the wrong thing
    /// to have on for anything quantitative.
    #[getter]
    fn ambient(&self) -> f32 { self.config.borrow().light.ambient }
    #[setter]
    fn set_ambient(&mut self, v: f32) { self.config.borrow_mut().light.ambient = v; }
    /// Colour of the Sun, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().light.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().light.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Size of the debug light cube, in world units.
    ///
    /// Only drawn when `debug_light_cube_show` is on.
    #[getter]
    fn cube_scale(&self) -> Float { self.config.borrow().light.cube_scale }
    #[setter]
    fn set_cube_scale(&mut self, v: Float) { self.config.borrow_mut().light.cube_scale = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().light)
    }
}

/// The shadow map and its readback.
///
/// `app.simulation.config.shadows`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ShadowsConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ShadowsConfig {
    /// Side length of each square shadow map, in texels.
    ///
    /// The array is always allocated at all 8 layers, so the cost is
    /// `resolution^2 x 4 bytes x 8` -- 2.1 GB at the default 8192, 8.6 GB at 16384.
    /// Dropping to 2048 is the first thing to try when VRAM is tight or interactive
    /// frame times matter.
    ///
    /// It also feeds the automatic bias, which is expressed relative to one texel,
    /// so changing it changes the shadow bias with it.
    #[getter]
    fn resolution(&self) -> u32 { self.config.borrow().shadows.resolution }
    #[setter]
    fn set_resolution(&mut self, v: u32) { self.config.borrow_mut().shadows.resolution = v; }
    /// Percentage-closer-filtering kernel *radius*: 0 is a single hardware 2x2
    /// comparison, N is a `(2N+1)^2` grid averaged.
    ///
    /// Cost grows quadratically and is per-fragment, so it scales with pixel count:
    /// `shadow_pcf = 4` costs +2.5 ms at 800x600 and +7.8 ms at 3024x1964. Benchmark
    /// it at the resolution you actually run.
    ///
    /// The normal offset scales with this, since an N-radius kernel reaches N texels
    /// away and a one-texel offset would let those taps flip. `shadow_pcf = 0` is
    /// bit-identical to the pre-scaling behaviour.
    #[getter]
    fn pcf(&self) -> u32 { self.config.borrow().shadows.pcf }
    #[setter]
    fn set_pcf(&mut self, v: u32) { self.config.borrow_mut().shadows.pcf = v; }
    /// Push the sample along the surface normal before the shadow lookup, in
    /// world units. `None` fits it per frame from the layer's own texel size.
    ///
    /// Scaled by the PCF kernel radius, since an N-radius kernel reaches N
    /// texels away and a one-texel offset would let those taps flip.
    ///
    /// Pinning it is now worse than leaving it automatic: with per-body shadow
    /// layers a pinned value replaces the fitted one on *every* layer, and
    /// those differ by the ratio of the bodies' sizes -- 403x between Mars and
    /// Deimos in the same scene.
    #[getter]
    fn normal_offset_scale(&self) -> Option<f32> { self.config.borrow().shadows.normal_offset_scale }
    #[setter]
    fn set_normal_offset_scale(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.normal_offset_scale = v; }
    /// Slope-dependent term of the depth-comparison bias. `None` fits it per
    /// frame. Combined in the shader as
    /// `max(shadow_bias_scale * k, shadow_bias_minimum)`.
    ///
    /// See `shadow_normal_offset_scale` for why pinning is discouraged.
    #[getter]
    fn bias_scale(&self) -> Option<f32> { self.config.borrow().shadows.bias_scale }
    #[setter]
    fn set_bias_scale(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.bias_scale = v; }
    /// Floor on the depth-comparison bias, for surfaces facing the light
    /// head-on. `None` fits it per frame.
    ///
    /// Measured to be the *ineffective* knob for the crater-floor PCF leak --
    /// auto, 1e-4 and 1e-3 all gave identical results, while the normal offset
    /// moved it 9x. Reach for that one first.
    #[getter]
    fn bias_minimum(&self) -> Option<f32> { self.config.borrow().shadows.bias_minimum }
    #[setter]
    fn set_bias_minimum(&mut self, v: Option<f32>) { self.config.borrow_mut().shadows.bias_minimum = v; }
    /// Read the shadow map back per facet: computes solar occlusion for every
    /// body each frame, readable from `after_render` via
    /// `Simulation::facet_shadow`.
    ///
    /// Off by default because it is not free: the query costs ~1.6 ms per
    /// body at 100k facets and ~7.3 ms at 3.1M, dominated by the blocking
    /// readback. Turn it on for thermophysical or radiance work; leave it off
    /// when you only want images.
    /// Compute per-facet solar occlusion for every body, every frame.
    ///
    /// Read it back with `sim.facet_shadow(body)` from `after_render`. Leave it off
    /// unless something consumes it: it is a compute pass and a readback per frame.
    #[getter]
    fn access_shadow_map(&self) -> bool { self.config.borrow().shadows.access_shadow_map }
    #[setter]
    fn set_access_shadow_map(&mut self, v: bool) { self.config.borrow_mut().shadows.access_shadow_map = v; }
    /// Fit a shadow map per body instead of one fitted to the whole scene.
    ///
    /// On by default, because one shared map is fitted to the scene's extent
    /// and a small body beside a large one then gets almost no texels -- 6 km
    /// Deimos next to 3,396 km Mars is the case that forced this. Each layer
    /// is aimed at its own body and sized to it, while its depth range still
    /// spans the scene, so mutual shadowing is unaffected: anything between
    /// the Sun and a body still casts into that body's layer.
    ///
    /// Costs one shadow pass per body. Turn it off to get the old single
    /// scene-fitted map back, which is only worth doing to reproduce older
    /// output or when every body is a similar size.
    #[getter]
    fn per_body(&self) -> bool { self.config.borrow().shadows.per_body }
    #[setter]
    fn set_per_body(&mut self, v: bool) { self.config.borrow_mut().shadows.per_body = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().shadows)
    }
}

/// Facet edges drawn over or instead of the surface.
///
/// `app.simulation.config.wireframe`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct WireframeConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl WireframeConfig {
    /// the barycentrics are meaningless and the CPU side warns once.
    #[getter]
    fn mode(&self) -> u32 { self.config.borrow().wireframe.mode }
    #[setter]
    fn set_mode(&mut self, v: u32) { self.config.borrow_mut().wireframe.mode = v; }
    /// Wireframe colour, `(r, g, b, a)`; alpha is dropped.
    ///
    /// Mode 2 blends by edge coverage and is antialiased; mode 1 thresholds instead,
    /// because the pipeline blend state is REPLACE and a fractional alpha would be
    /// ignored.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().wireframe.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().wireframe.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    /// Wireframe half-width in screen pixels.
    #[getter]
    fn width(&self) -> f32 { self.config.borrow().wireframe.width }
    #[setter]
    fn set_width(&mut self, v: f32) { self.config.borrow_mut().wireframe.width = v; }
    /// Fade the wireframe out as a body recedes far enough that its facets
    /// stop being resolvable. **Off by default.**
    ///
    /// Past about a pixel per facet the three edges cover the whole triangle,
    /// so the mesh reads as a sheet of wireframe colour -- a shadowed body at
    /// distance comes out grey rather than black, which is the wireframe
    /// overwriting the shading rather than drawing the mesh. This fades it out
    /// between 4 px and 1 px facets instead.
    ///
    /// Distance only: the measure is the facet's *largest* screen height, so
    /// tilt does not trigger it and the limb of a sphere keeps its wireframe.
    ///
    /// Only applies to `wireframe_mode = 2`, where there is a shaded surface
    /// underneath to fade into. Mode 1 is wireframe alone and would simply
    /// vanish.
    #[getter]
    fn fade(&self) -> bool { self.config.borrow().wireframe.fade }
    #[setter]
    fn set_fade(&mut self, v: bool) { self.config.borrow_mut().wireframe.fade = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().wireframe)
    }
}

/// The picked facet and the facet labels.
///
/// `app.simulation.config.selection`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct SelectionConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl SelectionConfig {
    /// 0 shaded only, 1 wireframe only, 2 wireframe over the shaded mesh.
    ///
    /// Barycentric edge detection in the main fragment shader, so the overlay
    /// cannot z-fight. Needs a flattened mesh -- indexed meshes share vertices, so
    /// Draw each facet's index at its centre.
    ///
    /// For working out *which* facet a number in a data product refers to,
    /// without counting round a mesh by hand. Off by default, and capped by
    /// `facet_labels_max`: a label per facet is a text draw per facet, and a
    /// shape model has millions of them.
    ///
    /// Only facets turned towards the camera are labelled. The text has no
    /// depth test -- it is drawn over the frame -- so labelling the far side
    /// of a body would print numbers on top of the surface hiding them. On a
    /// concave shape, a facet behind another that faces the same way can
    /// still show through.
    #[getter]
    fn labels(&self) -> bool { self.config.borrow().selection.labels }
    #[setter]
    fn set_labels(&mut self, v: bool) { self.config.borrow_mut().selection.labels = v; }
    /// Most facets to label before giving up, per body.
    ///
    /// A guard rather than a preference: turning labels on with a 3.1M-facet
    /// body would queue three million text draws and stop the frame dead.
    #[getter]
    fn labels_max(&self) -> u32 { self.config.borrow().selection.labels_max }
    #[setter]
    fn set_labels_max(&mut self, v: u32) { self.config.borrow_mut().selection.labels_max = v; }
    /// Size of a facet label, in pixels.
    #[getter]
    fn label_size(&self) -> f32 { self.config.borrow().selection.label_size }
    #[setter]
    fn set_label_size(&mut self, v: f32) { self.config.borrow_mut().selection.label_size = v; }
    /// Colour of a facet label, `(r, g, b, a)`.
    #[getter]
    fn label_color(&self) -> [f32; 4] { self.config.borrow().selection.label_color }
    #[setter]
    fn set_label_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().selection.label_color = v; }
    /// Colour a facet takes when it is selected, `(r, g, b, a)`.
    ///
    /// Selecting writes this onto the facet's own vertices and marks them
    /// colour-mode 1, which the shader honours for that facet alone -- so a
    /// picked facet is unlit and this colour while the rest of the body keeps
    /// its shading. Deselecting puts back what was there.
    #[getter]
    fn color(&self) -> [Float; 4] {
        let c = self.config.borrow().selection.color;
        [c.r as Float, c.g as Float, c.b as Float, c.a as Float]
    }
    #[setter]
    fn set_color(&mut self, v: [Float; 4]) {
        self.config.borrow_mut().selection.color = wgpu::Color {
            r: v[0] as f64, g: v[1] as f64, b: v[2] as f64, a: v[3] as f64,
        };
    }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().selection)
    }
}

/// Colouring facets from per-facet values.
///
/// `app.simulation.config.data`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct DataConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl DataConfig {
    /// Range the colormap spans, or `None` to fit the loaded values each
    /// frame.
    ///
    /// Automatic is the sane default for exploring, but pin it for anything
    /// comparative: an auto range silently rescales between frames, so two
    /// images of the same scene are not on the same colour scale and the
    /// difference between them reads as physics rather than as bookkeeping.
    #[getter]
    fn value_min(&self) -> Option<f32> { self.config.borrow().data.value_min }
    #[setter]
    fn set_value_min(&mut self, v: Option<f32>) { self.config.borrow_mut().data.value_min = v; }
    #[getter]
    fn value_max(&self) -> Option<f32> { self.config.borrow().data.value_max }
    #[setter]
    fn set_value_max(&mut self, v: Option<f32>) { self.config.borrow_mut().data.value_max = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().data)
    }
}

/// The colour scale drawn for `data`.
///
/// `app.simulation.config.colorbar`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ColorbarConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ColorbarConfig {
    #[getter]
    fn enabled(&self) -> bool { self.config.borrow().colorbar.enabled }
    #[setter]
    fn set_enabled(&mut self, v: bool) { self.config.borrow_mut().colorbar.enabled = v; }
    #[getter]
    fn anchor(&self) -> String { self.config.borrow().colorbar.anchor.name().to_string() }
    #[setter]
    fn set_anchor(&mut self, v: &str) -> PyResult<()> {
        let a = crate::app::config::HudAnchor::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown anchor {v:?}: expected one of top-left, top-center, \
                 top-right, middle-left, middle-center, middle-right, \
                 bottom-left, bottom-center, bottom-right"
            ))
        })?;
        self.config.borrow_mut().colorbar.anchor = a;
        Ok(())
    }
    /// Inset from the anchor, pixels.
    #[getter]
    fn x(&self) -> f32 { self.config.borrow().colorbar.x }
    #[setter]
    fn set_x(&mut self, v: f32) { self.config.borrow_mut().colorbar.x = v; }
    #[getter]
    fn y(&self) -> f32 { self.config.borrow().colorbar.y }
    #[setter]
    fn set_y(&mut self, v: f32) { self.config.borrow_mut().colorbar.y = v; }
    /// Long and short axis of the bar, pixels.
    #[getter]
    fn length(&self) -> f32 { self.config.borrow().colorbar.length }
    #[setter]
    fn set_length(&mut self, v: f32) { self.config.borrow_mut().colorbar.length = v; }
    #[getter]
    fn thickness(&self) -> f32 { self.config.borrow().colorbar.thickness }
    #[setter]
    fn set_thickness(&mut self, v: f32) { self.config.borrow_mut().colorbar.thickness = v; }
    /// `None` infers from the anchor.
    #[getter]
    fn vertical(&self) -> Option<bool> { self.config.borrow().colorbar.vertical }
    #[setter]
    fn set_vertical(&mut self, v: Option<bool>) { self.config.borrow_mut().colorbar.vertical = v; }
    /// Caption, e.g. `"Surface temperature (K)"`.
    #[getter]
    fn label(&self) -> String { self.config.borrow().colorbar.label.clone() }
    #[setter]
    fn set_label(&mut self, v: &str) { self.config.borrow_mut().colorbar.label = v.to_string(); }
    /// Roughly how many numbered ticks; rounded to a readable step as the axes
    /// are.
    #[getter]
    fn ticks(&self) -> usize { self.config.borrow().colorbar.ticks }
    #[setter]
    fn set_ticks(&mut self, v: usize) { self.config.borrow_mut().colorbar.ticks = v; }
    #[getter]
    fn text_size(&self) -> f32 { self.config.borrow().colorbar.text_size }
    #[setter]
    fn set_text_size(&mut self, v: f32) { self.config.borrow_mut().colorbar.text_size = v; }
    #[getter]
    fn text_color(&self) -> [f32; 4] { self.config.borrow().colorbar.text_color }
    #[setter]
    fn set_text_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().colorbar.text_color = v; }
    /// Outline drawn around the strip, so it reads as a scale rather than as
    /// part of the scene when it sits over a dark body.
    #[getter]
    fn border(&self) -> bool { self.config.borrow().colorbar.border }
    #[setter]
    fn set_border(&mut self, v: bool) { self.config.borrow_mut().colorbar.border = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().colorbar)
    }
}

/// Reference axes, tick labels and the navigation gizmo.
///
/// `app.simulation.config.axes`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct AxesConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl AxesConfig {
    /// Reference axes drawn around the scene.
    ///
    /// `"off"`, `"box"` (MATLAB), `"panes"` (matplotlib), `"gizmo"` (three
    /// labelled arrows at the origin), `"blender"` (ground grid, Z line and
    /// gizmo). A rendered body alone carries no scale or orientation; these
    /// supply both.
    #[getter]
    fn style(&self) -> String { self.config.borrow().axes.style.name().to_string() }
    #[setter]
    fn set_style(&mut self, v: &str) -> PyResult<()> {
        let s = crate::app::axes::AxesStyle::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown axes style {v:?}: expected off, box, panes, gizmo or blender"
            ))
        })?;
        self.config.borrow_mut().axes.style = s;
        Ok(())
    }
    /// Colour of the axis lines and grid.
    #[getter]
    fn color(&self) -> [f32; 3] { self.config.borrow().axes.color }
    #[setter]
    fn set_color(&mut self, v: [f32; 3]) { self.config.borrow_mut().axes.color = v; }
    /// Roughly how many ticks per axis. The step is rounded to 1, 2 or 5
    /// times a power of ten first, so the count lands near this rather than
    /// on it -- a figure with ticks at 0.0347 is unreadable.
    #[getter]
    fn ticks(&self) -> usize { self.config.borrow().axes.ticks }
    #[setter]
    fn set_ticks(&mut self, v: usize) { self.config.borrow_mut().axes.ticks = v; }
    /// Appended to every tick label, e.g. `" km"`.
    ///
    /// The renderer knows the mesh is 0.437 across but not whether that is
    /// metres or kilometres, so the unit has to come from the script.
    #[getter]
    fn unit(&self) -> String { self.config.borrow().axes.unit.clone() }
    #[setter]
    fn set_unit(&mut self, v: &str) { self.config.borrow_mut().axes.unit = v.to_string(); }
    /// Tick label size in pixels, and their colour.
    #[getter]
    fn label_size(&self) -> f32 { self.config.borrow().axes.label_size }
    #[setter]
    fn set_label_size(&mut self, v: f32) { self.config.borrow_mut().axes.label_size = v; }
    #[getter]
    fn label_color(&self) -> [f32; 4] { self.config.borrow().axes.label_color }
    #[setter]
    fn set_label_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().axes.label_color = v; }
    /// Which corner the navigation gizmo sits in. Any of the nine HUD
    /// anchors, so it can be moved out of the way of a colour bar or a HUD.
    ///
    /// Drawn by the `"gizmo"` and `"blender"` axes styles and by no other.
    #[getter]
    fn gizmo_anchor(&self) -> String { self.config.borrow().axes.gizmo_anchor.name().to_string() }
    #[setter]
    fn set_gizmo_anchor(&mut self, v: &str) -> PyResult<()> {
        let a = crate::app::config::HudAnchor::parse(v).ok_or_else(|| {
            pyo3::exceptions::PyValueError::new_err(format!(
                "unknown anchor {v:?}: expected one of top-left, top-center, \
                 top-right, middle-left, middle-center, middle-right, \
                 bottom-left, bottom-center, bottom-right"
            ))
        })?;
        self.config.borrow_mut().axes.gizmo_anchor = a;
        Ok(())
    }
    /// Half the widget's width, in pixels: a ball centre never sits further
    /// than this from the middle.
    ///
    /// The gizmo's only size knob. Letter height follows it
    /// ([`crate::app::gizmo::label_size`]), the margin to the image edge is
    /// fixed at 20 px, and the letters are black -- each of those was settable
    /// once and none of them was worth setting: a letter is sized and coloured
    /// by the ball it sits on, so the pair could only ever agree or disagree.
    #[getter]
    fn gizmo_size(&self) -> f32 { self.config.borrow().axes.gizmo_size }
    #[setter]
    fn set_gizmo_size(&mut self, v: f32) { self.config.borrow_mut().axes.gizmo_size = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().axes)
    }
}

/// The shaded ground grid of the `blender` axes style.
///
/// `app.simulation.config.grid`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct GridConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl GridConfig {
    /// Shade the `"blender"` style's ground grid instead of drawing it as
    /// line segments. On by default; `False` restores the segments.
    ///
    /// The segments end at the scene bounds, sit at one spacing, and are one
    /// pixel wide because WebGPU has no line width. This computes the grid
    /// per pixel instead: it has no edge, it crossfades between decades as
    /// you zoom -- which is what lets one grid serve a unit cube and a body
    /// 1e4 km away -- and its lines antialias themselves.
    #[getter]
    fn enabled(&self) -> bool { self.config.borrow().grid.enabled }
    #[setter]
    fn set_enabled(&mut self, v: bool) { self.config.borrow_mut().grid.enabled = v; }
    /// Width of a grid line, in pixels.
    #[getter]
    fn width(&self) -> f32 { self.config.borrow().grid.width }
    #[setter]
    fn set_width(&mut self, v: f32) { self.config.borrow_mut().grid.width = v; }
    /// Cells between thick lines, and the factor between the levels the
    /// crossfade steps through -- the same number seen from two sides.
    #[getter]
    fn major(&self) -> u32 { self.config.borrow().grid.major }
    #[setter]
    fn set_major(&mut self, v: u32) { self.config.borrow_mut().grid.major = v; }
    /// Colour of the ordinary lines, `(r, g, b, a)`.
    #[getter]
    fn color(&self) -> [f32; 4] { self.config.borrow().grid.color }
    #[setter]
    fn set_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.color = v; }
    /// Colour of every `grid_major`-th line.
    #[getter]
    fn major_color(&self) -> [f32; 4] { self.config.borrow().grid.major_color }
    #[setter]
    fn set_major_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.major_color = v; }
    /// The axis lines, drawn over the grid so the origin reads without
    /// hunting for it. Two of the three are in the grid's plane and get
    /// drawn; which two depends on which plane that is.
    #[getter]
    fn axis_x_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_x_color }
    #[setter]
    fn set_axis_x_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_x_color = v; }
    #[getter]
    fn axis_y_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_y_color }
    #[setter]
    fn set_axis_y_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_y_color = v; }
    #[getter]
    fn axis_z_color(&self) -> [f32; 4] { self.config.borrow().grid.axis_z_color }
    #[setter]
    fn set_axis_z_color(&mut self, v: [f32; 4]) { self.config.borrow_mut().grid.axis_z_color = v; }
    /// Fade the grid out between these grazing factors: `0.0` is looking
    /// straight down at the ground plane and `1.0` is looking along it.
    /// Without it the horizon is a hard line of aliasing.
    ///
    /// On the angle rather than the distance because the plane is infinite:
    /// what bounds it on screen is the horizon, not the far plane, so a
    /// distance fade never reaches its ramp.
    #[getter]
    fn fade_near(&self) -> f32 { self.config.borrow().grid.fade_near }
    #[setter]
    fn set_fade_near(&mut self, v: f32) { self.config.borrow_mut().grid.fade_near = v; }
    #[getter]
    fn fade_far(&self) -> f32 { self.config.borrow().grid.fade_far }
    #[setter]
    fn set_fade_far(&mut self, v: f32) { self.config.borrow_mut().grid.fade_far = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().grid)
    }
}

/// The text overlays.
///
/// `app.simulation.config.hud`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct HudConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl HudConfig {
    /// Font for the HUD: a **name** or a **path**, or empty for the built-in
    /// DejaVu Sans.
    ///
    /// `"Arial"`, `"arial"`, `"Times New Roman"` and
    /// `"/Library/Fonts/Arial.ttf"` all work. Anything that exists on disk is
    /// treated as a path; anything else is looked up by name in the
    /// platform's font directories.
    ///
    /// **Matching is on the filename, not the family name inside the font.**
    /// Reading real family names needs a font-database dependency, which an
    /// overlay does not justify; filenames cover the names people type. A
    /// family whose file is named differently -- "Helvetica Neue" living in
    /// `HelveticaNeue.ttc` -- resolves, since punctuation and case are
    /// ignored, but one named nothing like its family will not.
    ///
    /// One font for all HUDs: each additional font needs its own glyph cache
    /// and draw, and per-HUD fonts are not worth that for an overlay. Per-HUD
    /// *size* is free by comparison and lives on `Hud::size`.
    ///
    /// A path that cannot be read or parsed warns once and falls back to the
    /// built-in font, rather than leaving the run with no HUD at all.
    ///
    /// Startup only: the glyph cache is built with the window.
    #[getter]
    fn font(&self) -> String { self.config.borrow().hud.font.clone() }
    #[setter]
    fn set_font(&mut self, v: &str) { self.config.borrow_mut().hud.font = v.to_string(); }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().hud)
    }
}

/// Frame export.
///
/// `app.simulation.config.export`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ExportConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ExportConfig {
    /// Encode and write each exported frame on the render thread instead of a
    /// worker pool.
    ///
    /// Slower, but the file is on disk before the frame returns -- which is what a
    /// script needs if it exports and then reads the file immediately.
    #[getter]
    fn sync(&self) -> bool { self.config.borrow().export.sync }
    #[setter]
    fn set_sync(&mut self, v: bool) { self.config.borrow_mut().export.sync = v; }
    /// How many frames may be waiting to be encoded before the render loop blocks.
    ///
    /// Unbounded, this reached 30 GB RSS growing at ~2 GB/s while only ~5.6 frames
    /// per second actually reached disk, and the loop still claimed 626 it/s --
    /// measuring queue growth rather than work done.
    #[getter]
    fn max_queued(&self) -> u32 { self.config.borrow().export.max_queued }
    #[setter]
    fn set_max_queued(&mut self, v: u32) { self.config.borrow_mut().export.max_queued = v; }
    /// Directory exported frames are written to, as `{export_dir}/{N:06}.png`.
    ///
    /// **Redirect this for any test or benchmark run.** The default is shared, so a
    /// benchmark left at it writes into whatever a real run is using, and two
    /// exporters pointed at one directory race on the startup index scan as well as
    /// on cleanup.
    #[getter]
    fn dir(&self) -> String { self.config.borrow().export.dir.clone() }
    #[setter]
    fn set_dir(&mut self, v: &str) { self.config.borrow_mut().export.dir = v.to_string(); }
    /// Burn the HUD text into exported frames as well as drawing it on screen.
    ///
    /// Off by default, and that is the right default for a data product: the
    /// HUD is drawn onto the swapchain after the scene has been copied out, so
    /// exports carry the render alone. Turn it on for a screen-capture-style
    /// movie where the run state should be visible in the frames themselves --
    /// it costs one extra text pass, on exported frames only.
    /// Burn the HUD text into exported frames as well as the window.
    ///
    /// Off by default: the HUD is drawn straight onto the swapchain after the blit,
    /// so it stays out of `render_texture` and therefore out of exports. Turning it
    /// on adds a separate pass that draws it into the exported image too.
    #[getter]
    fn hud(&self) -> bool { self.config.borrow().export.hud }
    #[setter]
    fn set_hud(&mut self, v: bool) { self.config.borrow_mut().export.hud = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().export)
    }
}

/// Mouse and keyboard sensitivities.
///
/// `app.simulation.config.controls`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ControlsConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ControlsConfig {
    /// Multiplier for WASD movement speed.
    #[getter]
    fn sensitivity_move(&self) -> Float { self.config.borrow().controls.sensitivity_move }
    #[setter]
    fn set_sensitivity_move(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_move = v; }
    /// Multiplier for mouse-look speed in WASD mode.
    #[getter]
    fn sensitivity_look(&self) -> Float { self.config.borrow().controls.sensitivity_look }
    #[setter]
    fn set_sensitivity_look(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_look = v; }
    /// Multiplier for arcball orbit speed.
    #[getter]
    fn sensitivity_rotate(&self) -> Float { self.config.borrow().controls.sensitivity_rotate }
    #[setter]
    fn set_sensitivity_rotate(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_rotate = v; }
    /// Multiplier for scroll and pinch zoom speed.
    #[getter]
    fn sensitivity_zoom(&self) -> Float { self.config.borrow().controls.sensitivity_zoom }
    #[setter]
    fn set_sensitivity_zoom(&mut self, v: Float) { self.config.borrow_mut().controls.sensitivity_zoom = v; }
    /// Treat alt + left-drag as a middle-drag, so the arcball can be orbited
    /// on hardware with no middle button. Blender calls the same setting
    /// "Emulate 3 Button Mouse". Defaults on for macOS, where a trackpad is
    /// the common case, and off elsewhere.
    /// Let `Option`/`Alt` + left-drag stand in for a middle-drag.
    ///
    /// Defaults on for macOS, matching Blender's "Emulate 3 Button Mouse". It exists
    /// because a trackpad has no middle button, which once made the arcball
    /// completely unusable there.
    #[getter]
    fn emulate_middle_button(&self) -> bool { self.config.borrow().controls.emulate_middle_button }
    #[setter]
    fn set_emulate_middle_button(&mut self, v: bool) { self.config.borrow_mut().controls.emulate_middle_button = v; }
    /// Two-finger swipe on a trackpad orbits, `shift` pans and `ctrl` zooms; off, it zooms like a wheel.
    ///
    /// Blender's default trackpad map. A trackpad is told from a wheel by
    /// what it reports -- pixels against notches -- which is how Blender
    /// tells them apart too, so a Magic Mouse counts as a trackpad here as
    /// it does there; this is the switch for it. A pinch zooms either way.
    #[getter]
    fn trackpad_orbit(&self) -> bool { self.config.borrow().controls.trackpad_orbit }
    #[setter]
    fn set_trackpad_orbit(&mut self, v: bool) { self.config.borrow_mut().controls.trackpad_orbit = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().controls)
    }
}

/// The size of the image being rendered, as distinct from the window.
///
/// `app.simulation.config.image`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct ImageConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl ImageConfig {
    /// Render size in physical pixels -- the *image*, not the window.
    ///
    /// `0` means "follow the window", which is what a terminal run wants and
    /// what every script got when there was only one pair of these. Set it to
    /// pin the render independently: a 4K export from a small window, or a
    /// fixed frame size while the editor's viewport panel is dragged about.
    ///
    /// Everything about the image follows this -- the camera's aspect ratio,
    /// where axis ticks project, where the colour bar sits, and what an
    /// exported frame measures.
    #[getter]
    fn width(&self) -> u32 { self.config.borrow().image.width }
    #[setter]
    fn set_width(&mut self, v: u32) { self.config.borrow_mut().image.width = v; }
    #[getter]
    fn height(&self) -> u32 { self.config.borrow().image.height }
    #[setter]
    fn set_height(&mut self, v: u32) { self.config.borrow_mut().image.height = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().image)
    }
}

/// Diagnostics and console output.
///
/// `app.simulation.config.debug`. Reads and writes the live config
/// through the same handle as every other view of it.
#[pyclass(unsendable)]
pub struct DebugConfig {
    pub config: Rc<RefCell<crate::app::config::Config>>,
}

#[pymethods]
impl DebugConfig {
    /// Print app lifecycle events: pause and camera-mode changes.
    #[getter]
    fn app(&self) -> bool { self.config.borrow().debug.app }
    #[setter]
    fn set_app(&mut self, v: bool) { self.config.borrow_mut().debug.app = v; }
    /// Print window and GPU setup: chosen surface format, adapter and device
    /// features, and **the present modes the surface supports**.
    ///
    /// Worth enabling once on any new machine -- it is how the vsync cap that
    /// invalidated a whole benchmark was identified.
    #[getter]
    fn window(&self) -> bool { self.config.borrow().debug.window }
    #[setter]
    fn set_window(&mut self, v: bool) { self.config.borrow_mut().debug.window = v; }
    /// Print per-mesh detail as meshes are uploaded.
    #[getter]
    fn window_mesh(&self) -> bool { self.config.borrow().debug.window_mesh }
    #[setter]
    fn set_window_mesh(&mut self, v: bool) { self.config.borrow_mut().debug.window_mesh = v; }
    /// **Does nothing.** The field exists and is settable from Python, but no code
    /// reads it. Left as a placeholder.
    #[getter]
    fn simulation(&self) -> bool { self.config.borrow().debug.simulation }
    #[setter]
    fn set_simulation(&mut self, v: bool) { self.config.borrow_mut().debug.simulation = v; }
    /// Time each GPU pass with timestamp queries, into `sim.gpu_timings()`.
    ///
    /// Off by default: the queries themselves are nearly free, but reading them
    /// back costs a buffer map per frame, and nothing needs it unless someone is
    /// asking where a frame goes. Silently inert where the adapter has no
    /// `TIMESTAMP_QUERY` -- `sim.gpu_timings()` returns an empty dict there.
    ///
    /// Draw the shadow/depth map as an overlay instead of leaving it offscreen.
    ///
    /// Only mirrors the main pass's depth at `msaa = 1`; above that the pass writes
    /// its own multisampled depth buffer and the debug view is not it.
    #[getter]
    fn gpu_timing(&self) -> bool { self.config.borrow().debug.gpu_timing }
    #[setter]
    fn set_gpu_timing(&mut self, v: bool) { self.config.borrow_mut().debug.gpu_timing = v; }
    /// Count what each body actually drew, with occlusion queries.
    ///
    /// The Visibility panel otherwise tests bounding boxes against the
    /// frustum, so "visible" means "could be seen", and a body wholly behind
    /// another still counts. This draws each body's box after the scene, with
    /// the depth test on and depth writes off, and asks the GPU how many
    /// samples survived. Zero means it put nothing on screen.
    ///
    /// Off by default: it costs a readback every frame, for a diagnostic.
    /// A box is a conservative stand-in for its body, so this can still call
    /// a body visible when only its box is -- the same direction the frustum
    /// test errs in.
    #[getter]
    fn occlusion_queries(&self) -> bool { self.config.borrow().debug.occlusion_queries }
    #[setter]
    fn set_occlusion_queries(&mut self, v: bool) { self.config.borrow_mut().debug.occlusion_queries = v; }
    #[getter]
    fn depth_show(&self) -> bool { self.config.borrow().debug.depth_show }
    #[setter]
    fn set_depth_show(&mut self, v: bool) { self.config.borrow_mut().debug.depth_show = v; }
    /// Free integer passed through to the shader, for one-off experiments.
    #[getter]
    fn extra(&self) -> u32 { self.config.borrow().debug.extra }
    #[setter]
    fn set_extra(&mut self, v: u32) { self.config.borrow_mut().debug.extra = v; }
    fn __repr__(&self) -> String {
        format!("{:?}", self.config.borrow().debug)
    }
}

/// The groups, as live views. Generated beside the group classes so a
/// group added to the struct appears here without anyone remembering.
#[pymethods]
impl super::config::Config {
    /// How the surface is coloured and the image encoded.
    #[getter]
    fn shading(&self) -> ShadingConfig { ShadingConfig { config: self.config.clone() } }
    /// The Sun as a light: its colour, the ambient floor, the debug cube.
    #[getter]
    fn light(&self) -> LightConfig { LightConfig { config: self.config.clone() } }
    /// The shadow map and its readback.
    #[getter]
    fn shadows(&self) -> ShadowsConfig { ShadowsConfig { config: self.config.clone() } }
    /// Facet edges drawn over or instead of the surface.
    #[getter]
    fn wireframe(&self) -> WireframeConfig { WireframeConfig { config: self.config.clone() } }
    /// The picked facet and the facet labels.
    #[getter]
    fn selection(&self) -> SelectionConfig { SelectionConfig { config: self.config.clone() } }
    /// Colouring facets from per-facet values.
    #[getter]
    fn data(&self) -> DataConfig { DataConfig { config: self.config.clone() } }
    /// The colour scale drawn for `data`.
    #[getter]
    fn colorbar(&self) -> ColorbarConfig { ColorbarConfig { config: self.config.clone() } }
    /// Reference axes, tick labels and the navigation gizmo.
    #[getter]
    fn axes(&self) -> AxesConfig { AxesConfig { config: self.config.clone() } }
    /// The shaded ground grid of the `blender` axes style.
    #[getter]
    fn grid(&self) -> GridConfig { GridConfig { config: self.config.clone() } }
    /// The text overlays.
    #[getter]
    fn hud(&self) -> HudConfig { HudConfig { config: self.config.clone() } }
    /// Frame export.
    #[getter]
    fn export(&self) -> ExportConfig { ExportConfig { config: self.config.clone() } }
    /// Mouse and keyboard sensitivities.
    #[getter]
    fn controls(&self) -> ControlsConfig { ControlsConfig { config: self.config.clone() } }
    /// The size of the image being rendered, as distinct from the window.
    #[getter]
    fn image(&self) -> ImageConfig { ImageConfig { config: self.config.clone() } }
    /// Diagnostics and console output.
    #[getter]
    fn debug(&self) -> DebugConfig { DebugConfig { config: self.config.clone() } }

    /// Old flat names, for one release: forwarded to the group they
    /// moved into, with a `DeprecationWarning` naming the new path.
    /// Table in `tools/config_renames.py`.
    fn __getattr__(slf: &Bound<'_, Self>, name: &str) -> PyResult<Py<PyAny>> {
        let py = slf.py();
        if let Some((group, new)) = renamed(name) {
            deprecated(py, name, group, new)?;
            return Ok(slf.getattr(group)?.getattr(new)?.unbind());
        }
        if MOVED_TO_APP.contains(&name) {
            return Err(pyo3::exceptions::PyAttributeError::new_err(format!(
                "config.{name} is a window property and moved to app.config.{name}"
            )));
        }
        Err(pyo3::exceptions::PyAttributeError::new_err(format!(
            "'Config' object has no attribute {name:?}"
        )))
    }

    /// The setter half of the shim. Anything not in the table takes the
    /// ordinary path, so the real setters on this class still run.
    fn __setattr__(slf: &Bound<'_, Self>, name: &str, value: Bound<'_, PyAny>) -> PyResult<()> {
        let py = slf.py();
        if let Some((group, new)) = renamed(name) {
            deprecated(py, name, group, new)?;
            return slf.getattr(group)?.setattr(new, value);
        }
        if MOVED_TO_APP.contains(&name) {
            return Err(pyo3::exceptions::PyAttributeError::new_err(format!(
                "config.{name} is a window property and moved to app.config.{name}"
            )));
        }
        // The generic path, by hand: calling `slf.setattr` here would come
        // straight back to this function.
        let key = pyo3::types::PyString::new(py, name);
        let rc = unsafe {
            pyo3::ffi::PyObject_GenericSetAttr(slf.as_ptr(), key.as_ptr(), value.as_ptr())
        };
        if rc == -1 {
            return Err(PyErr::fetch(py));
        }
        Ok(())
    }
}

/// Where a flat name went, if it was one.
fn renamed(name: &str) -> Option<(&'static str, &'static str)> {
    match name {
        "access_shadow_map" => Some(("shadows", "access_shadow_map")),
        "ambient_strength" => Some(("light", "ambient")),
        "axes" => Some(("axes", "style")),
        "axes_color" => Some(("axes", "color")),
        "axes_label_color" => Some(("axes", "label_color")),
        "axes_label_size" => Some(("axes", "label_size")),
        "axes_ticks" => Some(("axes", "ticks")),
        "axes_unit" => Some(("axes", "unit")),
        "background" => Some(("shading", "background")),
        "color" => Some(("shading", "color")),
        "color_mode" => Some(("shading", "color_mode")),
        "colorbar" => Some(("colorbar", "enabled")),
        "colorbar_anchor" => Some(("colorbar", "anchor")),
        "colorbar_border" => Some(("colorbar", "border")),
        "colorbar_label" => Some(("colorbar", "label")),
        "colorbar_length" => Some(("colorbar", "length")),
        "colorbar_text_color" => Some(("colorbar", "text_color")),
        "colorbar_text_size" => Some(("colorbar", "text_size")),
        "colorbar_thickness" => Some(("colorbar", "thickness")),
        "colorbar_ticks" => Some(("colorbar", "ticks")),
        "colorbar_vertical" => Some(("colorbar", "vertical")),
        "colorbar_x" => Some(("colorbar", "x")),
        "colorbar_y" => Some(("colorbar", "y")),
        "colormap" => Some(("data", "colormap")),
        "debug_app" => Some(("debug", "app")),
        "debug_depth_show" => Some(("debug", "depth_show")),
        "debug_light_cube_fit" => Some(("light", "cube_fit")),
        "debug_light_cube_show" => Some(("light", "cube_show")),
        "debug_simulation" => Some(("debug", "simulation")),
        "debug_window" => Some(("debug", "window")),
        "debug_window_mesh" => Some(("debug", "window_mesh")),
        "emulate_middle_button" => Some(("controls", "emulate_middle_button")),
        "export_dir" => Some(("export", "dir")),
        "export_hud" => Some(("export", "hud")),
        "export_max_queued" => Some(("export", "max_queued")),
        "export_sync" => Some(("export", "sync")),
        "extra" => Some(("debug", "extra")),
        "facet_label_color" => Some(("selection", "label_color")),
        "facet_label_size" => Some(("selection", "label_size")),
        "facet_labels" => Some(("selection", "labels")),
        "facet_labels_max" => Some(("selection", "labels_max")),
        "gamma" => Some(("shading", "gamma")),
        "gizmo_anchor" => Some(("axes", "gizmo_anchor")),
        "gizmo_size" => Some(("axes", "gizmo_size")),
        "gpu_timing" => Some(("debug", "gpu_timing")),
        "grid" => Some(("grid", "enabled")),
        "grid_axis_x_color" => Some(("grid", "axis_x_color")),
        "grid_axis_y_color" => Some(("grid", "axis_y_color")),
        "grid_axis_z_color" => Some(("grid", "axis_z_color")),
        "grid_color" => Some(("grid", "color")),
        "grid_fade_far" => Some(("grid", "fade_far")),
        "grid_fade_near" => Some(("grid", "fade_near")),
        "grid_major" => Some(("grid", "major")),
        "grid_major_color" => Some(("grid", "major_color")),
        "grid_width" => Some(("grid", "width")),
        "height" => Some(("image", "height")),
        "hud_font" => Some(("hud", "font")),
        "light_color" => Some(("light", "color")),
        "light_cube_scale" => Some(("light", "cube_scale")),
        "msaa" => Some(("shading", "msaa")),
        "occlusion_queries" => Some(("debug", "occlusion_queries")),
        "render_back_face" => Some(("shading", "render_back_face")),
        "selection_color" => Some(("selection", "color")),
        "sensitivity_look" => Some(("controls", "sensitivity_look")),
        "sensitivity_move" => Some(("controls", "sensitivity_move")),
        "sensitivity_rotate" => Some(("controls", "sensitivity_rotate")),
        "sensitivity_zoom" => Some(("controls", "sensitivity_zoom")),
        "shadow_bias_minimum" => Some(("shadows", "bias_minimum")),
        "shadow_bias_scale" => Some(("shadows", "bias_scale")),
        "shadow_normal_offset_scale" => Some(("shadows", "normal_offset_scale")),
        "shadow_pcf" => Some(("shadows", "pcf")),
        "shadow_per_body" => Some(("shadows", "per_body")),
        "shadow_resolution" => Some(("shadows", "resolution")),
        "srgb_mode" => Some(("shading", "srgb_mode")),
        "value_max" => Some(("data", "value_max")),
        "value_min" => Some(("data", "value_min")),
        "width" => Some(("image", "width")),
        "wireframe_color" => Some(("wireframe", "color")),
        "wireframe_fade" => Some(("wireframe", "fade")),
        "wireframe_mode" => Some(("wireframe", "mode")),
        "wireframe_width" => Some(("wireframe", "width")),
        _ => None,
    }
}

const MOVED_TO_APP: &[&str] = &["fullscreen", "title", "vsync"];

fn deprecated(py: Python<'_>, old: &str, group: &str, new: &str) -> PyResult<()> {
    let msg = std::ffi::CString::new(format!(
        "config.{old} is deprecated; use config.{group}.{new}"
    ))?;
    PyErr::warn(
        py,
        &py.get_type::<pyo3::exceptions::PyDeprecationWarning>(),
        msg.as_c_str(),
        2,
    )
}

/// The application's own settings, flat.
#[pymethods]
impl super::config::AppConfig {
    /// Draw in the editor layout: viewport panel, script, config, log.
    ///
    /// A *mode*, not a different loop. `start()` and `step()` behave exactly
    /// as they always did -- the frame simply also draws the UI, and the
    /// scene lands in the viewport panel instead of filling the window. So a
    /// script that drives its own `while app.step():` gets the editor around
    /// it without changing a line, which is the whole reason `step()` was
    /// made non-blocking.
    ///
    /// `start_editor()` is this plus `start()`.
    ///
    /// No widget: a checkbox that switches the UI off from inside the UI
    /// leaves nothing to switch it back on with.
    #[getter]
    fn editor(&self) -> bool { self.config.borrow().editor }
    #[setter]
    fn set_editor(&mut self, v: bool) { self.config.borrow_mut().editor = v; }
    /// Give the whole window to the renderer: panels out of the way, each
    /// coming back when the pointer reaches its edge.
    ///
    /// Focus on the scene, in other words. Not on the window -- that is yours
    /// to size, by double clicking its title bar or dragging a corner -- but
    /// on what is inside it. A focused renderer looks like a plain render
    /// window, with the panels a pointer-flick away: top for the toolbar,
    /// left for the script, right for the config, bottom for the log.
    ///
    /// Independent of `simulation.config.fullscreen`, which is the OS window
    /// and nothing else. Set both to be rid of everything at once; set this
    /// alone and the window stays where it is.
    #[getter]
    fn focus(&self) -> bool { self.config.borrow().focus }
    #[setter]
    fn set_focus(&mut self, v: bool) { self.config.borrow_mut().focus = v; }
    /// Open the window without taking focus, so a run can go on beside
    /// other work.
    ///
    /// A render window normally comes up *key* and pulls the keyboard away
    /// from whatever was in front of it, which is fine for one run and not
    /// fine for a script that opens a window per case. With this set the
    /// window is ordered in behind the active application instead, and
    /// nothing is typed into it by accident.
    ///
    /// **Startup only** -- it decides how the window is first shown, and how
    /// the application announces itself, neither of which can be taken back
    /// afterwards. Set it before `start()` or the first `step()`.
    ///
    /// The window is still drawn and still interactive; it simply has to be
    /// clicked before it takes the keyboard.
    ///
    /// Named at length because two shorter names were taken and both mean
    /// something else: `focus` here is the panels *inside* the window, and
    /// `simulation.config.background` is the colour the frame is cleared to.
    ///
    /// Unsupported on X11 and Wayland, where winit cannot ask for it, and the
    /// window comes up focused as before.
    ///
    /// No widget: it is read once, while the window is being created. By the
    /// time there is a panel to tick it in, the window it would have governed
    /// is already open, and a checkbox that does nothing is worse than none.
    #[getter]
    fn open_in_background(&self) -> bool { self.config.borrow().open_in_background }
    #[setter]
    fn set_open_in_background(&mut self, v: bool) { self.config.borrow_mut().open_in_background = v; }
    /// Window size in physical pixels.
    ///
    /// The *window*, not the render. `simulation.config.width` is the image
    /// inside it, and follows this unless it is set.
    #[getter]
    fn width(&self) -> u32 { self.config.borrow().width }
    #[setter]
    fn set_width(&mut self, v: u32) { self.config.borrow_mut().width = v; }
    #[getter]
    fn height(&self) -> u32 { self.config.borrow().height }
    #[setter]
    fn set_height(&mut self, v: u32) { self.config.borrow_mut().height = v; }
    /// What the editor's toolbar says beside the transport buttons.
    ///
    /// The same template as `huds`, so every placeholder works here too --
    /// `{drawn}` for the iteration on screen, `{it}` for how many have been
    /// begun, `{its}`, `{fps}`, `{ms}`, `{bodies}`, `{paused}`, `{warn}`,
    /// `{gpu}` and its per-pass forms -- and a precision may be attached, as
    /// `{fps:.1}`.
    ///
    /// Empty for a bare toolbar.
    #[getter]
    fn toolbar(&self) -> String { self.config.borrow().toolbar.clone() }
    #[setter]
    fn set_toolbar(&mut self, v: &str) { self.config.borrow_mut().toolbar = v.to_string(); }
    /// The OS window title.
    #[getter]
    fn title(&self) -> String { self.config.borrow().title.clone() }
    #[setter]
    fn set_title(&mut self, v: &str) { self.config.borrow_mut().title = v.to_string(); }
    /// Open the window in native fullscreen (borderless, current monitor).
    ///
    /// On macOS this is the same mode the green button gives -- its own
    /// Space -- which is worth knowing because it is not equivalent to a
    /// maximised window: the compositor hands out drawables differently
    /// there, and a stall that only appears fullscreen will not reproduce
    /// maximised.
    ///
    /// Startup only: applied when the window is created.
    #[getter]
    fn fullscreen(&self) -> bool { self.config.borrow().fullscreen }
    #[setter]
    fn set_fullscreen(&mut self, v: bool) { self.config.borrow_mut().fullscreen = v; }
    /// Cap the frame rate to the display refresh.
    ///
    /// **Off by default**, because a capped loop reports the monitor rather
    /// than the scene: on a 239 Hz panel the render loop measured exactly
    /// 239.46 it/s regardless of complexity, which made a 3.1M-facet scene
    /// look identical to a 100k one. That trap cost a wrong conclusion once
    /// and was worked around by hand in nine scripts, so it is the default
    /// that is wrong rather than those scripts.
    ///
    /// The price is that an idle viewer redraws as fast as it can instead of
    /// 60 times a second. Set `True` when you are looking at a scene rather
    /// than timing one.
    #[getter]
    fn vsync(&self) -> bool { self.config.borrow().vsync }
    #[setter]
    fn set_vsync(&mut self, v: bool) { self.config.borrow_mut().vsync = v; }
}

