[package]
name = "kalast_macros"
version = "0.4.0-beta"
description = "Kalast Macros"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"