[package]
name = "kalast_macros"
version = "0.1.0"
description = "Kalast Macros"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/GregoireHENRY/kalast"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", type-features = ["full", "parsing"] }
quote = "1"
proc-macro2 = "1"