# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from typing import Callable
from kalast.app.config import AppConfig
from kalast.app.simulation import Simulation

class App:
    def __init__(self) -> None:
        ...
    config: AppConfig
    """The application's own settings: window size, and panel layout and
    colours as the editor grows.

    Not the simulation's -- that is `app.simulation.config`, and it is
    where shading, shadows, axes, the colour bar and export live.
    """
    simulation: Simulation
    """The scene: bodies, camera, Sun, iteration state and HUDs."""
    def start(self) -> None:
        """Create the window and run the render loop.

        **Blocks until the window closes**, so set everything up before calling it
        and do per-frame work in `before_render`/`after_render`.

        Use `step()` instead to keep the loop in your own script.
        """
        ...
    def start_editor(self) -> None:
        """Open the editor: the renderer as one panel in a Blender-style layout.

        **Blocks until the window closes**, like `start()`, and runs the same
        loop. The difference is where the scene lands -- into an offscreen
        texture at the viewport panel's size, which the UI samples into the
        centre of the layout, rather than blitted to the swapchain.

        `start()` and `step()` are untouched by this: a script run from a
        terminal draws straight to the window as it always has.

        ```python
        app = App()
        app.simulation.load_mesh(path=..., mat=numpy.eye(4), flatten=True)
        app.start_editor()
        ```

        `python -m kalast` opens it on an empty scene.
        """
        ...
    script_runner: Callable[[str, str], None]
    """Install what the editor's `Run` button calls.

    A callable taking `(app, source, path)`. `kalast.editor.make_runner()`
    builds the standard one, which executes a script against the app it is
    handed rather than letting it construct a second.

    The app arrives as an argument rather than being captured when the
    runner is installed: a script must reach the app through a handle of
    its own, not through the object whose `start_editor` is running.
    """
    def set_script(self, path: str, source: str) -> None:
        """Put a script in the editor's buffer, and name the file it came from.

        Settable before `start_editor()`, which is when a launcher does it.
        """
        ...
    def run_script(self) -> None:
        """Run the script in the editor's buffer, as the Play button does.

        Takes effect on the next frame, and starts the simulation. Works
        before `start_editor()` as well, which is how `python -m kalast
        script.py --run` opens straight into a running scene.
        """
        ...
    def take_script_request(self) -> tuple[str, str] | None:
        """Take a script the editor's Play button has asked to run, if any.

        Returns `(path, source)` once per request, or `None`. Call it
        **between** frames and execute what comes back:

        ```python
        while app.step():
            asked = app.take_script_request()
            if asked:
                kalast.editor.run_toplevel(app, asked[1], asked[0])
        ```

        The frame cannot run a script itself: one that drives its own
        `while app.step():` would be a loop nested inside the frame it is
        trying to drive. Between frames it runs as the program it is,
        whatever shape it has.
        """
        ...
    script_requested: bool
    """Whether a run has been asked for and not yet taken.

    A peek, unlike `take_script_request`, so a script that is driving its
    own loop can notice the request without consuming it and unwind back
    to whoever owns the loop.
    """
    script_ran: bool
    """Whether the script in the editor's buffer is the one that is running.

    Drives the Play button: `False` and it runs the script, `True` and it
    is a pause toggle. A launcher that has already executed the script
    sets this, so Play does not offer to run it a second time.
    """
    def log(self, line: str) -> None:
        """Append a line to the editor's log panel, or to stdout without one."""
        ...
    def step(self) -> bool:
        """Draw one frame. Returns `False` once the window has closed.

        The alternative to `start()`: the loop stays in the script, so there
        is no callback boundary to hand state across.

        **`step()` goes in the middle of the loop body, not in the `while`
        line.**

        ```python
        sim = app.simulation
        while app.running:
            it = sim.state.iteration
            sim.bodies[0].mat = pose(et0 + it * dt)   # the before_render half
            sim.request_facet_shadow(0)

            if not app.step():
                break

            lit = sim.facet_shadow(0)                 # the after_render half
        ```

        **Where the code goes, against the callbacks.** Work written *before*
        `step()` is what `before_render` did -- it lands in the frame about to
        be drawn. Work written *after* it is what `after_render` did: the
        frame has rendered, so `facet_shadow()`, `facet_id_map()` and
        `hemicube()` answer for the scene just drawn.

        `while app.step():` is wrong, and wrong silently: it puts every line
        after the draw, so the pose you set applies to the next frame while
        the result you read describes the previous one. `while True:` is wrong
        too -- once the window closes `step()` returns at once without
        drawing, `state.iteration` stops advancing, and a loop keyed on it
        spins forever.

        Callbacks still run if set, inside the frame, so mixing the two works
        and every existing script is unaffected.

        **`step()` does not skip a paused frame.** It draws and returns `True`
        as usual, since the window must stay responsive to the key that
        unpauses it; what it does not do is advance `state.iteration` or run
        the callbacks. A driven loop that should also idle when paused has to
        check `sim.state.is_paused` itself.

        One call is one frame. The first is slower than the rest -- it creates
        the window and configures the surface.

        Not usable after `start()`: a platform event loop cannot be created
        twice in one process, and `start()` consumes it. Pick one.
        """
        ...
    def close(self) -> None:
        """Ask the window to close, ending a `while app.step():` loop.

        Takes effect on the next `step()`, not immediately: closing runs the
        same shutdown the window button does, which includes flushing every
        queued frame export to disk.
        """
        ...
    running: bool
    """Whether the window is still open."""
    before_render: Callable[[App, float], None]
    """Runs before each frame is drawn. Set body transforms, camera and
    sun here.

    Called as `f(app, dt)`. `dt` is the **wall-clock time since the last
    frame**, in seconds -- not a simulation step, so integrating physics
    with it ties the result to the frame rate.

    **Annotate the parameter** -- `def before_render(app: App, dt: float)`
    -- or an editor has no way to know what `app` is and completes nothing
    inside the body.

    ```python
    def before_render(app: App, dt: float) -> None:
        sim = app.simulation
        sim.huds[0].text = f"it={sim.state.iteration}  {dt * 1e3:.1f} ms"
        sim.bodies[0].mat = pos_mat("MARS", "IAU_MARS", et0 + sim.state.iteration * step)
    ```
    """
    tick: Callable[[App, float], None]
    """Alias for `before_render`, kept because it is what every example and
    existing script uses.
    """
    after_render: Callable[[App, float], None]
    """Runs after each frame is drawn, when GPU results for that frame
    exist -- `sim.facet_shadow()` is only filled in once the shadow map
    holds this frame's geometry, so this is where to consume it without
    a one-frame lag.

    Scene changes made here apply to the *next* frame, and heavy CPU work
    here blocks the render loop (fine for a simulation run, but frame
    rate stops meaning much).

    Called as `f(app, dt)`, same shape as `before_render`.
    """

