# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.app.config import Config
from kalast.app.simulation import Simulation

class App:
    def __init__(self) -> None:
        ...
    config: Config
    """Renderer and window settings. See `CONFIG.md`."""
    simulation: Simulation
    """The scene: bodies, camera, Sun, iteration state and HUDs."""
    def start(self) -> None:
        """Create the window and run the render loop.

        **Blocks until the window closes**, so set everything up before calling it
        and do per-frame work in `before_render`/`after_render`.
        """
        ...
    before_render: object
    """Runs before each frame is drawn. Set body transforms, camera and
    sun here.
    """
    tick: object
    """Alias for `before_render`, kept because it is what every example and
    existing script uses.
    """
    after_render: object
    """Runs after each frame is drawn, when GPU results for that frame
    exist -- `sim.facet_shadow()` is only filled in once the shadow map
    holds this frame's geometry, so this is where to consume it without
    a one-frame lag.

    Scene changes made here apply to the *next* frame, and heavy CPU work
    here blocks the render loop (fine for a simulation run, but frame
    rate stops meaning much).
    """

