# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class App:
    def __init__(self) -> None:
        ...
    config: Config
    get_simulation: Simulation
    def start(self) -> None:
        ...

