# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.mesh import Mesh

class Body:
    mat: numpy.object
    mesh: Mesh | None

