# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from typing import Sequence
from kalast.scattering import Atmosphere
from kalast.scattering import Hapke
from kalast.scattering import LommelSeeligerLambert
from kalast.mesh import Mesh

class Body:
    """One body of the scene: where it is, `mat`, and its shape model, `mesh`.

    A handle onto the live scene rather than a copy, so what is written
    through it moves the body from the next frame. The mesh has the rest --
    facets, positions, colours, per-facet data: `help(body.mesh)`.
    """
    @property
    def mat(self) -> numpy.ndarray:
        """The model matrix, 4x4, from the body's own frame to the world's.

        A view onto the live matrix, so `body.mat[:3, 3] = p` moves the body
        and `body.mat[:3, :3] = r` turns it; a whole 4x4 can be assigned too.
        """
        ...
    @mat.setter
    def mat(self, value: Sequence[Sequence[float] | numpy.ndarray] | numpy.ndarray) -> None: ...
    scattering: Hapke | LommelSeeligerLambert | None
    """How the surface reflects sunlight in the image: `None`, the default,
    for Lambert, or a law from `kalast.scattering` -- `Hapke(...)` or
    `LommelSeeligerLambert(...)`.

    Lambert makes a lit pixel `exposure * colour * cos(i)`. A law makes it
    `exposure * colour * pi * r(i, e, alpha) * cos(i)`: the I/F the law
    gives, scaled by the facet's colour. So with a law, leave the colours
    at 1 for the law's own albedo, or set them to a map relative to it.

    ```python
    from kalast.scattering import Hapke
    deimos.scattering = Hapke(w=0.068, b=0.275, c=1.0, b0=2.14, h=0.065, theta_bar=0.339)
    ```

    Reading gives a copy: assign a new law to change it.
    """
    atmosphere: Atmosphere | None
    """A dusty atmosphere over the surface, as the camera sees it: `None`,
    the default, for the bare surface, or `kalast.scattering.Atmosphere`.

    A pixel is then the dust's own light, scattered once and many times,
    plus the surface seen through the dust, lit by the beam that got
    through -- where the shadow map lets it -- and by the sky. Its colour
    is the surface's Lambert albedo for the sky's light, and with
    `scattering` set, the law still reflects the beam. The planet is
    taken as a sphere about the body's centre, `radius` in the scene's
    units: the defaults are Mars's, in km, at 655 nm in a clear season.

    ```python
    from kalast.scattering import Atmosphere
    mars.atmosphere = Atmosphere(tau=0.45)
    ```

    Reading gives a copy: assign a new one to change it.
    """
    horizon_map: bool
    """The body's own shadows from a horizon map, worked out once on the GPU,
    rather than from drawing it into its own shadow layer every frame:
    `False` by default.

    For each facet, how high the terrain rises in 32 directions; a facet
    is lit where the Sun stands above its horizon, and with the Sun a disc
    (`light.sun_as_point = False`) by the part of the disc above it. The
    body's layer then holds only the other bodies that can shadow it.
    Faster for a large body seen whole -- Mars's 12.9M facets at AFC's
    closest approach -- at the price of a few seconds when it is first
    turned on and 64 bytes a facet on the GPU. Its shadows are a facet's:
    a facet is lit or not as its centre is, where the shadow map's edges
    cross facets. For a body each direction from whose centre crosses its
    surface once -- a planet, most asteroids -- in its own frame, z its
    spin axis.

    ```python
    mars.horizon_map = True
    ```
    """
    mesh: Mesh
    """The shape model the renderer draws: facets, positions, colours and
    per-facet data -- `help(body.mesh)` for all of it.

    Every body a script loads or adds has one. A body built without one,
    which only Rust can do, raises `AttributeError` -- so that
    `getattr(body, "mesh", None)` still asks -- rather than giving `None`,
    which typed every `body.mesh.values = ...` as an error in the editor.
    """

