# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Hud:
    """One HUD overlay: a template, a corner, and how it looks.

    ```python
    kalast.app.Hud("{it}/{nit}")                       # top-left, the default
    kalast.app.Hud("{fps} fps", anchor="bottom-right")
    kalast.app.Hud("{hud}", x=200, y=120, size=24.0)  # absolute, no anchor needed
    ```
    """
    def __init__(self, text: str, anchor: str, x: float | None, y: float | None, size: float, color: list[float] | None, align_h: str | None, align_v: str | None) -> None:
        ...
    text: str
    """The template drawn for this HUD. See `Config::huds` for placeholders."""
    pin: str | None
    """Used in place of `text` while it is set, whatever `text` says.

    For taking a HUD off a script and giving it to a person. A callback
    that assigns `text` every iteration owns it completely, and a driven
    script goes on assigning even while paused -- pausing stops the
    iteration counter, not a `while` loop the script owns -- so there is
    nowhere else for an edit to stand.

    Typing in the editor's HUDs section sets it; its release button, or
    `None` here, gives the HUD back.
    """
    anchor: str
    """Which corner `x`/`y` are measured from: `top-left`, `top-right`,
    `bottom-left` or `bottom-right`.
    """
    x: float
    """Inset from the anchor in pixels. With the default top-left anchor
    this is simply the position, since that anchor is the origin.
    """
    y: float
    """Vertical inset from the anchor, in pixels.

    With the default top-left anchor this is simply the distance from the top.
    """
    size: float
    """Font size in pixels."""
    color: list[float]
    """Text colour, `(r, g, b, a)`."""

class AppConfig:
    """Settings for the application: the window now, panels and colours later.

    Separate from `simulation.config` because they answer different
    questions -- this one about the program you are looking at, that one about
    the thing being simulated.
    """
    editor: bool
    """Draw in the editor layout: viewport panel, script, config, log.

    A mode, not a different loop. Turn it on and `start()` or
    `while app.step():` draws the UI around the scene, unchanged
    otherwise -- which is what `step()` being non-blocking was for.
    """
    focus: bool
    """Give the whole window to the renderer: panels out of the way, each
    coming back when the pointer reaches its edge.

    About what is *inside* the window, not the window itself -- that is
    still yours to size. Independent of `simulation.config.fullscreen`.
    """
    open_in_background: bool
    """Open the window without taking focus, so a run can go on beside other
    work.

    A render window normally comes up key and pulls the keyboard away from
    whatever was in front of it. With this set it is ordered in behind the
    active application instead: still drawn, still interactive, but it has
    to be clicked before it takes the keyboard.

    **Startup only.** It decides how the window is first shown and how the
    application announces itself, so set it before `start()` or the first
    `step()`. Unrelated to `focus`, which is about the panels *inside* the
    window.

    Unsupported on X11 and Wayland; the window comes up focused there.
    """
    width: int
    """Window width in physical pixels.

    The *window*. `simulation.config.width` is the image inside it, and
    follows this unless it is set.
    """
    height: int
    """Window height in physical pixels."""
    toolbar: str
    """What the editor's toolbar says beside the transport buttons.

    The same template as `simulation.config.huds`, so every placeholder
    works here too -- `{drawn}` for the iteration on screen, `{it}` for
    how many have been begun, `{its}`, `{fps}`, `{ms}`, `{bodies}`,
    `{paused}`, `{warn}`, `{gpu}` -- and a precision may be attached, as
    `{fps:.1}`. Empty for a bare toolbar.
    """

class Config:
    debug_app: bool
    """Print app lifecycle events: pause and camera-mode changes."""
    debug_window: bool
    """Print window and GPU setup: chosen surface format, adapter and device
    features, and **the present modes the surface supports**.

    Worth enabling once on any new machine -- it is how the vsync cap that
    invalidated a whole benchmark was identified.
    """
    debug_window_mesh: bool
    """Print per-mesh detail as meshes are uploaded."""
    debug_simulation: bool
    """**Does nothing.** The field exists and is settable from Python, but no code
    reads it. Left as a placeholder.
    """
    debug_depth_show: bool
    debug_light_cube_show: bool
    """Draw a cube at the light's position, so the Sun is visible.

    Size comes from `light_cube_scale`. `debug_light_cube_fit` is on by
    default, which is what makes it *visible* rather than merely drawn:
    the camera's far plane is fitted to the bodies, and the Sun is well
    outside them.
    """
    debug_light_cube_fit: bool
    """Fit the camera's frustum around the light cube too, not just the
    bodies.

    What makes `debug_light_cube_show` show something, so it defaults to
    **on**: without it the Sun sits past the fitted far plane and is
    clipped away, and asking to see the light and being shown nothing is
    not a useful default. Nothing happens either way unless the cube is
    being drawn.

    Turn it off to keep the frustum fitted to the geometry being studied
    while the cube is on -- for a figure where the cube is out of frame
    but the framing must not change.

    The **camera** only. The light's own frustum stays fitted to the
    bodies, because it is what the shadow map covers: stretching it to the
    Sun would spend the whole map on empty space and leave the bodies a
    few texels across.

    Costs the depth range: a far plane at the Sun rather than at the
    body's edge is a much longer near-to-far span, so depth precision
    drops. For looking at where the light is, not for a figure.
    """
    title: str
    """The OS window title."""
    width: int
    """Render size in physical pixels -- the *image*, not the window.

    `0` means "follow the window", which is what a terminal run wants and
    what every script got when there was only one pair of these. Set it to
    pin the render independently: a 4K export from a small window, or a
    fixed frame size while the editor's viewport panel is dragged about.

    Everything about the image follows this -- the camera's aspect ratio,
    where axis ticks project, where the colour bar sits, and what an
    exported frame measures.
    :label: image width
    :range: 0..=7680
    """
    height: int
    """:label: image height
    :range: 0..=4320
    """
    background: list[float]
    """Colour the frame is cleared to, `(r, g, b, a)`.

    Accepts any 4-element sequence: tuple, list or `numpy.array`.
    """
    hud_font: str
    """Font for every HUD: a name (`"Arial"`) or a path, or empty for the
    built-in. One that will not resolve warns and falls back. Startup only.
    """
    huds: list[Hud]
    """The on-screen HUDs. Empty (the default) draws none.

    An alias for `app.simulation.huds`, not a second list: they are the
    same storage, so declaring them here and editing them there in
    `before_render` cannot drift apart. The objects handed back are the
    live ones -- setting `.text` on one takes effect on the next frame
    with no list to reassign.
    """
    fullscreen: bool
    """Native fullscreen at startup. See `Config::fullscreen`."""
    render_back_face: bool
    """Draw triangles facing away from the camera.

    Leave it off for closed shape models -- back faces are invisible there, so
    culling them is free performance. Measured on the full-resolution
    Didymos/Dimorphos meshes: culled against unculled differs in 5 pixels of
    1,040,400, all on silhouette edges.

    Turn it on for geometry that is *not* closed -- open craters, clipped
    sections, single-sided surfaces -- where the inside of the shell must be
    visible from outside. Note the shading is single-sided regardless: normals
    are not flipped for back faces, so an underside is lit as though it were the
    top.

    The shadow pass stays unculled either way, so open geometry still casts
    correctly from whichever side faces the light.
    """
    sensitivity_move: float
    """Multiplier for WASD movement speed.
    :range: 0.1..=5.0
    """
    sensitivity_look: float
    """Multiplier for mouse-look speed in WASD mode.
    :range: 0.1..=5.0
    """
    sensitivity_rotate: float
    """Multiplier for arcball orbit speed.
    :range: 0.1..=5.0
    """
    sensitivity_zoom: float
    """Multiplier for scroll and pinch zoom speed.
    :range: 0.1..=5.0
    """
    color: list[float]
    """Flat colour used when `color_mode` is 2, `(r, g, b, a)`."""
    color_mode: int
    """What the fragment shader outputs.

    | | |
    |---|---|
    | 0 | vertex/instance colour, lit, with shadows (the default) |
    | 1 | raw vertex/instance colour, no lighting |
    | 2 | the flat `color` |
    | 3 | as 0 but with shadows disabled |
    :range: 0..=3
    """
    extra: int
    """Free integer passed through to the shader, for one-off experiments.
    :range: 0..=10
    """
    srgb_mode: int
    """0 converts sRGB to linear before shading; 1 treats colours as already
    linear.
    :range: 0..=2
    """
    gamma: float
    """Exponent used by the sRGB conversion when `srgb_mode` is 0.
    :range: 0.1..=4.0
    """
    ambient_strength: float
    """Light added to every fragment regardless of shadowing.

    Deliberately tiny by default: a shadowed facet on an airless body receives
    almost nothing, and a visible ambient term would be inventing light that is
    not there.
    :range: 0.0..=1.0
    """
    light_color: list[float]
    """Colour of the Sun, `(r, g, b, a)`."""
    light_cube_scale: float
    """Size of the debug light cube, in world units.

    Only drawn when `debug_light_cube_show` is on.
    :range: 0.0..=5.0
    """
    msaa: int
    """Multisample anti-aliasing on the main pass: 1 (off), 2, 4 or 8.
    Takes effect when the window is created, so set it before `App.start`.
    """
    shadow_resolution: int
    """Side length of each square shadow map, in texels.

    The array is always allocated at all 8 layers, so the cost is
    `resolution^2 x 4 bytes x 8` -- 2.1 GB at the default 8192, 8.6 GB at 16384.
    Dropping to 2048 is the first thing to try when VRAM is tight or interactive
    frame times matter.

    It also feeds the automatic bias, which is expressed relative to one texel,
    so changing it changes the shadow bias with it.
    :range: 512..=16384
    """
    shadow_bias_scale: float | None
    """Slope-dependent term of the depth-comparison bias. `None` fits it per
    frame. Combined in the shader as
    `max(shadow_bias_scale * k, shadow_bias_minimum)`.

    See `shadow_normal_offset_scale` for why pinning is discouraged.
    """
    shadow_bias_minimum: float | None
    """Floor on the depth-comparison bias, for surfaces facing the light
    head-on. `None` fits it per frame.

    Measured to be the *ineffective* knob for the crater-floor PCF leak --
    auto, 1e-4 and 1e-3 all gave identical results, while the normal offset
    moved it 9x. Reach for that one first.
    """
    shadow_normal_offset_scale: float | None
    """Push the sample along the surface normal before the shadow lookup, in
    world units. `None` fits it per frame from the layer's own texel size.

    Scaled by the PCF kernel radius, since an N-radius kernel reaches N
    texels away and a one-texel offset would let those taps flip.

    Pinning it is now worse than leaving it automatic: with per-body shadow
    layers a pinned value replaces the fitted one on *every* layer, and
    those differ by the ratio of the bodies' sizes -- 403x between Mars and
    Deimos in the same scene.
    """
    wireframe_mode: int
    """the barycentrics are meaningless and the CPU side warns once.
    :range: 0..=2
    """
    wireframe_width: float
    """Wireframe half-width in screen pixels.
    :range: 0.1..=10.0
    """
    wireframe_color: list[float]
    """Wireframe colour, `(r, g, b, a)`; alpha is dropped.

    Mode 2 blends by edge coverage and is antialiased; mode 1 thresholds instead,
    because the pipeline blend state is REPLACE and a fractional alpha would be
    ignored.
    """
    gpu_timing: bool
    """Colour a picked facet takes, `(r, g, b, a)`.

    Applies to the *next* selection: facets already picked keep the colour
    they were given, because selecting writes it onto their vertices.
    Time each GPU pass, into `sim.gpu_timings()`.

    Off by default: the queries are nearly free but the readback is not,
    and nothing needs it unless someone is asking where a frame goes.
    """
    occlusion_queries: bool
    """Count what each body actually drew, with occlusion queries.

    The Visibility panel otherwise reports what the *frustum* can see, so a
    body wholly behind another still counts. With this on it also reports
    what put samples on screen. Off by default: it is a readback every
    frame for a diagnostic.

    A bounding box stands in for its body, so this can call a body visible
    when only its box is -- conservative in the same direction the frustum
    test already is.
    """
    selection_color: list[float]
    """Colour a facet takes when it is selected, `(r, g, b, a)`.

    Selecting writes this onto the facet's own vertices and marks them
    colour-mode 1, which the shader honours for that facet alone -- so a
    picked facet is unlit and this colour while the rest of the body keeps
    its shading. Deselecting puts back what was there.

    :group: Selection
    """
    shadow_pcf: int
    """Percentage-closer-filtering kernel *radius*: 0 is a single hardware 2x2
    comparison, N is a `(2N+1)^2` grid averaged.

    Cost grows quadratically and is per-fragment, so it scales with pixel count:
    `shadow_pcf = 4` costs +2.5 ms at 800x600 and +7.8 ms at 3024x1964. Benchmark
    it at the resolution you actually run.

    The normal offset scales with this, since an N-radius kernel reaches N texels
    away and a one-texel offset would let those taps flip. `shadow_pcf = 0` is
    bit-identical to the pre-scaling behaviour.
    :range: 0..=16
    """
    vsync: bool
    """Cap the frame rate to the display refresh.

    **Set this to `False` for any performance measurement.** With it on, a GPU
    faster than the display simply reports the refresh rate: a 239 Hz panel
    measured exactly 239.46 it/s regardless of scene complexity, which made a
    3.1M-facet scene look identical to a 100k one.
    """
    export_sync: bool
    """Encode and write each exported frame on the render thread instead of a
    worker pool.

    Slower, but the file is on disk before the frame returns -- which is what a
    script needs if it exports and then reads the file immediately.
    """
    export_max_queued: int
    """How many frames may be waiting to be encoded before the render loop blocks.

    Unbounded, this reached 30 GB RSS growing at ~2 GB/s while only ~5.6 frames
    per second actually reached disk, and the loop still claimed 626 it/s --
    measuring queue growth rather than work done.
    :range: 1..=512
    """
    emulate_middle_button: bool
    """Treat alt + left-drag as a middle-drag, so the arcball can be orbited
    on hardware with no middle button. Blender calls the same setting
    "Emulate 3 Button Mouse". Defaults on for macOS, where a trackpad is
    the common case, and off elsewhere.
    Let `Option`/`Alt` + left-drag stand in for a middle-drag.

    Defaults on for macOS, matching Blender's "Emulate 3 Button Mouse". It exists
    because a trackpad has no middle button, which once made the arcball
    completely unusable there.
    """
    access_shadow_map: bool
    """Read the shadow map back per facet: computes solar occlusion for every
    body each frame, readable from `after_render` via
    `Simulation::facet_shadow`.

    Off by default because it is not free: the query costs ~1.6 ms per
    body at 100k facets and ~7.3 ms at 3.1M, dominated by the blocking
    readback. Turn it on for thermophysical or radiance work; leave it off
    when you only want images.
    Compute per-facet solar occlusion for every body, every frame.

    Read it back with `sim.facet_shadow(body)` from `after_render`. Leave it off
    unless something consumes it: it is a compute pass and a readback per frame.
    """
    colorbar: bool
    """Draw the colour scale. Off by default."""
    colorbar_anchor: str
    """Which of the nine anchors the bar sits at.

    Orientation follows: `middle-left`/`middle-right` give a vertical bar,
    anything else horizontal. Override with `colorbar_vertical`.
    """
    colorbar_vertical: bool | None
    """Force the orientation, or `None` to follow the anchor."""
    colorbar_label: str
    """Caption above the bar, e.g. `"Surface temperature (K)"`."""
    colorbar_length: float
    """Long axis of the bar, pixels."""
    colorbar_thickness: float
    """Short axis of the bar, pixels."""
    colorbar_x: float
    """Inset from the anchor, pixels."""
    colorbar_y: float
    """Inset from the anchor, pixels."""
    colorbar_ticks: int
    """Roughly how many numbered ticks, rounded to a readable step."""
    colorbar_text_size: float
    """Tick and caption size in pixels."""
    colorbar_text_color: list[float]
    """Tick and caption colour, `(r, g, b, a)`."""
    colorbar_border: bool
    """Outline drawn around the strip, so it reads as a scale rather than as
    part of the scene when it sits over a dark body.
    """
    grid: bool
    """Reference axes: `"off"`, `"box"` (MATLAB), `"panes"` (matplotlib),
    `"gizmo"` (three labelled arrows at the origin) or `"blender"`
    Shade the `"blender"` grid instead of drawing it as line segments.
    """
    grid_width: float
    """Width of a grid line, pixels."""
    grid_major: int
    """Cells between thick lines."""
    grid_color: list[float]
    """Ordinary grid line colour, `(r, g, b, a)`."""
    grid_major_color: list[float]
    """Thick line colour."""
    grid_axis_x_color: list[float]
    """The X axis line drawn over the grid."""
    grid_axis_y_color: list[float]
    """The Y axis line drawn over the grid."""
    grid_fade_near: float
    """Where the fade to nothing begins, as a fraction of the far plane."""
    grid_fade_far: float
    """Where it reaches nothing."""
    axes: str
    """(ground grid, Z line and gizmo)."""
    gizmo_anchor: str
    """Which corner the navigation gizmo sits in: any of the nine HUD
    anchor names.
    """
    gizmo_size: float
    """Half the navigation gizmo's width, in pixels."""
    gizmo_margin: float
    """Gap between the gizmo and the edge of the image, in pixels."""
    gizmo_label_size: float
    """Size of the `X`, `Y`, `Z` letters on the gizmo, in pixels."""
    gizmo_label_color: list[float]
    """Colour of the gizmo's letters, `(r, g, b, a)`."""
    axes_color: list[float]
    """Colour of the axis lines and grid, `(r, g, b)`."""
    axes_ticks: int
    """Roughly how many ticks per axis.

    Approximate on purpose: the step is rounded to 1, 2 or 5 times a power
    of ten, so the count lands near this rather than on it. Ticks at
    0.0347 would hit the number exactly and be unreadable.
    """
    axes_unit: str
    """Appended to every tick label, e.g. `" km"`.

    The renderer knows the mesh is 0.437 across but not whether that is
    metres or kilometres, so the unit has to come from here.
    """
    axes_label_size: float
    """Tick label size in pixels."""
    facet_labels: bool
    """Draw each facet's index at its centre.

    For working out which facet a number in a data product refers to.
    Capped by `facet_labels_max`, and only facets turned towards the
    camera are labelled -- the text has no depth test, so labelling the
    far side would print numbers over the surface hiding them.
    """
    facet_labels_max: int
    """Most facets to label before giving up, per body. A guard: a label is a
    text draw, and a shape model has millions of facets.
    """
    facet_label_size: float
    """Facet label size, in pixels."""
    facet_label_color: list[float]
    """Facet label colour, `(r, g, b, a)`."""
    axes_label_color: list[float]
    """Tick label colour, `(r, g, b, a)`."""
    value_min: float | None
    """Bottom of the colour scale, or `None` to fit the data each frame.

    **Pin it for anything comparative.** An automatic range rescales
    between frames, so two images of the same scene are not on the same
    scale and the difference reads as physics rather than bookkeeping.
    """
    value_max: float | None
    """Top of the colour scale, or `None` to fit the data. See `value_min`."""
    colormap: numpy.object
    """Colour lookup table: a built-in name or an Nx3 array of RGB in 0..1.

    `"viridis"`, `"inferno"`, `"turbo"`, `"grey"`, or any matplotlib
    colormap passed straight through:

        app.config.colormap = matplotlib.colormaps["magma"](numpy.linspace(0, 1, 256))[:, :3]

    Resampled to 256 entries, so any length works.
    The colour table in use, as a 256x3 array.
    """
    export_hud: bool
    """Burn the HUD text into exported frames as well as drawing it on screen.

    Off by default, and that is the right default for a data product: the
    HUD is drawn onto the swapchain after the scene has been copied out, so
    exports carry the render alone. Turn it on for a screen-capture-style
    movie where the run state should be visible in the frames themselves --
    it costs one extra text pass, on exported frames only.
    Burn the HUD text into exported frames as well as the window.

    Off by default: the HUD is drawn straight onto the swapchain after the blit,
    so it stays out of `render_texture` and therefore out of exports. Turning it
    on adds a separate pass that draws it into the exported image too.
    """
    shadow_per_body: bool
    """Fit a shadow map per body instead of one fitted to the whole scene.

    On by default, because one shared map is fitted to the scene's extent
    and a small body beside a large one then gets almost no texels -- 6 km
    Deimos next to 3,396 km Mars is the case that forced this. Each layer
    is aimed at its own body and sized to it, while its depth range still
    spans the scene, so mutual shadowing is unaffected: anything between
    the Sun and a body still casts into that body's layer.

    Costs one shadow pass per body. Turn it off to get the old single
    scene-fitted map back, which is only worth doing to reproduce older
    output or when every body is a similar size.
    """
    export_dir: str
    """Directory exported frames are written to, as `{export_dir}/{N:06}.png`.

    **Redirect this for any test or benchmark run.** The default is shared, so a
    benchmark left at it writes into whatever a real run is using, and two
    exporters pointed at one directory race on the startup index scan as well as
    on cleanup.
    """

