# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class Hud:
    def __init__(self, object: str, object: str, object: float | None, object: float | None, object: float, object: list[float] | None) -> None:
        ...
    text: str
    anchor: str
    x: float
    y: float
    size: float
    color: list[float]

class Config:
    debug_app: bool
    debug_window: bool
    debug_window_mesh: bool
    debug_simulation: bool
    debug_depth_show: bool
    debug_light_cube_show: bool
    title: str
    width: int
    height: int
    background: list[float]
    hud_font: str
    huds: list[Hud]
    fullscreen: bool
    render_back_face: bool
    sensitivity_move: float
    sensitivity_look: float
    sensitivity_rotate: float
    sensitivity_zoom: float
    color: list[float]
    color_mode: int
    extra: int
    srgb_mode: int
    gamma: float
    ambient_strength: float
    light_color: list[float]
    light_cube_scale: float
    msaa: int
    shadow_resolution: int
    shadow_bias_scale: float | None
    shadow_bias_minimum: float | None
    shadow_normal_offset_scale: float | None
    wireframe_mode: int
    wireframe_width: float
    wireframe_color: list[float]
    shadow_pcf: int
    vsync: bool
    export_sync: bool
    export_max_queued: int
    emulate_middle_button: bool
    access_shadow_map: bool
    export_hud: bool
    shadow_per_body: bool
    export_dir: str

