# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from typing import Sequence

class InstanceInput:
    def __init__(self, mat: object = ...) -> None:
        ...
    mat: numpy.ndarray
    def set_mat(self, arr: Sequence[Sequence[float] | numpy.ndarray] | numpy.ndarray) -> None:
        ...
    def compute_normal(self) -> None:
        ...

