# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class InstanceInput:
    def __init__(self, mat: object, numpy: numpy.ndarray) -> None:
        ...
    mat: numpy.ndarray
    def set_mat(self, arr: list[list[float]]) -> None:
        ...
    def compute_normal(self) -> None:
        ...

