# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401

class InstanceInput:
    def __init__(self, object: object, numpy: numpy.object) -> None:
        ...
    mat: numpy.object
    def set_mat(self, object: list[list[float]]) -> None:
        ...
    def compute_normal(self) -> None:
        ...

