# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from typing import Sequence
from kalast.app.body import Body
from kalast.app.config import Config
from kalast.app.frame import Eye
from kalast.app.config import Hud
from kalast.mesh import Mesh

class Simulation:
    def reset(self) -> None:
        """Empty the scene: bodies, HUDs, the iteration counter and any pending
        GPU request.

        What the editor calls before running a script, because `load_mesh`
        appends -- run a script twice without it and its meshes are loaded
        twice.

        The config survives, deliberately: it is what the script sets on its
        way through *and* what the panel edits by hand. Running a *different*
        script in the UI app starts from a new app's config, camera and Sun
        as well.
        """
        ...
    def frame_all(self) -> None:
        """Point the camera and the Sun at everything loaded: Blender's default
        view and light, backed off until the whole scene fits.
        """
        ...
    config: Config
    """Every setting: shading, shadows, axes, colour bar, export, window.
    See `CONFIG.md`.
    """
    state: State
    """Iteration counter and pause state."""
    bodies: list[Body]
    """The loaded bodies, in load order.

    Set `bodies[i].mat` to place one: the 4x4 model matrix carries both
    orientation and position.
    """
    camera: Eye
    """The camera."""
    sun: Eye
    """The Sun.

    Only `pos` matters for lighting: since per-body shadow layers, each layer
    aims itself from `sun.pos` at the body it covers, so `dir` and `anchor` are
    not consulted.
    """
    def load_mesh(self, path: str, mat: Sequence[Sequence[float] | numpy.ndarray] | numpy.ndarray | None = ..., smooth: bool = ..., shadow_path: str | None = ..., flatten: bool | None = ...) -> None:
        """Meshes load *flat* -- each facet owning its three vertices -- which is
        what per-facet data, the wireframe overlay and the facet index map
        need. `smooth=True` keeps the file's shared vertices instead, for a
        smooth-shaded surface. `flatten=` is the old spelling, accepted for a
        release with a `DeprecationWarning`.

        `shadow_path` optionally names a lower-resolution mesh to render into
        the shadow map in place of `path`. The shadow map only decides which
        fragments are lit, so a coarser occluder buys performance without
        touching per-facet science data -- unlike loading a coarser `path`,
        which would invalidate facet-indexed results. Omit it (the default)
        to shadow with the main mesh.

        `mat` is the body's starting pose -- its `mat` -- and leaves the
        vertices as the file has them: a loop that sets `bod.mat` replaces
        it. To reshape the body, flattened along its pole say, scale
        `mesh.positions` and call `mesh.recompute_facets()`.
        """
        ...
    def add_mesh(self, mesh: Mesh, mat: Sequence[Sequence[float] | numpy.ndarray] | numpy.ndarray | None = ...) -> None:
        """Add an already-built `Mesh`, rather than loading one from a path."""
        ...
    def remove_body(self, index: int) -> None:
        """Take a body out of the scene, by index.

        The bodies after it shift down, so an index held across this call
        means a different body -- including `camera.anchor_body`, which is
        followed by index and will quietly follow its neighbour.

        There was no way to do this from a script at all: `bodies` hands back
        fresh wrappers, so removing from that list removes from a copy, and
        the only route was `reset()` and loading everything again.
        """
        ...
    def rebuild_meshes(self) -> None:
        """Rebuild the GPU buffers from the meshes on the next frame.

        Call after changing a mesh's *shape* rather than its placement --
        `mesh.flatten()`, `mesh.smoothen()`, replacing its vertices. The
        buffers are built from the meshes once and thereafter only the
        transforms are re-uploaded, so without this the render goes on
        showing the geometry as it was, with no error to say so.

        Moving a body needs nothing: `body.mat` is uploaded every frame.
        Colours have their own, cheaper route in `mesh.update_gpu_colors()`.
        """
        ...
    rays: bool
    """Whether the per-facet shadows (`facet_shadow`) are traced with rays:
    `config.shadows.rays` on and the GPU able to trace them. False before
    the first frame, and on a GPU without ray queries, where the shadow
    maps answer instead.
    """
    export: bool
    """Whether every frame is exported. Destination is `config.export_dir`."""
    @property
    def huds(self) -> list[Hud]:
        """The live HUDs -- the same objects as `app.config.huds`, not copies.

        Edit them in `before_render`: `sim.huds[0].text = f"{i}/{n}"`. The
        text is a template, so `{it}`, `{fps}` and the rest still expand in
        whatever is written here.
        """
        ...
    @huds.setter
    def huds(self, value: Sequence[Hud]) -> None: ...
    def update(self) -> None:
        """Advance the iteration counter. The app calls this once per frame; a script
        normally does not need it.
        """
        ...
    def toggle_export(self) -> None:
        """Flip continuous frame export."""
        ...
    def export_once(self) -> None:
        """Export the next frame only."""
        ...
    def request_facet_shadow(self, body: int) -> None:
        """Ask for `body`'s per-facet occluded fractions, read back from the GPU
        shadow map after this frame renders.

        Request from `before_render`, read from `after_render`: the shadow map
        only holds this frame's geometry once it has been drawn. Reading from
        `before_render` instead still works but returns the *previous* frame's
        result.
        """
        ...
    def facet_shadow(self, body: int = ...) -> numpy.ndarray | None:
        """Per-facet occluded fractions for `body`, or `None` if they were not
        computed this frame.

        One entry per facet, in `Mesh.facets` order: 0.0 fully lit, 1.0 fully
        shadowed, the mean of its corners and centre looked up as the image's
        pixels are, `shadows.pcf`'s kernel included; with the Sun a disc
        (`light.sun_as_point = False`), the fraction of the disc they do not
        see, graded across a penumbra. 1.0 facing away.

        Set `app.config.access_shadow_map = True` to have every body computed
        each frame, then read this from `after_render`.
        """
        ...
    def gpu_timings(self) -> object:
        """Milliseconds each GPU pass took, by name.

        `{"shadow": 0.42, "render": 3.10, "depth": 0.0, "text": 0.05,
        "gui": 0.0, "penumbra": 0.0}`, plus `"span"` -- first timestamp to
        last -- and `"frame"`, the iteration they were measured on.
        `"penumbra"` is the Sun's disc's own pass, 0 with a point Sun.

        Empty unless `config.gpu_timing` is on, and empty on an adapter
        without timestamp queries. **The numbers lag the current iteration**
        by a frame or two -- reading them back without blocking means reading
        what has already finished -- which is why `"frame"` is in there: quote
        that, not `sim.state.iteration`.

        **The per-pass figures overlap and must not be added.** Each is how
        long that pass was resident on the GPU, queue wait included, so four
        bodies report 4.6 ms of shadow passes inside a 3.9 ms frame. Compare
        `"span"` with the frame time; use the per-pass numbers for what moves
        when something changes, not as a budget.
        """
        ...
    def visibility(self) -> object:
        """What the last frame could see, and what it actually drew.

        Always `{"bodies", "visible", "clipped_near", "clipped_far",
        "outside_sides"}`; plus `"drawn"` and `"frame"` when
        `config.occlusion_queries` is on.

        `visible` is each body's **bounding box against the frustum**, so it
        says a body could be seen, not that it was: one wholly behind another
        still counts, and the four keys sum to `bodies`. `drawn` is the
        occlusion query -- how many actually put samples on screen -- and
        **lags the current iteration** by a frame or two, which is what
        `"frame"` is for. Quote that, not `sim.state.iteration`.
        """
        ...
    selected_facets: list[tuple[int, int]]
    """The facets picked by clicking, as `(body, facet)` pairs."""
    def toggle_facet(self, body: int, facet: int) -> bool:
        """Select a facet, or deselect it if it already is.

        Returns whether it is selected afterwards. The same call a click
        makes, so a script and the pointer cannot get out of step.

        The facet takes `config.selection.color` and colour-mode 1, which the
        shader honours for that facet alone; deselecting puts back whatever
        its vertices had. On an *indexed* mesh those vertices are shared with
        its neighbours and the colour bleeds -- load with `flatten=True`,
        which per-facet work wants anyway.
        """
        ...
    def clear_selection(self) -> None:
        """Put every selected facet back to the colour it had, and empty the list."""
        ...
    image_size: tuple[int, int]
    """`(width, height)` in pixels of the image the last frame was drawn at:
    what `project` measures in, and what an exported frame measures.
    `(0, 0)` until a frame has been drawn.
    """
    def project(self, point: Sequence[float] | numpy.ndarray) -> tuple[float, float] | None:
        """`(x, y)` where a world point lands in the last frame drawn, or `None`
        behind the camera.

        Pixels from the image's top-left corner, `x` right and `y` down, so
        the image spans `(0, 0)` to `image_size`. Pixel `(i, j)` covers
        `i..i + 1` by `j..j + 1`: `int(x), int(y)` is the pixel a point falls
        in, indexing an exported frame and `facet_id_map` as `[int(y),
        int(x)]`. A point outside the field of view still gets a position,
        outside that range.

        Read after the frame is drawn -- `after_render`, or after `step()`
        returns -- and before moving anything: the camera and the bodies are
        taken as they stand.
        """
        ...
    def project_body(self, body: int) -> tuple[float, float] | None:
        """`(x, y)` where `body`'s centre lands in the last frame drawn, or
        `None` behind the camera. See `project`.

        The centre is the origin of the body's own frame, which is where its
        `mat` puts it -- the SPICE position, for a body placed from SPICE.
        """
        ...
    def project_facet(self, body: int, facet: int) -> tuple[float, float] | None:
        """`(x, y)` where the centre of `facet` of `body` lands in the last frame
        drawn, or `None` behind the camera. See `project`.

        The centre is the mean of its three corners, where `selection.labels`
        writes its index. A projection, not a visibility test: a facet on the
        far side of the body, or behind the other one, lands on the disc that
        hides it. `facet_id_map` says which facets were actually drawn.
        """
        ...
    def pick_facet(self, origin: Sequence[float] | numpy.ndarray, direction: Sequence[float] | numpy.ndarray) -> tuple[int, int, list[float], list[float]] | None:
        """The nearest facet a ray hits, across every body.

        `(body, facet, world_point, body_point)`, or `None`. The body point is
        in the shape model's own frame, which is what a latitude and longitude
        have to come from.
        """
        ...
    def facet_illumination(self, body: int) -> numpy.ndarray | None:
        """Per-facet direct insolation, normalised: `max(0, cos i) * (1 - occluded)`.

        **This, not `facet_shadow`, is what "lit" means.** The shadow map
        answers one question -- is anything between this facet and the Sun --
        and a facet with nothing in the way is still dark if it faces away.
        On a crater that is most of the far wall; on a convex body it is about
        half of it.

        0 is dark, 1 is facing the Sun with nothing in the way. The cosine is
        clamped at zero, so a facet tilted away reads 0 rather than negative.

        ```python
        illum = sim.facet_illumination(0)
        lit = float((illum > 0).mean())          # fraction receiving any sun
        mean_insolation = float(illum.mean())    # and how much, on average
        ```

        Same availability as `facet_shadow`: `None` until a shadow result for
        that body has been read this frame, which `config.access_shadow_map`
        or `request_facet_shadow` arranges.
        """
        ...
    def facet_incidence(self, body: int) -> numpy.ndarray:
        """Per-facet `max(0, cos i)`: how squarely each facet of `body` faces
        the Sun, from its pose and the Sun's position as they stand -- the
        moment `mat` or `sun.pos` is set, before `step()` draws anything.

        Geometry alone, nothing in the way counted: right for a convex body
        on its own, and what `kalast.tpm.core.solar_bc` takes. A body that
        shadows itself or another wants `facet_illumination`, which is this
        times the unblocked fraction the shadow map reads back.

        ```python
        cosi = sim.facet_incidence(0)
        ```

        A pose that scales the body -- `bod.mat[:3, :3] = turn @ numpy.diag([a,
        b, c])`, flattened along its pole -- is taken as the renderer takes
        it, each normal turned to stay normal to the surface drawn: the shape
        can stay in `mat`, the mesh as loaded.

        An `IndexError` for a body that does not exist, rather than `None`:
        every body loaded has a mesh, so `None` was only ever a wrong index,
        and it made each `solar_bc(t, dau, cosi, ...)` an error in the
        editor, `cosi` being possibly `None`.
        """
        ...
    def facet_mean_incidence(self, body: int, spin_axis: Sequence[float] | numpy.ndarray | None = ...) -> numpy.ndarray:
        """Per-facet `max(0, cos i)` averaged over a spin about `spin_axis` --
        the body's own axis, in its frame, `z` unless given -- from its pose
        and the Sun's position as they stand: each facet's
        `kalast.tpm.core.mean_incidence`, of its latitude and the Sun's.

        What `core.effective_temperature` takes as `r` -- in place of the
        whole sphere's 1/4 -- to start each column at its latitude's
        effective temperature, 0 K in the polar night:

        ```python
        temperature = core.columns(nz, nf, core.effective_temperature(dau, sim.facet_mean_incidence(0), prop.albedo, prop.emissivity))
        ```

        The Sun's latitude is read from the pose as it stands: with the spin
        axis tilted, set the tilt first. A scale in the pose is taken as the
        renderer takes it. An `IndexError` for a body that does not exist.
        """
        ...
    def meridian_facets(self, body: int, longitude: float = ..., step: float = ...) -> tuple[numpy.ndarray, numpy.ndarray]:
        """The facets along a meridian of `body`, pole to pole, and the latitude
        each has (degrees), as two arrays: for each latitude from -90 to 90
        `step` degrees apart, the facet whose centre lies nearest it in
        direction from the body's centre on the meridian at `longitude` --
        each facet once, so a coarse mesh can give fewer.

        ```python
        meridian, latitudes = app.simulation.meridian_facets(0)
        surface = temperature[0, meridian]        # pole to pole
        ```

        In the body's own frame, `z` its spin axis and `x` longitude 0, and on
        its shape as its pose stretches it: a spin or a tilt in the pose
        changes nothing, a scale along the body's own axes counts -- set a
        scaled pose first. Any shape centred on its origin; on a concave one,
        the facet pointing most nearly along the direction. A `ValueError` for
        a `step` outside (0, 180] or a body with no mesh, an `IndexError` for
        a body that does not exist.
        """
        ...
    def request_hemicube(self, body: int = ..., facets: numpy.ndarray = ..., resolution: int = ..., batch: int = ...) -> None:
        """Ask for hemicube view factors for `facets` of `body`, this frame.

        Request from `before_render`, read with `hemicube` from
        `after_render`. This is a precompute, not a per-frame query: a full
        10,000-facet matrix is minutes of GPU work and 400 MB dense. For a
        rigid body the self view factors are fixed in the body frame, so it is
        computed once per shape model and reused.

        `resolution` is one hemicube face; the delta form factors close to
        unity as `1/resolution^2`, reaching 3e-5 at 128. `batch` hemicubes are
        accumulated on the GPU before a readback.
        """
        ...
    def hemicube(self) -> numpy.ndarray:
        """`(view_factors, offsets)` from the last `request_hemicube`, or `None`.

        `view_factors` has shape `(len(facets), n_total)` over a facet index
        space shared by every loaded body, so one array carries self *and*
        mutual view factors. `offsets[b]` is where body `b` starts, so
        `vf[:, offsets[b]:offsets[b] + n_b]` is the block for body `b`.

        Rows sum to at most 1; the shortfall is the fraction radiated to
        space. Occlusion is included, by the other body as well as by the
        body's own terrain.
        """
        ...
    def request_facet_pick(self, x: int, y: int) -> None:
        """Ask for the facet under one pixel of the rendered image.

        Request from `before_render`, read with `facet_pick` from
        `after_render`. `(0, 0)` is the top-left, indexing the image the same
        way `facet_id_map` does.

        The same second geometry pass the ID map costs, but **one texel** comes
        back rather than the whole framebuffer -- ~12 MB and 2.9M texels
        unpadded on the CPU at a 2116x1376 target. That is what makes it a pick
        rather than a data product.
        """
        ...
    def facet_pick(self) -> tuple[int, int, list[float], list[float]] | None:
        """`(body, facet, world_point, body_point)` for the last requested pixel,
        or `None`.

        The same answer and the same shape as `pick_facet`, except the facet
        comes from the rasteriser rather than from a ray tested against every
        facet, so the cost does not grow with the mesh. The point still comes
        from a ray -- one triangle test against the facet the pixel named.

        `None` where nothing was drawn under the pixel. **Only flattened meshes
        are drawn**, since the facet index comes from the vertex index; use
        `pick_facet` for an indexed mesh, or for a ray that does not start at
        the camera, such as an instrument boresight.
        """
        ...
    def request_facet_id(self) -> None:
        """Ask for a facet index map from the camera's point of view this frame.

        Request from `before_render`, read with `facet_id_map` from
        `after_render`. Unlike the shadow query there is no config flag to
        enable it permanently: it renders the scene a second time and blocks
        on a readback, so it is meant for the frames a data product comes
        from.
        """
        ...
    def facet_id_map(self) -> numpy.ndarray:
        """`(ids, offsets)` for the last requested frame, or `None`.

        `ids` is `(height, width)` of `uint32`: 0 where nothing was drawn,
        otherwise `1 + offsets[body] + facet`. So for body `b`,

        ```text
        mask  = (ids > offsets[b]) & (ids <= offsets[b] + n_facets_b)
        facet = ids[mask] - offsets[b] - 1
        ```

        picks its pixels and their facet indices, in `Mesh.facets` order.
        Depth is resolved by the rasteriser, so a facet missing from the map
        is one the camera genuinely cannot see -- occluded by another body,
        over the limb, or outside the field of view.

        Only flattened meshes are drawn: the facet index comes from the vertex
        index, which is only meaningful when each facet owns its vertices.
        """
        ...

class State:
    iteration: int
    """Frames advanced so far. Both callbacks see the same value for a given
    frame: it increments only once both have run.
    """
    is_paused: bool
    """Whether `P` has paused the simulation.

    The render loop keeps running -- the window stays responsive and the camera
    still moves -- but `before_render` and `after_render` are both skipped, so a
    script does not need its own check.
    """
    pause_after_iteration: int | None
    """Pause once this iteration has run -- the run's length, which plus
    one is what `{nit}` in a HUD reads -- or `None` to run on, the UI
    app's hold at the start included: `0` holds the run after its first.

    The app's own steps stop apart from it: Step, `K`, and the one
    iteration an opened script shows neither end a run early nor lose its
    length.
    """
    pause_at: int | None
    """The old spelling, one more: `pause_at = n` is `pause_after_iteration
    = n - 1`. Accepted for a release with a `DeprecationWarning`.
    """
    rate_limited: bool
    """Cap the frame rate at `rate_limit`; off runs as fast as it can. The
    frame waits for its turn, `app.step()` with it, and one step being one
    frame, the iteration rate is the same number.
    """
    rate_limit: float
    """Frames per second while `rate_limited`. Kept while the cap is off."""
    def toggle_pause(self) -> bool:
        """Flip the pause state, returning the new value."""
        ...

