# Generated by tools/gen_stubs.py -- do not edit by hand.
#
# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py

import numpy  # noqa: F401
from kalast.routines.setup import Body
from kalast.app.frame import Eye
from kalast.app.config import Hud
from kalast.mesh import Mesh

class Simulation:
    state: State
    bodies: list[Body]
    camera: Eye
    sun: Eye
    def load_mesh(self, object: str, object: list[list[float]] | None, object: bool | None, object: str | None) -> None:
        ...
    def add_mesh(self, object: Mesh, object: list[list[float]] | None) -> None:
        ...
    export: bool
    huds: list[Hud]
    def update(self) -> None:
        ...
    def toggle_export(self) -> None:
        ...
    def export_once(self) -> None:
        ...
    def request_facet_shadow(self, object: int) -> None:
        ...
    def facet_shadow(self, object: int) -> numpy.object | None:
        ...
    def request_hemicube(self, object: int, object: numpy.object, object: int, object: int) -> None:
        ...
    def hemicube(self) -> numpy.object:
        ...
    def request_facet_id(self) -> None:
        ...
    def facet_id_map(self) -> numpy.object:
        ...

class State:
    iteration: int
    is_paused: bool
    pause_at: int | None
    def toggle_pause(self) -> bool:
        ...

