#!/usr/bin/env python
"""Generate .pyi stubs for the PyO3 classes, so editors can complete them.

A compiled extension exposes no attributes to a static analyser, so without
stubs `app.config.<tab>` offers nothing. Hand-written stubs for a surface this
size rot within a week, so they are generated from the Rust source instead --
`#[getter]`/`#[setter]` become attributes, everything else a method.

Run:  python tools/gen_stubs.py          # write
      python tools/gen_stubs.py --check  # fail if stale (used by a test)
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Rust type -> Python annotation. Anything unmatched falls back to a bare name
# rather than guessing, so a wrong stub is never invented silently.
SCALARS = {
    "bool": "bool",
    "u8": "int", "u32": "int", "u64": "int", "usize": "int",
    "i32": "int", "i64": "int", "isize": "int",
    "f32": "float", "f64": "float", "Float": "float",
    "String": "str", "str": "str", "&str": "str",
    "()": "None",
}


def py_type(rust: str) -> str:
    t = rust.strip().removeprefix("pyo3::").removeprefix("crate::")
    t = re.sub(r"^&('[a-z]+ )?", "", t).strip()
    if t in SCALARS:
        return SCALARS[t]
    if m := re.fullmatch(r"Option<(.+)>", t):
        return f"{py_type(m.group(1))} | None"
    if m := re.fullmatch(r"(?:Py)?Result<(.+)>", t):
        return py_type(m.group(1))
    if m := re.fullmatch(r"Vec<(.+)>", t):
        return f"list[{py_type(m.group(1))}]"
    if m := re.fullmatch(r"\[(.+); *\d+\]", t):
        return f"list[{py_type(m.group(1))}]"
    if m := re.fullmatch(r"\((.+)\)", t):          # tuple
        parts, depth, cur = [], 0, ""
        for ch in m.group(1):
            if ch == "," and depth == 0:
                parts.append(cur); cur = ""
                continue
            depth += (ch in "<([") - (ch in ">)]")
            cur += ch
        parts.append(cur)
        return "tuple[" + ", ".join(py_type(p) for p in parts if p.strip()) + "]"
    if "PyArray" in t or "numpy" in t:
        return "numpy.ndarray"
    if "Bound<" in t or "Py<" in t:
        inner = re.search(r"Bound<[^,]+, *(.+)>", t) or re.search(r"Py<(.+)>", t)
        return py_type(inner.group(1)) if inner else "object"
    # A pyclass elsewhere in the tree: keep the bare name.
    t = t.split("::")[-1]
    return t if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", t) else "object"


def parse(src: str):
    """-> [(class, [(kind, name, type, doc)])] for one .rs file."""
    classes = []
    for m in re.finditer(r"#\[pyclass[^\]]*\]\s*(?:#\[[^\]]*\]\s*)*pub struct (\w+)", src):
        classes.append((m.group(1), []))
    if not classes:
        return []
    by_name = dict(classes)

    for im in re.finditer(r"#\[pymethods\]\s*impl (\w+) \{", src):
        cls = im.group(1)
        if cls not in by_name:
            continue
        # brace-match the impl block
        i = src.index("{", im.end() - 1)
        depth, j = 0, i
        while j < len(src):
            depth += (src[j] == "{") - (src[j] == "}")
            if depth == 0:
                break
            j += 1
        body = src[i:j]

        for fm in re.finditer(
            r"((?:\s*///[^\n]*\n)*)\s*((?:#\[(?:[^\[\]]|\[[^\]]*\])*\]\s*)*)"
            r"(?:pub )?fn (\w+)\s*(?:<[^>]*>)?\s*\(([^)]*)\)(?:\s*->\s*([^{]+))?",
            body,
        ):
            doc, attrs, name, args, ret = fm.groups()
            if "#[new]" in attrs:
                name = "__init__"
                ret = "()"          # a constructor returns None in Python
            if name.startswith("__") and name != "__init__":
                continue
            doc = "\n".join(
                l.strip().removeprefix("///").strip() for l in doc.strip().splitlines()
            ).strip()
            if "#[getter]" in attrs:
                by_name[cls].append(("attr", name, py_type(ret or "object"), doc))
            elif "#[setter]" in attrs:
                continue                      # the getter already declared it
            else:
                params = []
                for a in args.split(","):
                    a = a.strip()
                    if not a or a.startswith(("&self", "self", "slf", "mut self", "py:")):
                        continue
                    if ":" in a:
                        pn, pt = a.split(":", 1)
                        params.append(f"{pn.strip()}: {py_type(pt)}")
                by_name[cls].append(
                    ("meth", name, (py_type(ret) if ret else "None"), doc, params)
                )
    return classes


def render(classes) -> str:
    out = [
        "# Generated by tools/gen_stubs.py -- do not edit by hand.",
        "#",
        "# Regenerate after changing any #[pyclass]:  python tools/gen_stubs.py",
        "",
        "import numpy  # noqa: F401",
        "",
    ]
    for cls, members in classes:
        out.append(f"class {cls}:")
        if not members:
            out.append("    ...")
            out.append("")
            continue
        for m in members:
            if m[0] == "attr":
                _, name, typ, doc = m
                if doc:
                    out.append(f'    """{doc}"""' if False else "")
                    out[-1:] = []
                out.append(f"    {name}: {typ}")
            else:
                _, name, ret, doc, params = m
                sig = ", ".join(["self"] + params)
                out.append(f"    def {name}({sig}) -> {ret}:")
                if doc:
                    first = doc.splitlines()[0]
                    out.append(f'        """{first}"""')
                    out.append("        ...")
                else:
                    out.append("        ...")
        out.append("")
    return "\n".join(out) + "\n"


TARGETS = {
    "src/py/app/config.rs": "kalast/app/config.pyi",
    "src/py/app/simulation.rs": "kalast/app/simulation.pyi",
    "src/py/app/frame.rs": "kalast/app/frame.pyi",
    "src/py/app/body.rs": "kalast/app/body.pyi",
    "src/py/app/gpu.rs": "kalast/app/gpu.pyi",
    "src/py/app/mod.rs": "kalast/app/_core.pyi",
    "src/py/entity.rs": "kalast/entity.pyi",
    "src/py/mesh.rs": "kalast/mesh.pyi",
    "src/py/routines/setup.rs": "kalast/routines/setup.pyi",
    "src/py/tpm/properties.rs": "kalast/tpm/properties.pyi",
    "src/py/tpm/column.rs": "kalast/tpm/column.pyi",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    stale = []
    for rs, pyi in TARGETS.items():
        src = (ROOT / rs).read_text()
        text = render(parse(src))
        path = ROOT / pyi
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(pyi)
        else:
            path.write_text(text)
            print(f"wrote {pyi}")
    if stale:
        print("stale stubs (run tools/gen_stubs.py):", ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
