#!/usr/bin/env python
"""Fetch the files tab's icons and write the table that picks one per file.

The icons are Catppuccin's for VS Code (catppuccin/vscode-icons, MIT), the
Mocha flavour, at a pinned commit. Not all 650 of them: the ones a kalast
user's tree has in it -- scripts, meshes, data, notes, the repo's own files --
listed below. Which file gets which icon is the extension's own choice,
read from its `fileIcons.ts` and `folderIcons.ts` at the same commit, plus a
few kalast adds for files the extension does not know (`KALAST_*`).

    python tools/gen_icons.py      # after changing CATPPUCCIN or the lists

Writes `src/app/gui/assets/icons/*.svg`, their `LICENSE`, and
`src/app/gui/icon_table.rs`. Needs the network; nothing at build time does.
"""

import os
import re
import urllib.request

CATPPUCCIN = "b6915da9f6889b683a110aa747de96c2820a537d"
RAW = f"https://raw.githubusercontent.com/catppuccin/vscode-icons/{CATPPUCCIN}"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "src", "app", "gui", "assets", "icons")
TABLE = os.path.join(ROOT, "src", "app", "gui", "icon_table.rs")

FILES = """
_file python python-compiled python-config rust cargo cargo-lock 3d markdown
readme changelog license text json toml yaml csv image svg shader database
binary jupyter log zip pdf bash powershell batch git uv font exe c cpp
c-header html javascript typescript matlab julia fortran latex properties env
xml video audio makefile docker lib
""".split()
FOLDERS = """
src tests docs database dist scripts lib include images assets examples github
workflows vscode config benchmark git temp fonts api app
""".split()

# Files and folders the extension has no word for, named the way a kalast
# tree names them: SPICE kernels and data products, meshes' materials, stubs.
KALAST_EXT = {
    "pyi": "python",
    "mtl": "3d",
    "hdr": "image",
    "tm": "text",
    "fits": "database", "fit": "database", "npy": "database", "npz": "database",
    "h5": "database", "hdf5": "database", "nc": "database", "parquet": "database",
    "bsp": "database", "bc": "database", "bds": "database", "bpc": "database",
    "tpc": "text", "tls": "text", "tf": "text", "ti": "text", "tsc": "text",
    "dll": "binary", "so": "binary", "dylib": "binary", "pyd": "python-compiled",
    "whl": "zip",
}
KALAST_FOLDERS = {
    "notes": "docs", "res": "assets", "tools": "scripts", "target": "dist",
    "out": "dist", "output": "dist", "results": "dist",
    "data": "database", "mesh": "database", "meshes": "database",
    "spice": "database", "kernels": "database",
}


def get(path: str) -> bytes:
    with urllib.request.urlopen(f"{RAW}/{path}") as r:
        return r.read()


def entries(ts: str) -> dict[str, dict[str, list[str]]]:
    table = {}
    for m in re.finditer(r"^\s{2}'?([A-Za-z0-9_.\-]+)'?: \{(.*?)^\s{2}\},", ts, re.S | re.M):
        entry = {}
        for field in ("fileExtensions", "fileNames", "folderNames"):
            f = re.search(field + r": \[(.*?)\]", m.group(2), re.S)
            if f:
                entry[field] = re.findall(r"'([^']*)'", f.group(1))
        table[m.group(1)] = entry
    return table


def main() -> None:
    os.makedirs(ICONS, exist_ok=True)
    files = entries(get("src/defaults/fileIcons.ts").decode())
    folders = entries(get("src/defaults/folderIcons.ts").decode())

    names = sorted(set(FILES) | {"_folder", "_folder_open"} | {f"folder_{f}{o}" for f in FOLDERS for o in ("", "_open")})
    for name in names:
        with open(os.path.join(ICONS, f"{name}.svg"), "wb") as out:
            out.write(get(f"icons/mocha/{name}.svg"))
    with open(os.path.join(ICONS, "LICENSE"), "wb") as out:
        out.write(get("LICENSE"))

    by_ext, by_name, by_folder = {}, {}, {}
    for icon, e in files.items():
        if icon in FILES:
            for x in e.get("fileExtensions", []):
                by_ext.setdefault(x.lower(), icon)
            for x in e.get("fileNames", []):
                by_name.setdefault(x.lower(), icon)
    for icon, e in folders.items():
        if icon in FOLDERS:
            for x in e.get("folderNames", []):
                by_folder.setdefault(x.lower(), icon)
    for k, v in KALAST_EXT.items():
        by_ext.setdefault(k, v)
    for k, v in KALAST_FOLDERS.items():
        by_folder.setdefault(k, v)

    def table(name: str, pairs: dict[str, str]) -> str:
        rows = "".join(f'    ("{k}", "{v}"),\n' for k, v in sorted(pairs.items()) if '"' not in k and "\\" not in k)
        return f"pub(super) static {name}: &[(&str, &str)] = &[\n{rows}];\n"

    sources = "".join(f'        "{n}" => egui::include_image!("assets/icons/{n}.svg"),\n' for n in names)
    with open(TABLE, "w", encoding="utf-8", newline="\n") as out:
        out.write(
            "// Generated by tools/gen_icons.py from catppuccin/vscode-icons at\n"
            f"// {CATPPUCCIN}. Do not edit; run the tool.\n\n"
            "/// Lower-case file name -> icon, before any extension is looked at.\n"
            + table("BY_NAME", by_name)
            + "\n/// Lower-case extension, without the dot -> icon. The longest that\n/// matches wins: `tar.gz` before `gz`.\n"
            + table("BY_EXT", by_ext)
            + "\n/// Lower-case folder name -> icon; `folder_{icon}.svg`, `_open` when open.\n"
            + table("BY_FOLDER", by_folder)
            + "\n/// The SVG behind an icon's name. `_file` for a name it does not know.\n"
            "pub(super) fn source(icon: &str) -> egui::ImageSource<'static> {\n"
            "    match icon {\n" + sources + '        _ => egui::include_image!("assets/icons/_file.svg"),\n'
            "    }\n}\n"
        )
    print(f"{len(names)} icons, {len(by_name)} names, {len(by_ext)} extensions, {len(by_folder)} folders -> {os.path.relpath(TABLE, ROOT)}")


if __name__ == "__main__":
    main()
