name: Check

on:
  push:
    branches:        
      - '**' 

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Get SDL2
      run: |
        if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
          sudo apt install -y libsdl2-dev
        elif [ ${{ matrix.os }} == "macos-latest" ]; then
          brew install SDL2
        elif [ ${{ matrix.os }} == "windows-latest" ]; then
          cp include/win/SDL2.dll .
          cp include/win/SDL2.lib .
        fi
        
    - name: Check that code can compile
      run: cargo check --all-features