name: Check

on:
  push:
    branches:        
      - '**' 

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Get SDL2
      run: |
        echo "matrix: $MATRIX_OS"
        echo "matrix: ${{ matrix.os }}"

        echo "runner: $RUNNER_OS"
        echo "runner: ${{ runner.os }}"

        if [ $MATRIX_OS == "ubuntu-latest" ]; then
          sudo apt install -y libsdl2-dev
        elif [ ${{ matrix.os }} == "macos-latest" ]; then
          brew install SDL2
        elif [ ${{ matrix.os }} == "windows-latest" ]; then
          cp include/windows/* .
        fi
        
    - name: Check that code can compile
      run: cargo check --all-features