name: Check

on:
  push:
    branches:        
      - '**' 

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Install SDL2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install -y libsdl2-dev
        
    - name: Install SDL2
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install SDL2
        
    - name: Use SDL2 from repo/include/win
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cp include/win/SDL2.dll .
        cp include/win/SDL2.lib .

    - name: Check that code can compile
      run: cargo check --all-features