name: Check compilation

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install SDL2
      run: sudo apt install -y libsdl2-dev

    - name: Install kalast on cache
      uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: kalast

    - name: Check that code can compile
      run: cargo check

    - name: Build
      run: cargo build
