name: Build and upload release

on:
  push:
    tags:        
      - '**' 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install SDL2
      run: sudo apt install -y libsdl2-dev

    - name: Build
      run: cargo build && strip target/debug/kalast

    - name: Make bundle
      run: |
        mkdir -p bin/ubuntu
        cp -r examples bin/ubuntu
        cp -r target/debug/kalast bin/ubuntu
        tar czf kalast-${{ github.ref_name }}-tar.gz bin/ubuntu

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: kalast-${{ github.ref_name }}-tar.gz 
        prerelease: true