name: Build and Upload Release

on:
  push:
    tags:        
      - '**' 

jobs:
  release-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Set environment
      run: ./compile/environment.sh

    - name: Get SDL2
      run: ./compile/sdl.sh
      
    - name: Build
      run: ./compile/build.sh
      
    - name: Bundle
      run: ./compile/bundle.sh

    - uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.RELEASE_FILE }}
        prerelease: true