name: Build release

on:
  push:
    tags:        
      - '*' 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install SDL2
      run: sudo apt install -y libsdl2-dev

    - name: Build
      run: cargo build -r && strip target/release/kalast

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/kalast
        prerelease: true